### ISSUE TITLE
inconsistency with type definitions and errors

### ISSUE THREAD

**Issue by gdi2290** [s-panferov/awesome-typescript-loader#103]
I'm trying to use this module for these starters
https://github.com/angular/universal-starter
https://github.com/angular/angular2-starter
https://github.com/AngularClass/angular2-webpack-starter
but randomly I'll get errors because the loader sometimes can't find the type definitions in `typings/`. For example in angular2-starter is great but in universal-starter there are many errors. then in angular2-webpack-starter other devs are reporting random errors. Did I miss something because I can't figure out what's going that's different

**Comment by s-panferov** [comment]
@gdi2290 sorry for the delay in reply, fix landed in v0.16.1

**Comment by gdi2290** [comment]
@s-panferov thanks!
