### ISSUE TITLE
Property 'context' does not exist on type 'Require'.

### ISSUE THREAD

**Issue by pablorsk** [s-panferov/awesome-typescript-loader#106]
I have this code in xxx.JS:
```javascript
const req = require.context('./', true, /\.(controller|filter|service)\.ts$/);
```
And work fine. But when the file is xxx.TS the gulp says:
```
ERROR in [default] xxx.TS:5:20 
Property 'context' does not exist on type 'Require'.
```
What we are missing?

If you are interested on the use of this code: we need load dynamically TS files and put like angular.module.

Regards...

**Comment by s-panferov** [comment]
@pablorsk, thanks for your question. To solve this you can either

1) add '&+emitRequireType' to `awesome-typescript-loader` query string
2) or copy [this](https://github.com/s-panferov/awesome-typescript-loader/blob/master/lib/runtime.d.ts) file into your program.

**Comment by s-panferov** [comment]
If you're using `node` typings in your project, you need to add something like this to one of your .d.ts files:

```
interface NodeRequire {
    ensure(ids: string[], callback: WebpackRequireEnsureCallback, chunkName?: string): void;
    context(directory: string, useSubDirectories?: boolean, regExp?: RegExp): WebpackContext;
}
```

**Comment by pablorsk** [comment]
Thanks  @s-panferov! The answer 2 was the correct.

I found another solution and work it, I think is similiar:
```bash
tsd install webpack --save
tsd install webpack-env --save
```
Off couse, I have this line on my index.module.ts:
```typescript
/// <reference path="../../build/typings/tsd.d.ts" />
```
Thanks again!
