### ISSUE TITLE
Compiler options passed in query string are ignored

### ISSUE THREAD

**Issue by YuliaTsareva** [s-panferov/awesome-typescript-loader#107]
I would like to override one of the compiler options specified in tsconfig.json. I prefer to pass it in query string rather than add loader config in tsconfig.json.

But it seems that awesome-typescript-loader prefer the options from tsconfig.json. I did a little investigation and found that line of code:
`_.extend(options, configFile.compilerOptions);`

Would you consider to change this behaviour? It seems more reasonable to replace the standard options by the options specified specially for the loader.

**Comment by s-panferov** [comment]
@YuliaTsareva thanks for your report. Yes, this seems reasonable.

Landed as v0.17.0-rc.0

**Comment by YuliaTsareva** [comment]
Thank you for such a quick fix!
But it is still not available in npm...
