### ISSUE TITLE
Only one instance of babel-polyfill is allowed

### ISSUE THREAD

**Issue by AlanFoster** [s-panferov/awesome-typescript-loader#121]
Naively attempting to switch out `babel-loader` with `awesome-typescript-loader` within webpack throws the following babel-polyfill error 

```shell
> gulp watch
[23:47:05] Using gulpfile ~/app/gulpfile.js
[23:47:05] Starting 'watch'...
[23:47:05] Plumber found unhandled error:
 Error in plugin 'webpack-stream'
Message:
    only one instance of babel-polyfill is allowed
[23:47:05] Version: webpack 1.12.14

ERROR in only one instance of babel-polyfill is allowed
[23:47:05] webpack is watching for changes
```

With the following webpack snippet

```js
    loaders: [
      {
        test: /\.jsx?$/,
        exclude: /node_modules/,
        loader: 'awesome-typescript'
      }
    ]
```

**Comment by dsebastien** [comment]
We have the same issue and it's quite difficult to troubleshoot. @AlanFoster have you found anything?

**Comment by drywolf** [comment]
I had the same issue and am still having it when I try to enable `awesome-typescript-loader` in my webpack config.
To get back to work I switched back to [ts-loader](https://github.com/TypeStrong/ts-loader) which does not show that problem at all.

**Comment by s-panferov** [comment]
As I can see, this issue appears when two different libraries require two different versions of `babel-polyfill`. It's hard to do something with this, unfortunately :(
	
I can offer you one hacky and ugly solution, but I believe it will work:

```
loader: 'awesome-typescript-loader/dist.babel/index'
```

I'll think about how to make it better.

**Comment by drywolf** [comment]
Hi @s-panferov 

Thanks for looking into it.

I just tried out the new version `0.17.0-rc.7` and the mentioned loader string `'awesome-typescript-loader/dist.babel/index'`, but I get the following error when running webpack:

    Module build failed: ReferenceError: regeneratorRuntime is not defined
        at Object.loader (c:\_some_path_\node_modules\awesome-typescript-loader\dist.babel\index.js:56:44)

**Comment by drywolf** [comment]
I just patched my dist.babel/index.js files (in both modules) manually with the following code:

```
'use strict';

if (!global._babelPolyfill)
    require('babel-polyfill');
```

This works around the issue for me, not sure if it's a good idea but so far it seems to work just fine.

**Comment by s-panferov** [comment]
@drywolf your solution is good, but another library may be included afterwards and throw, because `require('babel-polyfill');` had been included already.

**Comment by messo** [comment]
Hey!

I am making a multi-module structure, and both module needs to have `awesome-typescript-loader` (the parent has the webpack.config.js, and the child itself is composed of typescript files)

I am experiencing the same issue, what do you recommend?

**Comment by s-panferov** [comment]
Require guard added in v0.18.0, please try.

**Comment by messo** [comment]
works for me! Thanks!

**Comment by AlanFoster** [comment]
Thanks for the fix :+1:
