### ISSUE TITLE
Any way to preprocess a file before compilation?

### ISSUE THREAD

**Issue by mjaneczek** [s-panferov/awesome-typescript-loader#122]
Hello!

Let's say that I have a file:
```typescript
class Example {
}
```

Now I want to add ```console.log('wtf');``` by the end of the file before the compilation process (ts->js).

```typescript
class Example {
}
console.log('wtf');
```

Is it achievable? I am looking for a callback or something.
Thanks!

**Comment by s-panferov** [comment]
@mjaneczek webpack already has mechanism called `loaders`, which allow to do exactly what you want.

**Comment by s-panferov** [comment]
Don't forget to enable `useWebpackText` option in `awesome-typescript-loader`, it you want to prepend it with another loader.

**Comment by mjaneczek** [comment]
@s-panferov The option useWebpackText helped.

Thanks! :)
