### ISSUE TITLE
Chaining custom loaders to awesome-typescript-loader doesn't seem to check the chained results

### ISSUE THREAD

**Issue by TheLarkInn** [s-panferov/awesome-typescript-loader#123]
I have created a custom loader to convert `import` statements to `require()` statements so I can continue to use imports, while allowing typescript to not error for using them on non .ts/.js files: 

### Custom Loader:
```javascript
module.exports = function convertES6StyleAndHTMLImportsToTypeScriptFriendlyRequires(source) {
  this.cacheable && this.cacheable();

  var hasES6StyleAndHTMLImportRegex = new RegExp(/import\s+(.+)\s+from\s+([\'|\"].+\.(html|jade|haml|twig|erb|css|scss|less|yaml|sass|styl)[\'\"]);?/, 'g');
  var results;

  try {
      results = source.replace(hasES6StyleAndHTMLImportRegex,
        "let $1 = require($2);\n"
      );
      console.log(results);
  } catch(e) {
      var err = "";
      if (e.location == null || e.location.first_column == null || e.location.first_line == null) {
        err += "Template Loader Error. The original exception was: " + e + "\n";
      } else {
        err += "ERROR ERROR ERROR ERROR";
      }
      throw new Error(err);
  }

  return results;
}
```

I wanted to run this loader first before `awesome-typescript-loader` compiles the files which have already been 'modified' by my custom loader. I have implemented it like this:

```javascript
      {
        test: /\.ts$/,
        loaders: ['awesome-typescript-loader', 'fix-es6-templates-import-with-typescript-loader'],
        exclude: [/\.(spec|e2e)\.ts$/]
      },
```

However I am still getting the following errors: 
```
Child html-webpack-plugin for "index.html":
    chunk    {0} index.html 505 kB
         + 3 hidden modules

    ERROR in [default]
    File '/Users/mac88847/Code/angular2-webpack-starter/src/app/home/home.html' has unsupported extension. The only supported extensions are '.ts', '.tsx', '.d.ts'.

    ERROR in [default] /Users/mac88847/Code/angular2-webpack-starter/src/app/home/home.component.ts:7:25
    Cannot find module './home.html'.
```
It almost appears as if there are linting or typechecking that is still scanning the original source files and not the already 'modified' src files. Thanks for your help!

**Comment by s-panferov** [comment]
@TheLarkInn please try `useWebpackText` option. Does it help?

**Comment by TheLarkInn** [comment]
@s-panferov it worked successfully. Before you close this, do you think you could discuss why this fixed the problem. I just want to understand what the property does.

**Comment by s-panferov** [comment]
@TheLarkInn loader uses it's own dependency resolution to create dependency graph of TS files. This requires to load files from file system. Loader passes all the files into typescript's `createProgram` at early stages. The assumption here is that webpack will bring the same file to loader, so we can just don't use it and don't update typescript's `program` (it can be costly). `useWebpackText ` says that we need to use webpack's text and recreate the program, because out assumption about file content may be wrong.

**Comment by TheLarkInn** [comment]
Thank you so much great explanation.
