### ISSUE TITLE
Can't resolve file properly

### ISSUE THREAD

**Issue by NoNameProvided** [s-panferov/awesome-typescript-loader#124]
With `webpack ^2.1.0-beta.5`, `webpack-dev-server ^2.0.0-beta` and `awesome-typescript-loader 0.17.0-rc.6` I got module resolve errors, it seems atl cant find the modules if its referenced from the webpack root like `app/components/myComponent/myComponent.component.ts` adding the full location like `/User/username/dev/project/app/components/myComponent/myComponent.component.ts` works tho. 

This is a pretty generic error, so you should let me know what else info should I provide to help you track down the errors.

**Comment by s-panferov** [comment]
@NoNameProvided 

Hello, why do you expect paths like `app/components/myComponent/myComponent.component.ts` to resolve? If you're using `moduleResolution: 'node'`, you need to use relative paths.

Could you please provide:

1) Your TS version
2) `tsconfig.json` file
3) webpack.config.js
3) webpack's output
