### ISSUE TITLE
Error is occured if tsconfig has "sourceMap": false

### ISSUE THREAD

**Issue by aspirisen** [s-panferov/awesome-typescript-loader#125]
Hi, i have met strange error
`ERROR in [default]
Option 'sourceRoot' cannot be specified without specifying option 'sourceMap'.`

And during small investigation i have noticed that it is because of `"sourceMap": false` in my tsconfig.json, if i remove this line everything will work fine. I attached [example.zip](https://github.com/s-panferov/awesome-typescript-loader/files/225766/example.zip)

**Comment by s-panferov** [comment]
@aspirisen thanks, I'll try to fix this soon.

**Comment by s-panferov** [comment]
@aspirisen, this should be fixed in @0.17.0-rc.7
