### ISSUE TITLE
ts-loader by TypeStrong

### ISSUE THREAD

**Issue by nik-kor** [s-panferov/awesome-typescript-loader#127]
Hi!

I have a question about https://github.com/TypeStrong/ts-loader . 
It looks like your loader has more features than the previous one.  But they have a huge amount of tests.

Can you compare these loaders? Which one is better to use and why?

**Comment by s-panferov** [comment]
@nik-kor please see #94

**Comment by nik-kor** [comment]
Ok. It really should be in readme)
