### ISSUE TITLE
crypto.createCredentials and crypto.Credentials are deprecated

### ISSUE THREAD

**Issue by galtalmor** [s-panferov/awesome-typescript-loader#131]
I've Upgraded from version 0.16.2 to 0.17.0 and since the upgrade I see the following message:
```
(node) crypto.createCredentials is deprecated. Use tls.createSecureContext instead.
(node) crypto.Credentials is deprecated. Use tls.createSecureContext instead.
```

Did I miss something that was required before upgrading?
Thanks.

**Comment by s-panferov** [comment]
Hello @galtalmor, which node version are you using?

**Comment by galtalmor** [comment]
@s-panferov v4.2.2

**Comment by raybooysen** [comment]
I see the same issue with node 5

**Comment by s-panferov** [comment]
Thanks, I'll try to fix this.

**Comment by TomaszScisloGS** [comment]
Same for me in Node 5.1.0

**Comment by jtrinklein** [comment]
occurs in 4.2.4 as well

**Comment by s-panferov** [comment]
This weird issue is because of babel's require interop, which transpiles this:

```
import * as crypto from 'crypto';
```

into `interopRequireWildcard(require('crypto')` call, which iterates through `crypto`'s properties.

**Comment by s-panferov** [comment]
Fixed in v0.18.0, please try.

**Comment by galtalmor** [comment]
It seems like you fixed it.
Can you publish v0.18.0 on npm please?
Cheers.

**Comment by s-panferov** [comment]
@galtalmor it's already published in `next` tag.

**Comment by galtalmor** [comment]
:+1: 
Thanks.

**Comment by masaeedu** [comment]
@s-panferov Not using the library, so maybe slightly off topic, but how did you fix this? Having the same issue importing `* as crypto from "crypto"` with Babel.
