### ISSUE TITLE
Build errors with `npm link` dependencies

### ISSUE THREAD

**Issue by messo** [s-panferov/awesome-typescript-loader#132]
I have the following two modules:

* `@my/core` module: has dependencies to actual 3rd party libs
* `@my/bundle` module: has dependency to `@my/core`, and `devDependencies` to `webpack`, loaders, etc.

When I publish `@my/core` to internal npm repo, and I do `npm install` for `@my/bundle` then
`$ webpack`
builds without error. Perfect!

Once I do `npm link` in the `@my/core` module, and I _replace_ the `@my/core` dependency inside `@my/bundle` with `npm link @my/core` (the directory structure is the same, except that `node_modules/@my/core` is now a symlink), then webpack build fails with:

```
ERROR in ./src/app.module.ts
Module build failed: Error: Cannot resolve module 'moment' in C:\Dev\webpack-spike-svn\core\src\core
    Required in C:\Dev\webpack-spike-svn\core\src\core\application.service.ts
    at ResolutionError.Error (native)
    at new ResolutionError (C:\Dev\webpack-spike-svn\bundle\node_modules\awesome-typescript-loader\dist.babel\deps.js:515:88)
    at C:\Dev\webpack-spike-svn\bundle\node_modules\awesome-typescript-loader\dist.babel\deps.js:340:37
    at run (C:\Dev\webpack-spike-svn\bundle\node_modules\core-js\modules\es6.promise.js:89:22)
    at C:\Dev\webpack-spike-svn\bundle\node_modules\core-js\modules\es6.promise.js:102:28
    at flush (C:\Dev\webpack-spike-svn\bundle\node_modules\core-js\modules\_microtask.js:18:9)
    at doNTCallback0 (node.js:419:9)
    at process._tickCallback (node.js:348:13)
```

I guess it is because actually in `core/node_modules` there aren't any modules, since those are inside `bundle/node_modules`.

If I do `npm install` inside `core`, then it requires the loaders which are already defined in bundle's devDependencies. I can only make it work if I copy the devDependencies from bundle to core as well.

Do you have any suggestion about this problem?

**Comment by s-panferov** [comment]
@messo you should try to add `resolve` and `resolveLoader` sections to your webpack config:

https://webpack.github.io/docs/configuration.html#resolve
https://webpack.github.io/docs/configuration.html#resolveloader

And specify `root` and `fallback` properties for both. Something like:

resolve: {
           root: [
                path.join(__dirname, "node_modules")
           ],
           fallback: path.join(__dirname, "node_modules")
},

**Comment by messo** [comment]
@s-panferov thank you very much! You've just saved my day :)
Actually I had this in my webpack.default.conf.js:

```
resolveLoader: {
        modulesDirectories: ['node_modules']
},
```

Because of the `npm link`, and the way the folders are structured (`core` and `bundle` are siblings in the root directory), the referenced modules in `core` couldn't be found (which are in `bundle/node_modules`), but adding:

```
        fallback: path.join(__dirname, 'node_modules')
```

solves the problem. Thank you! And sorry for posting this here, I thought it is awesome-ts-loader related, because of the stacktrace :)

**Comment by milhouse-dev** [comment]
I know this thread is pretty old, but I ran into same issues with webpack 4 and babel 7. Now there is a option for resolve section in webpack...js. My build passed after adding a symlinks: false to resolve section. Hope this helps somebody :)
