### ISSUE TITLE
"TypeError: Path must be a string" on nodejs 6 with no tsconfig

### ISSUE THREAD

**Issue by Heymdall** [s-panferov/awesome-typescript-loader#134]
For projects without tsconfig file awesome-typescript-loader is broken on nodejs 6. Seems like it trying to find correct outdir using config file path. But when there is no config `path.dirname(undefined)` will return `'.'` on node 5 and throw an error on node 6. It can be fixed by adding default value [here](https://github.com/s-panferov/awesome-typescript-loader/blob/master/src/instance.ts#L156)

**Comment by s-panferov** [comment]
Fixed in v0.18.0, please try.

**Comment by Heymdall** [comment]
Thanks, it's working!
