### ISSUE TITLE
0.18.0 not published to npm

### ISSUE THREAD

**Issue by dsebastien** [s-panferov/awesome-typescript-loader#143]
Hi,

Could you publish 0.18.0 to npm?

**Comment by s-panferov** [comment]
It's already published on npm in "next tag" because there are some unstable changes and I want it to be tested some more time.

**Comment by s-panferov** [comment]
It's already published on npm in "next tag" because there are some unstable changes and I want it to be tested some more time.

**Comment by s-panferov** [comment]
It's already published on npm in "next tag" because there are some unstable changes and I want it to be tested some more time.

**Comment by dsebastien** [comment]
I noticed thanks to a comment on another issue! That's good enough for me now; I'll open an issue if I find something wrong (nothing so far). Thanks!
