### ISSUE TITLE
Error "Unknown file" after upgrading from 0.17 to 1.1.1 (or 0.18)

### ISSUE THREAD

**Issue by brianchance** [s-panferov/awesome-typescript-loader#164]
After upgrading, I get 5 of these errors. They all relate to the same package, the files do exist.
`
ERROR in ./~/ng2-toasty/src/toasty.container.ts
Module build failed: Error: Unknown file C:\Code\Sparkle\src\Web\SdrBackofficeWebApp\node_modules\ng2-toasty\src\toasty.container.ts
    at State.fastEmit (C:\Code\Sparkle\src\Web\SdrBackofficeWebApp\node_modules\awesome-typescript-loader\dist.babel\host.js:300:23)
    at transform (C:\Code\Sparkle\src\Web\SdrBackofficeWebApp\node_modules\awesome-typescript-loader\dist.babel\index.js:215:52)
    at _callee3$ (C:\Code\Sparkle\src\Web\SdrBackofficeWebApp\node_modules\awesome-typescript-loader\dist.babel\index.js:265:42)
    at tryCatch (C:\Code\Sparkle\src\Web\SdrBackofficeWebApp\node_modules\regenerator-runtime\runtime.js:62:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (C:\Code\Sparkle\src\Web\SdrBackofficeWebApp\node_modules\regenerator-runtime\runtime.js:336:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (C:\Code\Sparkle\src\Web\SdrBackofficeWebApp\node_modules\regenerator-runtime\runtime.js:95:21)
    at fulfilled (C:\Code\Sparkle\src\Web\SdrBackofficeWebApp\node_modules\awesome-typescript-loader\dist.babel\index.js:31:32)
    at run (C:\Code\Sparkle\src\Web\SdrBackofficeWebApp\node_modules\core-js\modules\es6.promise.js:89:22)
    at C:\Code\Sparkle\src\Web\SdrBackofficeWebApp\node_modules\core-js\modules\es6.promise.js:102:28
    at flush (C:\Code\Sparkle\src\Web\SdrBackofficeWebApp\node_modules\core-js\modules\_microtask.js:18:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
 @ ./~/ng2-toasty/ng2-toasty.js 8:25-58 12:9-42
`

using Typescript 1.8.10
tsconfig:
`{
  "compilerOptions": {
    "target": "ES5",
    "module": "commonjs",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "sourceMap": true,
    "noEmitHelpers": true
  },
  "compileOnSave": false,
  "exclude": [
    "node_modules",
    "wwwroot"
  ]
}`

using webpack 1.13.1
loader call, I copied this from starter project, not sure what the exclude is doing.
`{
              test: /\.ts$/,
              loader: 'awesome-typescript-loader?forkChecker=true',
              query: {
                  'ignoreDiagnostics': [
                    2403, // 2403 -> Subsequent variable declarations
                    2300, // 2300 -> Duplicate identifier
                    2374, // 2374 -> Duplicate number index signature
                    2375, // 2375 -> Duplicate string index signature
                    2502  // 2502 -> Referenced directly or indirectly
                  ]
              },
              exclude: [/node_modules\/(?!(ng2-.+))/]
          }`

**Comment by brianchance** [comment]
Removed the extra query and exclude from loader call, same result.
`{
                test: /\.ts$/,
                loader: 'awesome-typescript-loader?forkChecker=true'
            }`

**Comment by gdi2290** [comment]
related https://github.com/AngularClass/angular2-webpack-starter

**Comment by t246246** [comment]
@brianchance 
Your `exculde` setting
```
exclude: [/node_modules\/(?!(ng2-.+))/]
```
means exclude node_modules but node_modules/ng2-xxx.
And when your 2nd trial without exclude setting means exclude nothing.  So both setting does not exclude `node_modules/ng2-toasty/src/toasty.container.ts`

I know nothing about ng2-toasty but suggest to try to exclude ng2-toasty somehow,
as `awesome-typescript-loader` itself works as expected I think.

**Comment by s-panferov** [comment]
@brianchance hello,

right now I'm working on the next version of the loader. Could you please try it (`2.0.0-rc.3` right now)? These errors must be solved there.

**Comment by brianchance** [comment]
@s-panferov - I tried 2.0.0-rc.3 and get different errors about not finding angular and other application files. Still using `{ test: /\.ts$/, loader: 'awesome-typescript-loader?forkChecker=true' }`

My code is throwing - 
ERROR in [default] C:/Code/Sparkle/src/Web/SdrBackofficeWebApp/client/app/app.component.ts:1:27
Cannot find module '@angular/core'.

ERROR in [default] C:/Code/Sparkle/src/Web/SdrBackofficeWebApp/client/app/app.component.ts:2:50
Cannot find module '@angular/router'.

ERROR in [default] C:/Code/Sparkle/src/Web/SdrBackofficeWebApp/client/app/app.component.ts:4:21
Cannot find module 'ng2-toasty/ng2-toasty'.

ERROR in [default] C:/Code/Sparkle/src/Web/SdrBackofficeWebApp/client/app/app.component.ts:6:31
Cannot find module './order'.

ERROR in [default] C:/Code/Sparkle/src/Web/SdrBackofficeWebApp/client/app/order/index.ts:1:15
Cannot find module './order.component'.


And the ng2-toasty files are throwing...

ERROR in [default] C:/Code/Sparkle/src/Web/SdrBackofficeWebApp/node_modules/ng2-toasty/src/toasty.component.ts:5:53
Cannot find module '@angular/core'.

ERROR in [default] C:/Code/Sparkle/src/Web/SdrBackofficeWebApp/node_modules/ng2-toasty/src/toasty.component.ts:6:30
Cannot find module '@angular/common'.

ERROR in [default] C:/Code/Sparkle/src/Web/SdrBackofficeWebApp/node_modules/ng2-toasty/src/toasty.component.ts:8:27
Cannot find module './toasty.config'.

ERROR in [default] C:/Code/Sparkle/src/Web/SdrBackofficeWebApp/node_modules/ng2-toasty/src/toasty.component.ts:9:24
Cannot find module './toasty.service'.

**Comment by brianchance** [comment]
@s-panferov - I went back and tried each release, the initial issue starts when changing from 0.17.0 to 0.18.0.

**Comment by s-panferov** [comment]
@brianchance please try `v2.0.0-rc.4`

**Comment by brianchance** [comment]
@s-panferov same output as 2.0.0-rc.3

**Comment by brianchance** [comment]
@s-panferov upgrading to angular2 rc2 I ran into some issues so I upgraded typescript to be 1.9.0-dev.20160409. With that typescript and 2.0.0-rc.4 I have the same set of original errors. So not fixed, but same output.

**Comment by brianchance** [comment]
When I put any exclude on the loader, it emits the second set of errors where it cannot find angular and other imported files
`{
                test: /\.ts$/,
                loader: 'awesome-typescript-loader?forkChecker=true',
                exclude: [/node_modules\/ng2-toasty/]
            }`

**Comment by s-panferov** [comment]
Fixed in `2.0.0` latest release candidates

**Comment by brianchance** [comment]
@s-panferov - thank you. Just tested and it is working.

**Comment by gdi2290** [comment]
thanks
