### ISSUE TITLE
Intermittent "Unknown file" Error with ts files required from js

### ISSUE THREAD

**Issue by dtabuenc** [s-panferov/awesome-typescript-loader#166]
I'm working in a large code base that has been slowly getting migrated to ts. When running webpack with the awesome-typescript-loader I will sporadically get an "Error: Unknown file". This is not deterministic, I may run webpack again immediately after getting this error and it will work. Somehow there seems to be a race condition, where under some circumstances it will not have added the file to the files array  by the time fastEmit() is called. 

This also does not seem completely random. When it does error out, it is always the same files that have this issue. The one commonality between these files are that they are typescript files that are some point or other being required from other plain javascript files, (mostly just for establishing a load-order dependency). 

I can try to debug this further, but am wondering if there are any thoughts as to possible causes? I added some logging statements to the code and the order that files get added to the "files" array in host.ts is not always the same. What determines this? Is this just promises not returning in a deterministic order? Under what circumstances could the code try to emit a file before it had been loaded into the file array?

**Comment by s-panferov** [comment]
@dtabuenc hello,

right now I'm working on the next version of the loader. Could you please try it (`2.0.0-rc.3` right now)? These errors must be solved there.

**Comment by s-panferov** [comment]
Fixed in `2.0.0` release candidates.
