### ISSUE TITLE
Add support for tsconfig.json

### ISSUE THREAD

**Issue by aindlq** [s-panferov/awesome-typescript-loader#17]
Would be great to have support for https://github.com/Microsoft/TypeScript/wiki/tsconfig.json. This file is used by many editors which support typescript.

Maybe it is possible to have something similar to gulp-typescript implementation -
https://github.com/ivogabe/gulp-typescript/issues/66#issuecomment-97169740
Any thoughts?

**Comment by s-panferov** [comment]
@aindlq it it definitely in the future plans. It will be implemented soon

**Comment by s-panferov** [comment]
@aindlq 

Achieved in v0.4.0. Please see [README.md](https://github.com/s-panferov/awesome-typescript-loader/blob/master/README.md) for details

**Comment by aindlq** [comment]
@s-panferov it was fast :+1: , could you please publish latest version to npm?

**Comment by s-panferov** [comment]
@aindlq  v0.5.2 was publised
