### ISSUE TITLE
Error when using inline sourcemaps

### ISSUE THREAD

**Issue by spiffytech** [s-panferov/awesome-typescript-loader#171]
I'm using inline sourcemaps but awesome-typescript-loader is compiling my code with `sourceMaps` enabled, which is incompatible.

**WebPack output / error**
```
$ node_modules/.bin/webpack --display-error-details
Hash: 3d6566755644095c840b
Version: webpack 1.13.1
Time: 774ms
     Asset     Size  Chunks             Chunk Names
webpack.js  5.04 kB       0  [emitted]  main
    + 1 hidden modules

ERROR in [default] 
Option 'sourceMap' cannot be specified with option 'inlineSourceMap'.
```

**webpack.config.js**

```
const webpack = require("webpack");
const path = require("path");

module.exports = {
  entry: "./index",
  output: {
    path: path.join(__dirname, "out"),
    filename: "webpack.js"
  },
  // Turn on sourcemaps
  devtool: "inline-source-map",
  resolve: {
    extensions: [".ts"]
  },
  module: {
    loaders: [
      {
        test: /\.ts$/,
        exclude: [/node_modules/],
        loader: "awesome-typescript-loader"
      },
    ]
  },
};
```

**tsconfig.json**

```
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "es5",
        "noImplicitAny": false,
        "inlineSourceMap": true,
        "inlineSources": true
    },
    "files": [
        "index.ts"
    ],
    "exclude": [
        "node_modules"
    ]
}
```

**Comment by s-panferov** [comment]
@spiffytech thanks for your report, I'll fix this.

**Comment by s-panferov** [comment]
@spiffytech I made some investigation for this and it appears that you don't need to compile with `inlineSourceMaps` to get inline source maps. When you inline source maps it's harder for the loader to extract them and pass to webpack. So just use [`inline-source-map` devtool](https://webpack.github.io/docs/configuration.html#devtool) in webpack.

**Comment by jzahka** [comment]
Thanks, this partly solved the issue for me.
I also had to change the test regex for the webpack sourcemap plugin to include .ts files (it tests for only .js and .css files by default).

``` js
plugins: [
  new webpack.SourceMapDevToolPlugin({
    test: /\.ts$/i
  })
]
```

**Comment by tkrotoff** [comment]
This should be documented that awesome-typescript-loader doesn't work in TypeScript `inlineSourceMap: true` and that `sourceMap: true` should be used instead.
