### ISSUE TITLE
[2.0] file change is not detected on Windows

### ISSUE THREAD

**Issue by t246246** [s-panferov/awesome-typescript-loader#178]
With awesome-typescript-loader 2.0.0-rc.12, ts file change is not detected when running `webpack-dev-server --hot --inline`. This seems to happen only on Windows.

Using
`webpack 2.1.0-beta.14`
`webpack-dev-server 2.1.0-beta.0`
`typescript 1.9.0-dev.20160623-1.0`

No problem with 1.1.1.

Best Wishes,

**Comment by s-panferov** [comment]
@t246246 thanks for your report. It's very hard for me to debug on Windows, everything is different :) I think this might be fixed in `2.0.0-rc.13`
