### ISSUE TITLE
didn't work together with ts-jsx-loader

### ISSUE THREAD

**Issue by flyon** [s-panferov/awesome-typescript-loader#18]
I just installed webpack because I would like jsx support with typescript.
Your plugin worked for making js bundles from TS, but adding !ts-jsx-loader didn't seem to do much.

            { test: /\.ts$/, loader: 'awesome-typescript-loader!ts-jsx-loader' }

When I switched to ts-loader it worked and the jsx got replaced:

            { test: /\.ts$/, loader: 'ts-loader!ts-jsx-loader' } 

This plugin do seem to give a bit more options than ts-loader, so it would be nice if it would work together with ts-jsx-loader

**Comment by s-panferov** [comment]
@flyon

Achieved in v0.4.0. See example in https://github.com/s-panferov/awesome-typescript-loader/blob/master/examples/tsjsx/webpack.config.js#L9
