### ISSUE TITLE
[2.0.1] Paths resolving incorrectly when `baseUrl:''`

### ISSUE THREAD

**Issue by TheLarkInn** [s-panferov/awesome-typescript-loader#184]
ATL Version: 2.0.1
Typescript Version: `typescript@next`

**Expected Behavior:** When you set `baseUrl` to an empty string (`''`), it should default to `path.dirname(configFilePath)`.

**Actual Behavior:** Currently instead of being the path relative to the config file, it is resolving to the directory that the process was run in (`process.cwd()`). 

Below is a small illustration showing the concern. 
![screen shot 2016-07-09 at 1 05 51 pm](https://cloud.githubusercontent.com/assets/3408176/16709449/cd513e6c-45d6-11e6-9a13-54ebb766fd29.png) 

I will hopefully get a PR in once I've verified it fixes the problem. 

PS. Paths should be ignored when the `baseUrl` property is NOT in the config, however should still work when `baseUrl:''`

**Comment by TheLarkInn** [comment]
@danielrosenwasser sounds right?

**Comment by DanielRosenwasser** [comment]
Sounds right! :smile:
