### ISSUE TITLE
Webpack watch not triggered if logic is not changed

### ISSUE THREAD

**Issue by nullptr128** [s-panferov/awesome-typescript-loader#186]
Hello!

The problem exists in TypeScript@2.0.0 version. Didnt checked earlier ones. Problem is - if I make a change on code that does NOT result in changing emitted JS, webpack watch is not triggered. For example adding an interface into some random .ts file does not trigger watch and does not reevaluate errors because interfaces are not compiled into final files. Second example could be with defining class fields, if you have a class and declare new field, webpack watcher is not triggered because this does not change output js files.

This forces me to restart webpack everytime I change only logic just to check if there are no errors. For example when I have a class with field someField: number;   <-- if I change type of this field to string, my code wont be checked for errors. I have to either add some dummy line with "logic" like "let x=0;" or restart webpack in order to check if changing declaration yielded any error.

**Comment by niieani** [comment]
@nullptr128 why don't you let your IDE do the type checking?

**Comment by nullptr128** [comment]
Unfortunately my IDE does not work too well because TypeScript checker crashes from time to time (https://github.com/Microsoft/TypeScript/issues/8717) so it cant be used reliably. Also sometimes it cant be worked around and requires restarting webpack in order to continue. For example, you can do something like this:

let controller = Express(); // without importing express

Webpack will now throw error that Express() is not declared. But when you add 

import * as Express from 'express'

It will not flush webpack at all requiring me to restart it.

**Comment by s-panferov** [comment]
This is unrelated to the loader, please see https://github.com/webpack/webpack/issues/2538. You can use [forkChecker](https://github.com/s-panferov/awesome-typescript-loader#forkchecker-boolean-defaultfalse) as a possible workaround.
