### ISSUE TITLE
Cannot read property 'exclude' of undefined

### ISSUE THREAD

**Issue by SteveVanOpstal** [s-panferov/awesome-typescript-loader#190]
The full error:

> Module build failed: TypeError: Cannot read property 'exclude' of undefined at applyDefaults (...\node_modules\awesome-typescript-loader\src\instance.ts:267:72)

The line of code where the error occurs ([here](https://github.com/s-panferov/awesome-typescript-loader/blob/master/src/instance.ts#L267)) seems like the first point where `compilerConfig` is used. 
So it seems like atl is unable to find or read my `tsconfig.json` file, it is however at the root and contains nothing out of the ordinary:
``` JSON
{
  "allowJs": true,
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "sourceMap": true,
    "removeComments": false,
    "noImplicitAny": false
  },
  "exclude": [
    "node_modules",
    "dist"
  ],
  "filesGlob": [
    "./src/**/*.ts",
    "./test/**/*.ts",
    "!./node_modules/**/*.ts",
    "src/custom-typings.d.ts",
    "typings/index.d.ts"
  ],
  "awesomeTypescriptLoaderOptions": {
    "useCache": true,
    "forkChecker": true,
    "cacheDirectory": "node_modules/.awesome-typescript-loader-cache"
  },
  "compileOnSave": false,
  "buildOnSave": false
}
```

**Comment by SteveVanOpstal** [comment]
The `compilerConfig` object content:

``` JavaScript
{ options: 
   { target: 2,
     module: 5,
     moduleResolution: 2,
     sourceMap: true,
     emitDecoratorMetadata: true,
     experimentalDecorators: true,
     removeComments: false,
     noImplicitAny: false },
  fileNames:  [ 'files' ],
  errors: [] }
```
It lacks the expected typingOptions:
``` JavaScript
typingOptions: { enableAutoDiscovery: false, include: [], exclude: [] },
```

Haven't found the cause for this issue yet.

**Comment by aspirisen** [comment]
Had the same issue, upgrading to TypeScript 1.8.10 helped

**Comment by Marianogboo** [comment]
please i am having this same issue and typescript is 2.0.2. please i need a fix as soon as possible.

**Comment by CuriousCain** [comment]
Yeah, I'm having this issue also on 2.0.2 and the very latest dev-version.

**Comment by Heliosare** [comment]
Same issue with tsc => Version 2.0.10

**Comment by Marianogboo** [comment]
Guys you need to do an npm cache clean, npm install and npm install -g angular-cli while you run as admin

**Comment by Heliosare** [comment]
Thks ! Its working

**Comment by kvey** [comment]
https://github.com/s-panferov/awesome-typescript-loader/blob/bd5cbb5869f4b4b4dcbcaff3bb7600d419326559/src/instance.ts#L266 in latest release version 2.2.4 uses typingOptions, latest typescript nightly uses typeAcquisition instead I believe? Master version of awesome-typescript-loader doesn't have the line, so probably resolved in next release

**Comment by DenisVuyka** [comment]
Having the same problem with latest Typescript

**Comment by joxford-soltech** [comment]
Yep, this is breaking with Typescript 2.1.4.

**Comment by sumitarora** [comment]
using version `2.0.10` solves the issue any version starting `2.1.x` have the issue

**Comment by lisamartin00** [comment]
Based on what kvey is saying, a temporary solution is to open node_modules/awesome-typescript-loader/dist/instance.js and comment out the offending line.

**Comment by paynoattn** [comment]
Installing typescript@2.0.10 as suggested by @sumitarora fixed it for me. So is this an awesome-typescript-loader bug, a tsconfig change that needs to take place, or a typescript bug?

**Comment by kvey** [comment]
It should be an awesome-typescript-loader bug but the resolution for it should already available in whatever release is next.

**Comment by squadwuschel** [comment]
Everythink is working with TypeScript Version 2.0.10 but when you upgrade your TypeScript Version to 2.1.4 the above error shows up. There are some changes that are not working with the Loader

**Comment by amcdnl** [comment]
Yup, getting same here just now. :(

**Comment by sfmskywalker** [comment]
Here too. :(

**Comment by ethanve** [comment]
Here too

**Comment by sotisoti** [comment]
Same here, downgrading to typescript 2.0.10 fixed the issue

**Comment by BharathLenin** [comment]
Got this error today as well

**Comment by KacerCZ** [comment]
Using Typescript 2.1.1 also "fixes" this issue.

**Comment by mduta** [comment]
still having issues with both 2.0 and 2.1.1

**Comment by VorgaT1339** [comment]
This error appeared after upgrading to TypeScript 2.1.4 (from 2.0.10) and downgrading back to 2.0.10 does not fix issue.

**Comment by squadwuschel** [comment]
@vorgaT1339 Have you cleared our node_modules folder and reinstalled all your dependencies? Then it should work again.

**Comment by readme42** [comment]
This morning our builds are failing because

`"typescript": "^2.0.10"`

installs 2.1.4 now. 

Nailing it down to `"typescript": "2.0.10"` solves this for the moment, but the Issue should remain open.

**Comment by readme42** [comment]
#293

**Comment by kekeh** [comment]
Changing 
```javascript
"typescript": "^2.1.1", 
```
to 
```javascript
"typescript": "2.1.1",
```
worked.

**Comment by sanyamkamat** [comment]
Mine worked by changing 

> "typescript": "^2.0.3",

to 

> "typescript": "2.0.10",

made it load the typescript module which doesn't break the awesome-typescript-loader module

**Comment by cdupetit** [comment]
Mine worked with beta version :
> "awesome-typescript-loader": "^3.0.0-beta.9"
> "typescript": "^2.1.4"

**Comment by mrin9** [comment]
Mine worked with beta version :

"awesome-typescript-loader": "^3.0.0-beta.9"
"typescript": "^2.1.4"

But only with angular-cli@1.0.0-beta.21 
fails with angular-cli@1.0.0-beta.22-1

**Comment by vicacid** [comment]
"typescript": "^2.1.4"
"awesome-typescript-loader": "^2.2.4",

Failed

**Comment by paralin** [comment]
Can we reopen this issue or make another to track the problem?

**Comment by ASK83** [comment]
Had the same problem and now using the following versions my app is working again:

"typescript":"2.1.4"
and the new "awesome-typescript-loader": "3.0.0-beta.10"

**Comment by squadwuschel** [comment]
@ASK83 with webpack 2?

**Comment by ritox842** [comment]
As @ASK83 said, 
```
 "typescript": "2.1.4",
 "awesome-typescript-loader": "3.0.0-beta.10"
```
Workd for me also

**Comment by kolkov** [comment]
```
"typescript": "2.1.4",
 "awesome-typescript-loader": "3.0.0-beta.13"
```
![image](https://cloud.githubusercontent.com/assets/3740898/21099325/b61f639a-c07e-11e6-8ab2-26061f827b04.png)
Whats wong?

**Comment by davidspiess** [comment]
Look at the configuration part in the documentation https://github.com/s-panferov/awesome-typescript-loader#configuration

**Comment by kolkov** [comment]
After modification:
```
var webpack = require('webpack');
var HtmlWebpackPlugin = require('html-webpack-plugin');
var ExtractTextPlugin = require('extract-text-webpack-plugin');
var helpers = require('./helpers');

var CheckerPlugin = require('awesome-typescript-loader');

module.exports = {
    entry: {
        'polyfills': './src/polyfills.ts',
        'vendor': './src/vendor.ts',
        'app': './src/main.ts'
    },

    resolve: {
        extensions: ['', '.ts', '.js']
    },

    module: {
        loaders: [
            {
                test: /\.ts$/,
                loaders: ['awesome-typescript-loader', 'angular2-template-loader']
            },
            {
                test: /\.html$/,
                loader: 'html'
            },
            {
                test: /\.(png|jpe?g|gif|svg|woff|woff2|ttf|eot|ico)$/,
                loader: 'file?name=assets/[name].[hash].[ext]'
            },
            {
                test: /\.css$/,
                exclude: helpers.root('src', 'app'),
                loader: ExtractTextPlugin.extract('style', 'css?sourceMap')
            },
            {
                test: /\.css$/,
                include: helpers.root('src', 'app'),
                loader: 'raw'
            }
        ]
    },

    plugins: [
        new CheckerPlugin(),

        new webpack.optimize.CommonsChunkPlugin({
            name: ['app', 'vendor', 'polyfills']
        }),

        new HtmlWebpackPlugin({
            template: 'src/index.html'
        })
    ]
};

```

```
D:\!Projects\TypeScript\test\angular2-webpack>npm start

> angular2-webpack@1.0.0 start D:\!Projects\TypeScript\test\angular2-webpack
> webpack-dev-server --inline --progress --port 8080

TypeError: Cannot read property 'parentCompilation' of undefined
    at getRootCompiler (D:\!Projects\TypeScript\test\angular2-webpack\node_modules\awesome-typescript-loader\src\instance.ts:50:17)
    at ensureInstanceStore (D:\!Projects\TypeScript\test\angular2-webpack\node_modules\awesome-typescript-loader\src\instance.ts:67:24)
    at Object.ensureInstance (D:\!Projects\TypeScript\test\angular2-webpack\node_modules\awesome-typescript-loader\src\instance.ts:90:5)
    at compiler (D:\!Projects\TypeScript\test\angular2-webpack\node_modules\awesome-typescript-loader\src\index.ts:37:20)
    at new loader (D:\!Projects\TypeScript\test\angular2-webpack\node_modules\awesome-typescript-loader\src\index.ts:16:18)
    at Object.<anonymous> (D:\!Projects\TypeScript\test\angular2-webpack\config\webpack.common.js:47:9)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\!Projects\TypeScript\test\angular2-webpack\config\webpack.dev.js:3:20)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10) 'TypeError: Cannot read property \'parentCompilation\' of undefined\n    at getRootCompiler (D:\\!Projects\\TypeScript\\test\\angular2-webpack\\node_modules\\awesome-typescript-loader\\src\\instance.ts:50:
17)\n    at ensureInstanceStore (D:\\!Projects\\TypeScript\\test\\angular2-webpack\\node_modules\\awesome-typescript-loader\\src\\instance.ts:67:24)\n    at Object.ensureInstance (D:\\!Projects\\TypeScript\\test\\angular2-webpack\\node_modules\\awesome-typescri
pt-loader\\src\\instance.ts:90:5)\n    at compiler (D:\\!Projects\\TypeScript\\test\\angular2-webpack\\node_modules\\awesome-typescript-loader\\src\\index.ts:37:20)\n    at new loader (D:\\!Projects\\TypeScript\\test\\angular2-webpack\\node_modules\\awesome-typ
escript-loader\\src\\index.ts:16:18)\n    at Object.<anonymous> (D:\\!Projects\\TypeScript\\test\\angular2-webpack\\config\\webpack.common.js:47:9)\n    at Module._compile (module.js:571:32)\n    at Object.Module._extensions..js (module.js:580:10)\n    at Modul
e.load (module.js:488:32)\n    at tryModuleLoad (module.js:447:12)\n    at Function.Module._load (module.js:439:3)\n    at Module.require (module.js:498:17)\n    at require (internal/module.js:20:19)\n    at Object.<anonymous> (D:\\!Projects\\TypeScript\\test\\
angular2-webpack\\config\\webpack.dev.js:3:20)\n    at Module._compile (module.js:571:32)\n    at Object.Module._extensions..js (module.js:580:10)'

D:\!Projects\TypeScript\test\angular2-webpack\node_modules\awesome-typescript-loader\src\instance.ts:50
    if (compiler.parentCompilation) {
                ^
TypeError: Cannot read property 'parentCompilation' of undefined
    at getRootCompiler (D:\!Projects\TypeScript\test\angular2-webpack\node_modules\awesome-typescript-loader\src\instance.ts:50:17)
    at ensureInstanceStore (D:\!Projects\TypeScript\test\angular2-webpack\node_modules\awesome-typescript-loader\src\instance.ts:67:24)
    at Object.ensureInstance (D:\!Projects\TypeScript\test\angular2-webpack\node_modules\awesome-typescript-loader\src\instance.ts:90:5)
    at compiler (D:\!Projects\TypeScript\test\angular2-webpack\node_modules\awesome-typescript-loader\src\index.ts:37:20)
    at new loader (D:\!Projects\TypeScript\test\angular2-webpack\node_modules\awesome-typescript-loader\src\index.ts:16:18)
    at Object.<anonymous> (D:\!Projects\TypeScript\test\angular2-webpack\config\webpack.common.js:47:9)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\!Projects\TypeScript\test\angular2-webpack\config\webpack.dev.js:3:20)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Andy\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v7.2.1
npm ERR! npm  v3.10.6
npm ERR! code ELIFECYCLE
npm ERR! angular2-webpack@1.0.0 start: `webpack-dev-server --inline --progress --port 8080`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular2-webpack@1.0.0 start script 'webpack-dev-server --inline --progress --port 8080'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular2-webpack package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack-dev-server --inline --progress --port 8080
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular2-webpack
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular2-webpack
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\!Projects\TypeScript\test\angular2-webpack\npm-debug.log

D:\!Projects\TypeScript\test\angular2-webpack>

```

**Comment by losnir** [comment]
@kolkov You have to export 'CheckerPlugin' from at.

Change:
```js
var CheckerPlugin = require('awesome-typescript-loader');
```

To:
```js
var { CheckerPlugin } = require('awesome-typescript-loader');
```

Notice the curly brackets which is a [destructuring assignment](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment).

**Comment by kolkov** [comment]
![image](https://cloud.githubusercontent.com/assets/3740898/21109368/c0ce7a1c-c0a9-11e6-83cd-df74d2ef009e.png)
 Is it ok?

**Comment by kolkov** [comment]
![image](https://cloud.githubusercontent.com/assets/3740898/21109522/80a5dd26-c0aa-11e6-8609-b44e5d119faa.png)

**Comment by albandaft** [comment]
Updated to typescript 2.1.1 solved my issue here, with angular 2.3.0

**Comment by kolkov** [comment]
I switched to ECMAScript 6 and underlining disappeared.
![image](https://cloud.githubusercontent.com/assets/3740898/21112137/a184054e-c0b5-11e6-8264-75c2a9ce890c.png)

**Comment by roshan3133** [comment]
Its fixed with "typescript": "^2.1.4" and "awesome-typescript-loader": "^3.0.0-beta.9"
and working fine

**Comment by sdudziak** [comment]
This code is resolving the issue; I don't want to create MR, so please apply, test it and close it soon.
`function applyDefaults(configFilePath, compilerConfig, loaderConfig) {
    compilerConfig.raw.compilerOptions.exclude = compilerConfig.raw.compilerOptions.exclude || [];`

**Comment by TheElf** [comment]
@sdudziak 

that code appears to have a couple of issues.

If that's the exclude from tsconfig.json, that is semantically different from a not specified exclude. (exclude in the default typescript implementation excludes node_modules, bower_componenets etc by default.)
see: [commandLineParser.ts, line 849-868](https://github.com/Microsoft/TypeScript/blob/2305c685607f274992b12ac6a0dc5224b0667e89/src/compiler/commandLineParser.ts#L849-L868)

irrespective of that. the compilerOptions node should be of type ts.CompilerOptions, which doesn't contain an exclude. if we are asking for exclude of compilerConfig.raw.compilerOptions, then that is just systemic of another bug.

Based on my previous reading of the code, @s-panferov seems to have a couple of places where he convolutes CompilerOptions and LoaderConfig. Its actually a problem in the loader plugin because it makes it so you can't specify many of the loader options because they conflict with compilerConfig.

All in all, if the above line fixes it, it doesn't seem like the right fix.

**Comment by sdudziak** [comment]
@TheElf

I haven't analysed this code so deeply, so you are probably right. My intention was to make quick-fix only.

**Comment by TheElf** [comment]
fair enough @sdudziak 

If you're up for it, this looks like it needs a pretty substantial go through/rewrite for webpack2

I'm still deciding if I'm going to work on that, or just see about improving performance in ts-loader. at-loader has been way useful, but its not in good shape with the new APIs from both webpack 2 and typescript 2.

Thanks for tossing in your quick fix, I submitted a PR with a hack comment that refs this issue to help us remember to remove it later

**Comment by KristiyanVachev** [comment]
Yup, downgrading to 2.0.10 worked. 
Just type npm install typescript@2.0.10

**Comment by RyanBalfanz** [comment]
@KristiyanVachev Same, that also worked for me. Thanks!

**Comment by luke88jones** [comment]
I've had this same issue but found I could use Typescript 2.1.4 with the latest, beta, version of atl, The only issue I had then was that it seems that the webpack entry points are now case sensitive (on windows at least).

**Comment by erwin16** [comment]
Installing typescript@2.0.10 and  awesome-typescript-loader@¨2.2.4  as suggested by @sumitarora fixed it for me too.
Is it going to be fixed in v3  ( with typescript 2.1.X ). ???
Happy New Year to all of you...

**Comment by szahn** [comment]
+1 This failed for me
```
{
    "awesome-typescript-loader": "^2.2.4",
    "typescript": "^2.0.10",
}
```
This worked: guess it had to be the exact version
```
{
    "awesome-typescript-loader": "=2.2.4",
    "typescript": "=2.0.10",
}
```

**Comment by jonbiere** [comment]
modifying my typescript package.json reference to a specific version fixed it for me. Thanks for the help. Wil likely upgrade to recent version of typescript once this issue is fixed with awesome-typescript loader.

"typescript": "=2.0.10"

**Comment by gjoris** [comment]
At the time of writing, this problem still persists. The fix above still works, though.

```
{
    "awesome-typescript-loader": "=2.2.4",
    "typescript": "=2.0.10",
}
```

**Comment by szahn** [comment]
Still no support for Typescript 2.1.5? Guess it's time to switch back to ts-loader.

**Comment by raybooysen** [comment]
@szahn what a silly thing to say. If it's that much of an issue, feel free to submit a PR.

**Comment by s-panferov** [comment]
`awesome-typescript-loader@3.x` supports latest TypeScript from the moment of its foundation.
