### ISSUE TITLE
Unclear installation instructions

### ISSUE THREAD

**Issue by abergs** [s-panferov/awesome-typescript-loader#2]
> npm install awesome-typescript-loader

is not enough. How would can I get TS 1.5 as a npm package?

**Comment by s-panferov** [comment]
@abergs sorry for the long time you have to wait for my answer. This library is not production-ready yet, and to install it now you need to do some `npm link`ing. So I don't recommend you to use it now until TS 1.5 is there.

If you still interested in the installation instructions, just say.

**Comment by s-panferov** [comment]
@abergs 	TypeScript 1.5-alfa is out, so now you can use v0.2.0 of the loader without any troubles. Please reopen this issue if you have any troubles.
