### ISSUE TITLE
Question: Failing the build on TypeScript compilation error

### ISSUE THREAD

**Issue by kevin-ashton** [s-panferov/awesome-typescript-loader#202]
Could someone explain how I might fail the build with a compile error. I need to fail for my CI. Ts-loader has a [section](https://github.com/TypeStrong/ts-loader#failing-the-build-on-typescript-compilation-error) on this and recommends using the webpack-fail-plugin. However that does not seem to be working for me with awesome-typescript-loader. Has anyone else got this to work? Any thoughts?

[](url)

**Comment by s-panferov** [comment]
@kevin-ashton `webpack-fail-plugin` should work. Could you provide some more info about your environment? (versions, webpack.config.js, OS, CI output)

**Comment by s-panferov** [comment]
@kevin-ashton another option is to run webpack with `--bail` flag, but in this case you will see only first error.

**Comment by kevin-ashton** [comment]
@s-panferov I must have had something misconfigured because the `webpack-fail-plugin` seems to be working just fine for me now. Not sure what I was doing wrong. Sorry about that.
