### ISSUE TITLE
Loader show errors about files inside node_modules

### ISSUE THREAD

**Issue by thekip** [s-panferov/awesome-typescript-loader#209]
I don't know is this behavior correct or not, but it stumped our team for a week. 

I have the simple webpack config: 

```js
 entry: {
        app: './src/app.ts',
    },
...
 loaders: [
      {
        test: /\.[tj]s$/,
        loaders: ['awesome-typescript-loader'],
        exclude: /node_modules/,
      },
...
```
The important part here is `exclude: /node_modules/`, so i thinked this is enough for loader to exclude library folder from transpiling or type checking. 

Actually it'is not. 

In entry point  `app.ts` we have just one import and dumb code which used this import: 
```js
import * as Rx from 'rx';

Rx.Observable.of(
    { foo: 1, bar: 2}
)
```
`rx` is npm module rx@3.1.2

When we run webpack, it print to console:

> ERROR in [default] ../front/node_modules/rx/dist/rx.all.js:7662:10
Duplicate identifier 'handleError'.

> ERROR in [default] ../front/node_modules/rx/dist/rx.all.js:7664:15
Duplicate identifier 'handleError'.

WTF? node_modules is exluded in loaders, but it is exactly typescript error, so it means loader was run for this files. 

Okay. May be, i defined a glob in tsconfig.json ?  

```js
{
  "compilerOptions": {
    "target": "es5",
    "allowJs": true,
    "module": "CommonJS",
    "removeComments": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true
  },
  "files": [
    "typings/index.d.ts",
    "src/definitions/definitions.d.ts"
  ]
}
```
As you can se, we didn't use globs here. 

Anyway error solved when I added 
```js
  "exclude": [
    "node_modules"
  ]
```
to tsconfig.json.

I spent a lot of time to found this solution. 
I think this behaviour is unobvious.

I use ATl 1.1.1 with typescript 1.8.10

It might be be helpfull for someone else.

**Comment by s-panferov** [comment]
This is by-design, because default `tsc` behavior is to include *every* `.d.ts` file it finds in the folder where `tsconfig.json` located. Use `exclude` or `include` directive to tune this behavior.

**Comment by thekip** [comment]
Actually there is not `.d.ts` file, `rx.all.js` is a `JS` file, and tsc compiler point to error inside this JS file, so your answer about by-design tsc behavior is wrong.

https://github.com/Reactive-Extensions/RxJS/blob/v3.1.2/dist/rx.all.js#L7662

**Comment by t57ser** [comment]
node_modules/xmlhttprequest-ssl/lib/XMLHttpRequest.js:208:6 
Unreachable code detected.

I see the same behaviour, that it is checking inside javascript files for errors.

**Comment by s-panferov** [comment]
> Actually there is not .d.ts file, rx.all.js is a JS file, and tsc compiler point to error inside this JS file, so your answer about by-design tsc behavior is wrong.

**Comment by thekip** [comment]
May be should add it to readme as required option in tsconfig.json?

ts-loader has this in readme.

**Comment by TomMarius** [comment]
Exclude in tsconfig.json is completely ignored (but works when I use standalone tsc); it's causing tons of errors:

`ERROR in [default] C:\Users\Tom\VSCodeProjects\personal\webpack-test2\node_modules\@types\react-router\lib\History.d.ts:9:22
Module '"C:/Users/Tom/VSCodeProjects/personal/webpack-test2/node_modules/history/lib/index"' has no exported member 'Location'.

ERROR in [default] C:\Users\Tom\VSCodeProjects\personal\webpack-test2\node_modules\@types\react-router\lib\History.d.ts:9:102
Module '"C:/Users/Tom/VSCodeProjects/personal/webpack-test2/node_modules/history/lib/index"' has no exported member 'Location'.

ERROR in [default] C:\Users\Tom\VSCodeProjects\personal\webpack-test2\node_modules\@types\react-router\lib\History.d.ts:10:25
Module '"C:/Users/Tom/VSCodeProjects/personal/webpack-test2/node_modules/history/lib/index"' has no exported member 'Pathname'.

ERROR in [default] C:\Users\Tom\VSCodeProjects\personal\webpack-test2\node_modules\@types\react-router\lib\History.d.ts:10:45
Module '"C:/Users/Tom/VSCodeProjects/personal/webpack-test2/node_modules/history/lib/index"' has no exported member 'Query'.`

My tsconfig.json:
`{
    "compilerOptions":
    {
        "target": "es6",
        "moduleResolution": "node",
        "jsx": "react",
        "allowJs": true,
        "removeComments": true,

        "allowSyntheticDefaultImports": true,
        "suppressImplicitAnyIndexErrors": true,
        
        "experimentalDecorators": true,
        "emitDecoratorMetadata": true,

        "allowUnreachableCode": false,
        
        "noImplicitAny": true,
        "noImplicitReturns": true,
        "noImplicitThis": true,
        "noUnusedLocals": true,
        "noUnusedParameters": true,

        "noImplicitUseStrict": false,
        "noFallthroughCasesInSwitch": false,
        
        "strictNullChecks": true,
        "allowUnusedLabels": false,
        "forceConsistentCasingInFileNames": true,
        "suppressExcessPropertyErrors": false,

        "stripInternal": true
    },

    "exclude": [
        "node_modules"
    ],

    "awesomeTypescriptLoaderOptions": {
        "forkChecker": false,
        "useCache": false,
        "useBabel": true
    }
}`
