### ISSUE TITLE
Errors not emptied on watch

### ISSUE THREAD

**Issue by Keats** [s-panferov/awesome-typescript-loader#21]
Hello

I'm trying to setup a webpack workflow and am using that loader.
However, when running the webpack-dev-server errors accumulate in between runs ie on every filesave the same error gets pushed to an array I presume and I end up with one error for each time I saved the file.
Any way to cleanup the array or do some dedup?

**Comment by Keats** [comment]
Actually, even new errors gets multiplied by the number of times since last save.
IE i get error 1 twice, make some changes now get error 2 three times

**Comment by s-panferov** [comment]
@Keats could you please show me your webpack config

**Comment by Keats** [comment]
```js
var path = require('path');
var webpack = require('webpack');


module.exports = {
  devtool: 'eval',
  entry: [
    'webpack-dev-server/client?http://localhost:3000',
    'webpack/hot/only-dev-server',
    './src/app/app.ts'
  ],
  output: {
    path: path.join(__dirname, 'build'),
    filename: 'bundle.js'
  },
  plugins: [
    new webpack.HotModuleReplacementPlugin(),
    new webpack.NoErrorsPlugin()
  ],
  resolve: {
    extensions: ['', '.js', '.ts']
  },
  resolveLoader: {
    modulesDirectories: ['node_modules']
  },
  module: {
    loaders: [
      {
        test: /\.ts$/,
        loaders: ['react-hot', 'awesome-typescript-loader']
      }
    ]
  }
};
```

And it's started with gulp
```js
gulp.task('webpack:server', function() {
  devServer = new webpackDevServer(devCompiler, {
    contentBase: outputFolder,
    hot: true,
    watchDelay: 100,
    stats: {
      colors: true,
      exclude: ['node_modules']
    }
  });

  devServer.listen(3000, "localhost", function(err) {
    if (err) {
      throw new $.util.PluginError("webpack:server", err);
    }
    $.util.log("Server running on http://localhost:3000");
  });
});
```

**Comment by s-panferov** [comment]
@Keats please check out v0.5.3

**Comment by s-panferov** [comment]
I've also added an example with react-hot-loader https://github.com/s-panferov/awesome-typescript-loader/tree/master/examples/react-hot

**Comment by Keats** [comment]
After updating, I now get
`Module build failed: TypeError: Cannot read property 'compilerOptions' of undefined` when running it.

This is my tsconfig.json
```js
{
    "compilerOptions": {
        "noImplicitAny": true,
        "removeComments": true
    }
}

```

**Comment by Keats** [comment]
Unrelated to that previous issue but how does this differs from https://github.com/jbrantly/ts-loader ? Might be worth putting in the readme

**Comment by Keats** [comment]
For the error above: https://github.com/s-panferov/awesome-typescript-loader/blob/master/src/index.ts#L95-L96 is correct in the ts but not in dist so I'm assuming dist is from a slightly older version

**Comment by RomanDidenko** [comment]
+1

**Comment by chicoxyzzy** [comment]
> Module build failed: TypeError: Cannot read property 'compilerOptions' of undefined

same

**Comment by Keats** [comment]
@s-panferov should be fixed by https://github.com/s-panferov/awesome-typescript-loader/pull/24

**Comment by s-panferov** [comment]
Sorry for the delay, I was afk on the weekend. PR was merged, version will be released soon.

**Comment by s-panferov** [comment]
v0.5.4

**Comment by Keats** [comment]
cheers mate, working for me
