### ISSUE TITLE
Regression 2.2.1: getAutomaticTypeDirectiveNames

### ISSUE THREAD

**Issue by cortopy** [s-panferov/awesome-typescript-loader#212]
I just upgraded to 2.2.1 and I'm getting the following error when packaging an angular app: 

```
Module build failed: TypeError: this.ts.getAutomaticTypeDirectiveNames is not a function
```

Reverting to 2.1.1 gets rid of this issue

**Comment by caleblloyd** [comment]
I am also getting this when doing npm install:

    ERROR in ./src/index.tsx
    Module build failed: TypeError: this.ts.getAutomaticTypeDirectiveNames is not a function
        at State.loadTypesFromConfig (../node_modules/awesome-typescript-loader/src/host.ts:148:36)
        at new State (../node_modules/awesome-typescript-loader/src/host.ts:142:14)
        at Object.ensureInstance (../node_modules/awesome-typescript-loader/src/instance.ts:150:19)
        at compiler (../node_modules/awesome-typescript-loader/src/index.ts:37:20)
        at Object.loader (../node_modules/awesome-typescript-loader/src/index.ts:18:18)
    @ multi main

**Comment by s-panferov** [comment]
Please provide your versions (ts, webpack, os)

**Comment by caleblloyd** [comment]
OS: Ubuntu 16.04 LTS
    Node: v6.3.0
    NPM: 3.10.3
    "webpack": "^1.13.0",
    "typescript": "^1.8.10",

**Comment by caleblloyd** [comment]
Sorry just read this from README.md:

**Supported TypeScript**

awesome-typescript-loader@2.x aims to support only typescript@2.x and webpack@2x, if you need old compilers please use 1.x or 0.x versions.

Will revert to 1.x.  Looks like the boilerplate I used (https://github.com/rangle/typescript-react-redux-starter) already fixed this too.

**Comment by cortopy** [comment]
Tried again now and 2.2.1 is not throwing the error any more :)

**Comment by skaor** [comment]
I have the same problem : this.ts.getAutomaticTypeDirectiveNames is not a function
I used **webpack 2.1.0-beta.22** and **awesome-typescript-loader 2.2.4** (tried with 1.13 of webpack too)
