### ISSUE TITLE
useBabel and useCache performance 

### ISSUE THREAD

**Issue by Haemoglobin** [s-panferov/awesome-typescript-loader#213]
Hi, 

I was using awesome-typescript-loader without Babel and had hot reload turned on in webpack, but in my project a single file change would result in webpack dev server sitting on a "recompiling" step for 7-10 seconds before the updated module came through. 

I read on the ATL docs that things can be sped up if combined with Babel and the useBabel and useCache ATL options. So I made the necessary changes, and also changed my tsconfig so it would target ES6 (rather than ES5) and the jsx setting from react to preserve. 

Unfortunately however with this setup I noticed no speed differences and it still takes as long for the updated module to come through. 

How fast would you expect things to be with this setting on? Could I have done something wrong?

Thanks,
Hamish

**Comment by c0gnize** [comment]
@Haemoglobin may be you use `devtool: 'source-map'`  which has a very slow rebuild speed: https://webpack.github.io/docs/configuration.html#devtool

**Comment by Haemoglobin** [comment]
Yes, I did notice this and you are right, using the eval source map sped it up considerably
