### ISSUE TITLE
Loader not working with typescript 2.0.2 (RC)

### ISSUE THREAD

**Issue by juanevp** [s-panferov/awesome-typescript-loader#221]
There seems to be a problem with the implementation of LanguageServiceHost.resolveTypeReferenceDirectives (according to mhegazy on [#10633](https://github.com/Microsoft/TypeScript/issues/10633)), which is resulting in a lot of types and modules not being found when processing (see issue for details and repro).

**Comment by panjiesw** [comment]
I hit this issue yesterday. When I compile directly using `tsc`, it works fine. When I run tests using Karma+Webpack+Awesome Typescript Loader, the tests run fine, but there are lots of TS compile errors, complaining it can't find my internal modules' definition files.

**Comment by Delagen** [comment]
Multiple errors with not resolvable types

**Comment by jnetterf** [comment]
This appears related to https://github.com/Microsoft/TypeScript/pull/9646.

**Comment by s-panferov** [comment]
I'll take a look soon.
