### ISSUE TITLE
Npm install is running for ever

### ISSUE THREAD

**Issue by mfilotto** [s-panferov/awesome-typescript-loader#23]
Hi,
Thanks for the lib.
I really would like to test it but npm install is running for ever.
Any idea ?

**Comment by warrenrumak** [comment]
I'm having the same problem.

**Comment by s-panferov** [comment]
@warrenrumak @mfilotto please check out v0.5.3

**Comment by mfilotto** [comment]
The problem is solved with that new version.
Thanks for your very quick answer.
