### ISSUE TITLE
Cannot find module 'highlight.js'

### ISSUE THREAD

**Issue by jpzwarte** [s-panferov/awesome-typescript-loader#249]
I previously reported this issue against webpack (https://github.com/webpack/webpack/issues/3051), but on further investigation this seems to be coming from awesome-typescript-loader.

The behavior i'm seeing is as follows:
- tsc runs fine without errors
- webpack with awesome-typescript-loader gives error for node modules which don't have @types modules

So i have various angular modules with @types/module_name counterparts. But highlight.js lacks a @types counterpart. I had one other module with the same situation and i also get a 'cannot find module' error for that one.

**Comment by s-panferov** [comment]
Fixed in 3.x branch
