### ISSUE TITLE
events/events.js' has unsupported extension.

### ISSUE THREAD

**Issue by whitecolor** [s-panferov/awesome-typescript-loader#261]
I've got strange error while build (build is ok though, only this erro):

```
ERROR in [default]                                                                                                                                                                            
File `.../my-project/node_modules/events/events.js' has unsupported extension. The only supported extensions are '.ts', '.tsx', '.d.ts'.  
```

Have only one loader:

``` ts
 module: {
    loaders: [
      { test: /\.ts$/, loader: 'awesome-typescript-loader'},
```

![image](https://cloud.githubusercontent.com/assets/736697/19840412/22dcfc9c-9f17-11e6-8cf4-c68e19b40f08.png)

Any suggestions how to fix?

**Comment by dsifford** [comment]
I'm also having pretty severe issues with this, though on a much larger scale. 

I updated babel-core (and friends) to the latest version and it appears to have broken the babel integration of ATSL. I'm getting the same warnings, but for every `.js` file that exists. Just prior to updating babel, I had zero issues.

**Comment by dsifford** [comment]
Reporting back: I have no idea what's going on, but it's likely the result of some npm dependency nightmare. I can get it to work or not work depending on the installation order of my packages. Wonderful!

**Comment by dsifford** [comment]
@whitecolor Try setting `allowJs: true` in your `tsconfig.json` compilerOptions. That did the trick for me.

**Comment by yuanfeiz** [comment]
@dsifford confirm that enable `allowJs` resolves the issue, ty!

Anyone knows how does this issue sneak in?

**Comment by whitecolor** [comment]
`allowJs` works, but it is hardly can be called a solution - one may have a project were one will have issues with this option enabled, and actually in my other projects where I use a-t-l I had no such issue, but didn't manage to debug it yet.

**Comment by donaldpipowitch** [comment]
I have this problem only with `typescript@next`. `typescript@2.0.6` works.

**Comment by s-panferov** [comment]
@donaldpipowitch I'll take a look.

**Comment by dsifford** [comment]
Can confirm that I'm also using `typescript@next`. Good catch @donaldpipowitch 👍

**Comment by whitecolor** [comment]
I'm too using `typescript@next`

**Comment by Truedrog** [comment]
Typescript 2.1 rc was released yesterday, any updates on this issue? (I am also having this).

**Comment by s-panferov** [comment]
Release 3.0.0-beta.0 should address these issues.

**Comment by prashaantt** [comment]
I'm still getting these kind of errors with `react-hot-loader` enabled, presently only for all `@types` modules:

![image](https://cloud.githubusercontent.com/assets/390540/20168585/fed5c452-a748-11e6-9e73-17aa076709a3.png)


Also, missing module imports are erroring out for the very first build, but not on subsequent incremental builds using HMR.

**Comment by whitecolor** [comment]
@s-panferov 
For me 3.0.0-beta seems to fix this, btw you don't have `beta` tag on this version.

**Comment by s-panferov** [comment]
Fixed in 3.x branch
