### ISSUE TITLE
tsconfig.json is not loaded

### ISSUE THREAD

**Issue by Milanoss** [s-panferov/awesome-typescript-loader#265]
**tsconfig.json configuration:**
{
 "compilerOptions": {
   "outDir": "builders",
   "module": "CommonJSbblabla",
   "target": "es9",
   "sourceMap": true,
   "inlineSourceMap": false,
   "inlineSources": false,
   "experimentalDecorators": true,
   "jsx": "react",
   "moduleResolution": "node"
 },
 "awesomeTypescriptLoaderOptions": {
   /* ... TODO */
 },
 "exclude": [
   "node_modules",
   "build",
   "typings/main",
   "typings/main.d.ts"
 ]
}

**webpack.config:**
entry: {
   app: [
     'eventsource-polyfill',
     'webpack-hot-middleware/client?reload=true',
     './src/client.tsx',
     './src/favicon.ico',
     './src/vendor/main.ts'
   ]
 },

 output: {
   path: path.resolve('./build/public'),
   publicPath: '/public/',
   filename: 'js/[name].js',
   pathinfo: true
 },

 module: {
   preLoaders: [
     {
       test: /\.tsx?$/,
       loader: 'tslint'
     }
   ],
   loaders: [
     {
       test: /\.tsx?$/,
       loaders:['react-hot-loader/webpack','awesome-typescript-loader']
     },

**Comment by s-panferov** [comment]
Please provide more info about what is wrong.
