### ISSUE TITLE
Release 3.0

### ISSUE THREAD

**Issue by s-panferov** [s-panferov/awesome-typescript-loader#267]
* [x] Refactor
* [x] Always fork a child process for speed
* [x] Remove all custom resolution logic
* [x] Support typescript 2.0.6 and the latest webpack@beta
* [x] Align configuration options with `ts-loader`
* [x] Test on typescript@next
* [x] Test on Windows
* [x] Receive feedback
* [x] Update README
* [ ] Consider to port separate-process-checker to `ts-loader`, #266 

Blockers:

* [x] #277
* [x] #279 
* [x] #282 
* [x] #287

**Comment by Ciantic** [comment]
I tested on windows, seems to work so far. I'll post here if I encounter something with my Windows setup.

Also good news! This beta.0 version seems to support react-hot-loader 3 (I couldn't get it working at all with older versions of awesome)

**Comment by s-panferov** [comment]
@Ciantic thanks! I appreciate that.

**Comment by endel** [comment]
I just tried out v `3.0.0.beta.0`, and I'm having this error:

```
Error: Cannot find module 'enhanced-resolve/lib/getInnerRequest'
```

Do you have any clue? Thanks!

**Comment by dsifford** [comment]
Just updated and it looks like `ForkCheckerPlugin` is now either broken, or deprecated. 

Also I'm getting this error:

```
(node:18815) Warning: Possible EventEmitter memory leak detected. 11 exit listeners added. Use emitter.setMaxListeners() to increaselimit
```

**Comment by niieani** [comment]
It would be good to tackle this issue before 3.0: https://github.com/s-panferov/awesome-typescript-loader/issues/129.

**Comment by cortopy** [comment]
It works really good for me on Linux. In fact, it just solved an issue I've had with tslint output for a long time https://github.com/s-panferov/awesome-typescript-loader/issues/273

**Comment by jefbarn** [comment]
beta.3 using typescript 2.1.1 just hangs after showing
```[at-loader] Using typescript@2.1.1 from typescript and "tsconfig.json" from C:\projects\dayapp/tsconfig.json```

**Comment by vascofernandes** [comment]
same problem as jefbarn but for TS 2.0.10

**Comment by s-panferov** [comment]
@vascofernandes do you have some example to reproduce?

**Comment by LennyThompson** [comment]
ATL  3.0.0-beta.3 is ignoring exclude configuration from webpack - using filter /\.(spec|e2e)\.ts/ still compiles the spec files. You can test this with the angular2-webpack-starter by updating ATL to latest and removing the ForkCheckerPlugin reference... Reverting to 2.2.1 fixes the problem.

**Comment by niieani** [comment]
@LennyThompson I think you should ignore those files from within `tsconfig.json`. If you need, you can create a second `tsconfig.json` for the production build that doesn't include these spec files.

**Comment by LennyThompson** [comment]
Thanks for the response Bazyli, but does that mean the exclude
configuration is ignored by ATL? and you need to control this through the
tsconfig?

Cheers
Lenny

**Comment by niieani** [comment]
Not sure what's the designed behavior for exclude configuration @LennyThompson, but ATL should follow the exclude list in tsconfig in any case.

**Comment by s-panferov** [comment]
@LennyThompson @niieani we have two different conceptions here:

1. "TypeScript program" — it's a scope of files which will be type-checked together. This scope is controlled by `tsconfig.json`.

2. Webpack Bundle — it's a scope of files which will be included to a result bundle. This scope is controlled by `webpack.config.js` and its exclude rules.

**Comment by niieani** [comment]
@s-panferov yeah, this is how I understood it. Good points to add to the README, though ;)

**Comment by LennyThompson** [comment]
Thanks guys, I'll go back to version 3 then.

**Comment by lhecker** [comment]
@s-panferov I'm constantly getting `Typescript checker was exited with non-zero error code` when using the `webpack` module. Strangely if I use the `webpack-dev-server` it works fine though. (Using the same `webpack.config.js`!)

Any idea what could cause or how I should debug this?

**Comment by jefbarn** [comment]
Just wanted to let you know that 3.0 beta.9 is working again with my project. Thanks!

**Comment by pselden** [comment]
Has anyone seen this issue before (with beta.9):

![screen shot 2016-12-06 at 11 00 25 am](https://cloud.githubusercontent.com/assets/709282/20932718/a6d9e1ba-bba3-11e6-92dc-2490c418ef83.png)

This is in a very large project that uses 2 instances of ATL (and unfortunately I can't post the code). If no one has encountered an issue like this before I'll try to produce a minimal sample project that exhibits it.

**Comment by cortopy** [comment]
@pselden I've had that many times. It means lodash definitions are included more than once in your parsing

**Comment by pselden** [comment]
https://github.com/s-panferov/awesome-typescript-loader/issues/267#issuecomment-265263340 -- thanks, I just never saw it before until I updated to 3.x beta.

How would I go about fixing that then -- making sure there's only one lodash in my node_modules? One of the reasons I thought it might be an issue with v3 was that it only happens during a rebuild.

**Comment by cortopy** [comment]
Whenever it's happened to me, there was always a lot of trial and error. It used to happen a lot with my npm-linked modules, but new versions of TS have fixed that. Try with different options in `tsconfig` too (exclude the right folders, include only what's needed, etc.)

**Comment by pselden** [comment]
Now with ATL .17 beta I'm seeing a lot of "unknown error"

```
{ seq: 348, success: true, payload: null } // logged out res
Unknown message:  null
```

And then the build fails -- while in previous versions it would succeed.  This seems to only be happening when running in production mode (with -p and no watch).

Any ideas where to look?
