### ISSUE TITLE
Slow rebuilds comparing to ts-loader?

### ISSUE THREAD

**Issue by asadsahi** [s-panferov/awesome-typescript-loader#269]
Detail can be found in [this](https://github.com/aspnet/JavaScriptServices/issues/325) issue. Rebuilds are ~4 times slower compared to ts-loader. Please let me know if more details required.

**Comment by whitecolor** [comment]
I too notices that recompile takes long.

**Comment by s-panferov** [comment]
@whitecolor please provide some additional information about your setup: OS, node version, at-loader version, tsconfig

**Comment by whitecolor** [comment]
@s-panferov 
It is not a problem of alt but something with webpack I believe. You you may check OP issue, my post is not relevant.

**Comment by asadsahi** [comment]
@s-panferov in my case I am using webpack 2 beta 27 as well and in the same project with ts-loader rebuild is ~200-~300 ms and ATL starts rebuilding late for some reason and when it rebuilds it takes around 1800-3000ms. Stats are given in the link given in my issue above.

**Comment by s-panferov** [comment]
@asadsahi what version of the loader you use?

**Comment by asadsahi** [comment]
Last time when I tried it was:

    "ts-loader": "1.2.2",

Vs

     "awesome-typescript-loader": "2.2.4",

**Comment by whitecolor** [comment]
@asadsahi 
btw try updated (last) versions of both.

**Comment by s-panferov** [comment]
@asadsahi could you please try awesome-typescript-loader@3.0.0-beta.9 on your codebase?

**Comment by asadsahi** [comment]
Thanks @whitecolor those happen to be latest versions.

@s-panferov will try with beta.9. Give me a sec.

**Comment by asadsahi** [comment]
@s-panferov , Thanks for bringing magic back in ATL.
With ts-loader:
![image](https://cloud.githubusercontent.com/assets/3470892/20716164/3a509fb6-b649-11e6-9e76-1f31fd7f8bee.png)

With awesome-typescript-loader:

![image](https://cloud.githubusercontent.com/assets/3470892/20716251/88ae9f28-b649-11e6-8543-42b00ba8cd4d.png)

Means, ATL is taking lead in 3.beta9 again.

BTW, what magic you have done? :)

**Comment by s-panferov** [comment]
@asadsahi the loader forks a process with TypeScript compiler and communicates with it via IPC. This leads to better parallelism.

**Comment by whitecolor** [comment]
I can confirm that  `beta.9` works at least faster than `beta.0`.
