### ISSUE TITLE
JSX support

### ISSUE THREAD

**Issue by KnisterPeter** [s-panferov/awesome-typescript-loader#27]
Please add jsx support.
The typescript-loader from andreypopp does work in combination with ts-jsx-loader which convertes template strings into JSX-JavaScript.
This does not work with awesome-typescript-loader anymore.

**Comment by s-panferov** [comment]
@KnisterPeter there is an example in https://github.com/s-panferov/awesome-typescript-loader/tree/master/examples/tsjsx

Please ensure that you have https://github.com/s-panferov/awesome-typescript-loader#usewebpacktext-string-defaultfalse option enabled.

**Comment by KnisterPeter** [comment]
Thanks :)
