### ISSUE TITLE
2.2.4 cannot find module for angular and lodash

### ISSUE THREAD

**Issue by NickTsitlakidis** [s-panferov/awesome-typescript-loader#270]
Hello, 

I'm trying to use 2.2.4 of ATL with Webpack 2.1.0-beta.25.

My imports are ES6 style, for example : `import * as angular from 'angular';`
And my typings are normally inside node_modules/@types

I have installed the typings for both lodash and angular but when I run the webpack task, I'm getting the following error : 
**Cannot find module 'lodash'.
Cannot find module 'angular'.**

I think it's something in my configuration because the same code works perfect when Intellij tries to compile it and no errors are thrown.

Any ideas on what I'm doing wrong?

**Comment by jskrzypek** [comment]
You should post your tsconfig.json file

**Comment by NickTsitlakidis** [comment]
Apparently the problem was that I didn't have angular installed through npm and I only had the types. Weird, the types should be able to work. Closing this nonetheless.
