### ISSUE TITLE
`enhanced-resolve` dependency is missing

### ISSUE THREAD

**Issue by marvinhagemeister** [s-panferov/awesome-typescript-loader#275]
The `enhanced-resolve` dependency is missing inside `package.json`. It is included by [paths-plugin.ts](https://github.com/s-panferov/awesome-typescript-loader/blob/1bd0eecd648462de7aad20dd3f7dd2313d33fc76/src/paths-plugin.ts#L7)

**Comment by dmcclureagl** [comment]
Temporary fix is to install it as a dev dependency as: npm install --save-dev enhanced-resolve

**Comment by s-panferov** [comment]
Thanks!
