### ISSUE TITLE
Dies on deleted file 3.0

### ISSUE THREAD

**Issue by JProgrammer** [s-panferov/awesome-typescript-loader#276]
I've been trying loader 3.0 beta.

I have noticed that it will die with the following error when a file is deleted

`Error: ENOENT: no such file or directory, open '/Users/.....'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at /Users/admj012/projects/mcc/mccManager-v2/node_modules/awesome-typescript-loader/src/instance.ts:297:52`

It appears that the callback handler calls read file an any update so it cannot find the file and throws the exception.

https://github.com/s-panferov/awesome-typescript-loader/blob/master/src/instance.ts#L297

**Comment by s-panferov** [comment]
Should be fixed in 3.0.0-beta.4
