### ISSUE TITLE
Does not update build when webpack cache enabled

### ISSUE THREAD

**Issue by Delagen** [s-panferov/awesome-typescript-loader#28]
Compiled file does not contain any changes when bundler.run repeatedly

```
cache: {},
outputFileSystem: new webpack.MemoryOutputFileSystem();
```

**Comment by Delagen** [comment]
Tested babel-loader. It works as expected.

**Comment by s-panferov** [comment]
@Delagen I'll take a look soon

**Comment by oniekrenz** [comment]
Same here. Replaced loader with ts-loader and it works.

**Comment by Delagen** [comment]
@s-panferov Seems to occurs again
