### ISSUE TITLE
childProcess.fork debug port crash

### ISSUE THREAD

**Issue by DingWeizhe** [s-panferov/awesome-typescript-loader#280]
when I lunch node with `node --debug app.ts`
will throw `Error: listen EADDRINUSE :::5858`
at `/src/checker/checker.ts:40`
`const checker: childProcess.ChildProcess`
`            = childProcess.fork(path.join(__dirname, 'runtime.js'));`

I solve this problem by `typescript/lib/tsserver.js`
`var execArgv = [];`
`{`
`  for(var _i = 0, _a = process.execArgv; _i < _a.length; _i++) {`
`    var arg = _a[_i];`
`    var match = /^--(debug|inspect)(=(\d+))?$/.exec(arg);`
`    if(match) {`
`      var currentPort = match[3] !== undefined ? +match[3] : match[1] === "debug" ? 5858 : 9229;`
`      execArgv.push("--" + match[1] + "=" + (currentPort + 1));`
`      break;`
`    }`
`  }`
`}`

sorry my english is poor! Hope you can understand!

**Comment by s-panferov** [comment]
@DingWeizhe I understand, thanks for your report.
