### ISSUE TITLE
beta version is too verbose.

### ISSUE THREAD

**Issue by Strate** [s-panferov/awesome-typescript-loader#288]
Hi! Thank you for awesome work!
I found, that beta version is more verbose thatn stable. And there is no way to disable it. It is significant when webpack used with `--json` option. Could you please add option to be silent?

**Comment by idiotWu** [comment]
Same issue here, overlapping occurs when using with [webpack-dashboard](https://github.com/FormidableLabs/webpack-dashboard):

![screenshot](https://cloud.githubusercontent.com/assets/6022672/21075144/f9bb0de8-bf4d-11e6-88e0-283f4e866a45.png)

It would be nice to have an option to disable logs like `{ quiet: true }`.
