### ISSUE TITLE
Using Handlebars with this loader

### ISSUE THREAD

**Issue by vania-pooh** [s-panferov/awesome-typescript-loader#29]
Hi, I'm using Webpack inside Gulp with two loaders: this one and [handlebars-loader](https://github.com/altano/handlebars-loader). Having the following webpack configuration...
```javascript
    webpack({
        entry: './src/main.ts',
        output: {
            path: 'dist',
            filename: 'app.js'
        },
        resolve: {
            extensions: ['', '.hbs', '.ts', '.webpack.js', '.web.js', '.js']
        },
        module: {
            loaders: [
                {
                    test: /\.hbs$/,
                    exclude: /node_modules/,
                    loader: 'handlebars-loader'
                },
                {
                    test: /\.ts$/,
                    exclude: /node_modules/,
                    loader: 'awesome-typescript-loader?compiler=ntypescript&emitRequireType=false&library=es6&module=commonjs'
                }
            ]
        },
        plugins: plugins,
        devtool: '#source-map'
    }, function (err, stats) {
        // Some error handling logic
    });
```
... I'm facing the following errors while building 100% Typescript code:
```
ERROR in
File 'path/to/src/templates/myTemplate.hbs' has unsupported extension. The only supported extensions are '.tsx', '.ts', '.d.ts'.

ERROR in path/to/src/views/myView.ts:3:19
Cannot find module '../templates/myTemplate.hbs'.
```
**Any idea how to fix this?** What I tried:
* My Handlebars templates are imported in **myView.ts** class like the following:
```javascript
import myTemplate from '../templates/myTemplate.hbs';

// And somewhere later in the code I render this template:
myTemplate(context);
```
* I installed d.ts files for all libraries except Handlebars (as I'm using handlebars loader) using **tsd** command and attached ```./typings/tsd.d.ts``` to ```main.ts```
* Tried to add definitions for each view as described on the [page](http://stackoverflow.com/questions/27316823/handlebars-templates-and-browserify-with-typescript)

**Comment by s-panferov** [comment]
@vania-pooh this is TypeScript thing, not the loader thing. 

It you want a working solution right now, you can just write:

let myTemplate = require('../templates/myTemplate.hbs');

Otherwise you need to write something like that in one of your .d.ts files:

```
declare module '../templates/myTemplate.hbs' { 
	/* describe the type here */	
}
```

Please read the [discussion](https://github.com/Microsoft/TypeScript/issues/2338) about the problem.

**Comment by vania-pooh** [comment]
@s-panferov thank you for the clarification. Let me try this approach in the evening and then close the issue.

**Comment by vania-pooh** [comment]
Finally ```require``` did the trick.

**Comment by just-boris** [comment]
I found a new solution: 

```js
import * as template from './AppLayout.hbs';
```
Initial import doesn't work because CommonJS modules doesn't have magical `default` export from module. Handlebars generates module exposed with `module.exports` and my solution is how to import that modules at all

**Comment by vania-pooh** [comment]
@just-boris how should we then use individual templates?

**Comment by just-boris** [comment]
`template` variable is the exactly a single template function.
This is equivalent of `var template = require('./AppLayout.hbs')`

**Comment by mhegazy** [comment]
If you are using TS 2.0 or later, in one of your .d.ts files add:

```ts
declare module "*.hbs" {
    const _: string;
    export default _;
}
```

or just simply:

```ts
declare module "*.hbs";
```

see https://github.com/Microsoft/TypeScript/wiki/What%27s-new-in-TypeScript#wildcard-character-in-module-names for more details.

**Comment by ksnyde** [comment]
@mhegazy any idea how would go about importing precompiled templates?
