### ISSUE TITLE
[ap-loader] callback... 

### ISSUE THREAD

**Issue by erwin16** [s-panferov/awesome-typescript-loader#291]
I am using awesome-typescript-loader w Webpack, running fine …
However I am trying to setup a production deployment process (running ships-deploy)  to my remote host (Yves.live) , and I have facing a problem you might help me to solve. On my localhost
After deploying my new release on a remote host, compiling and building w webpack, I need to restart my app with PM2
I cannot hook the pm2-restart to Webpack ending or Webpack exiting because the at-loader process is started in a separate process… and is still running when I start the pm2-start

 I should hook pm2-start to the end of this separate process…

Here is the console output

        `	@yves.live Executing pre-build scripts

	@yves.live "Webpack Start". # echo from  WebpackShellPlugin
	@yves.live 
	@yves.live [at-loader] Using typescript@2.0.10 from typescript and "tsconfig.json" from /opt/hello-angular/releases/20161206103220/tsconfig.json
	@yves.live 
	@yves.live [at-loader] Checking started in a separate process...

	   # is there a way to keep track of this process ?

	@yves.live 
	@yves.live [at-loader] Ok, 5.531 sec.
	@yves.live Executing post-build scripts
	@yves.live "Webpack End"  # echo from WebpackShellPlugin
	@yves.live Executing additional scripts before exit
	@yves.live "Webpack Exit". # echo from WebpackShellPlugin
	@yves.live Hash: 5c4be87232dc5ea6d7fa
	@yves.live Version: webpack 2.1.0-beta.27
	@yves.live Time: 70161ms
	@yves.live     Asset    Size  Chunks             Chunk Names
	@yves.live bundle.js  376 kB       0  [emitted]  app
	@yves.live     + 441 hidden modules
	...
	....  # [at-loader] output  long process ….  Still running
	5693ms asset optimization
	localhost$ # here I should restart my pm2

Any clue ?  Thanks for your feedback

**Comment by s-panferov** [comment]
@erwin16 If webpack started in non-watch mode, at-loader should act just like any normal loader and it's child process dies after everything is done.

https://github.com/s-panferov/awesome-typescript-loader/blob/master/src/instance.ts#L368

**Comment by erwin16** [comment]
OK, however my concern was with continuing the shift process after the loader dies... and I found a solution w shipit

in my shipi task which excite the webpack building process, I can add a callback function which is waiting for the complete webpack process to end. ( including the loaders) 

    shipit.blTask('webpack_build', function () {
        shipit.remote('cd '+ shipit.releasePath + ' && sh webpack_builder.sh ' + env).then(function (res) {
            console.log("WEBPACK BUILD CALLBACK FUNCTION...");
        });
    });

so I can insert at this place the PM2 restart command ....
thanks a lot for feedback
