### ISSUE TITLE
Identify errors more clearly

### ISSUE THREAD

**Issue by karptonite** [s-panferov/awesome-typescript-loader#295]
I ran into an issue trying to use non-relative paths module resolution. The error looked like:
```
ERROR in [default] /path/to/src/app/app.module.ts:13:29
Cannot find module 'app/app.component'.
```
I thought the error was from webpack, and spent a long time trying to debug. It wasn't until I switched to ts-loader, and the error changed to
```
ERROR in /path/to/src/app/app/app.module.ts
(13:29): error TS2307: Cannot find module 'app/app.component'.
```
that I realized that the error was coming from the loader (or compiler) itself, and was able to track down the issue.

Including some indication in your error message--the ts error code?--of the source of the error would really have helped.

**Comment by s-panferov** [comment]
Fixed
