### ISSUE TITLE
Build process hangs after completion

### ISSUE THREAD

**Issue by charsleysa** [s-panferov/awesome-typescript-loader#302]
I have found that the build hangs after successful completion with v3.0.0-beta.12.

Works fine if I revert to v3.0.0-beta.9.

Haven't tested with other versions.

**Comment by allenevans** [comment]
I also have the exact same issue where the build hangs after successful completion.

I reverted back to v3.0.0-beta.10 and that works. It appears to be broken from v3.0.0-beta.11 onwards.

I'm using webpack v1.14.0, and typescript 2.1.4

**Comment by calvin** [comment]
I'm also experiencing the same issue with the following setup:

```JSON
  "devDependencies": {
    "typescript": "^2.1.4",
    "webpack": "^1.14.0",
    "awesome-typescript-loader": "^3.0.0-beta.12",
    "source-map-loader": "^0.1.5"
  }
```

**Comment by s-panferov** [comment]
It hangs with `--watch`?

**Comment by charsleysa** [comment]
@s-panferov no, it hangs on a standard build. It completed the build and everything looks fine but the process never terminates.

**Comment by s-panferov** [comment]
@charsleysa which OS do you have?

**Comment by charsleysa** [comment]
@s-panferov I have Windows 10 (latest stable channel release) but this issue also occurs on Linux Docker images.

**Comment by Jontem** [comment]
I have this problem to with osx sierra, typescript@2.1.4 awesome-typescript-loader@^3.0.0-beta.12 and webpack@^2.1.0-beta.27.

I have to different bundles in the same project. One works. The other don't. Haven't figured out why yet..

**Comment by JimtotheB** [comment]
@s-panferov I'm experiencing this as well, the process just hangs after. 

```shell
webpack --progress --bail -p
webpack -p
webpack --bail
webpack
```
All produce this result.

With typescript@2.1.4, webpack@1.14.0 and awesome-typescript-loader@3.0.0-beta.9 on MacOS 10.12.1

**Comment by s-panferov** [comment]
It looks like that forked process doesn't allow a parent to die.

**Comment by s-panferov** [comment]
Fixed in awesome-typescript-loader@3.0.0-beta.13, but unfortunately, the fix requires `CheckerPlugin` to be installed. I hoped to make it optional, but it seems that it's not possible until https://github.com/webpack/webpack/issues/3460 will be resolved.

**Comment by Jontem** [comment]
Can confirm that it works now!

**Comment by Delagen** [comment]
#304
