### ISSUE TITLE
Create release on GitHub for beta. 

### ISSUE THREAD

**Issue by Jontem** [s-panferov/awesome-typescript-loader#303]
Hi!

Thanks for your work on at-loader!

I'm using the new beta 3 version and would like to get notified when new releases are available. GitHub provides an[ atom feed](https://github.com/s-panferov/awesome-typescript-loader/releases.atom) for project releases. It would help if you created a release on GitHub for every beta version like you do on npm!

**Comment by s-panferov** [comment]
@Jontem sure.
