### ISSUE TITLE
Not watching/detecting for changes

### ISSUE THREAD

**Issue by Bnaya** [s-panferov/awesome-typescript-loader#305]
webpack -w not detecting changes to .ts files

```
    "awesome-typescript-loader": "^3.0.0-beta.11",
    "clean-webpack-plugin": "^0.1.14",
    "typescript": "^2.1.4",
    "webpack": "2.1.0-beta.27"
```
checker plugin is added to my webpack plugins

The initial build is passing, webpack entering watch mode, but when editing typescript files nothing happens

**Comment by stilllife00** [comment]
@Bnaya What was the solution ? I have the same issue

**Comment by Bnaya** [comment]
I don't remember, i probably had miss-configuration :)
