### ISSUE TITLE
Dev-Server not working

### ISSUE THREAD

**Issue by John0x** [s-panferov/awesome-typescript-loader#306]
Hey, it seems like the awesome-typescript-loader is not currently working with the dev-server of webpack2.

The Console is saying that it rebuilt the files, but the outputted bundle is still the same (not changed).

Reproduce this by creating a new angular 2 project with then newest angular 2, webpack 2 and awesome-typescript-loader versions and run ``webpack-dev-server``

**Comment by martindederer** [comment]
Why did you close this issue, John0x? I believe i ran into the same issue. How did you resolve it?
