### ISSUE TITLE
`findTsImplPackage` strange issue

### ISSUE THREAD

**Issue by Delagen** [s-panferov/awesome-typescript-loader#310]
src/instance.ts
```
function findTsImplPackage(inputPath: string) {
    let pkgDir = path.dirname(inputPath);
    if (fs.readdirSync(pkgDir).find((value) => value === 'package.json')) {
        return path.join(pkgDir, 'package.json');
    } else {
        return findTsImplPackage(pkgDir);
    }
}
```

```
fs.readdirSync(pkgDir).find((value) => value === 'package.json')
```
with inputPath ".../node_modules/typescript/lib/typescript.js" returns -1 which interpreted as true with throw error
```
Error: Cannot find module '...\node_modules\typescript\lib\package.json'
```
on the next line
```
const compilerVersion = require(pkgPath).version;
```

**Comment by Delagen** [comment]
I don't understand why. But debugger when working in gulp with webpack show me the following
![2016-12-13_13-07-16](https://cloud.githubusercontent.com/assets/783335/21136099/4ed246dc-c135-11e6-93e0-b11450c578af.png)

**Comment by Delagen** [comment]
I resolved it. this is cause due multiple webpack instances in parallel gulp pipe. So I provided instance config field to separate its config. All works now.

**Comment by dbandstra** [comment]
I ran into this issue too. But I don't understand the webpack stuff (I don't deal with that part of things in the project I'm working on). Not sure if that fix is available to me.

The 'find' function is returning -1 in my setup also. I changed it to `fs.readdirSync(pkgDir).indexOf('package.json') !== -1` .

**Comment by dbandstra** [comment]
I finally found the cause of this problem. It's an old version of the npm package `collections` which has a bunch of Array.prototype shims that don't match the es6 array functions (hooray, shims). In my case the bad dependency path was `dgeni-packages` -> `q-io` -> `collections`. Upgrading to a more recent release of `dgeni-packages` solved the problem for me.

**Comment by Delagen** [comment]
Yes. I also using `dgeni-packages` ) Thanks for work

**Comment by Awk34** [comment]
Thangs, my issues was https://www.npmjs.com/package/gh-pages
