### ISSUE TITLE
Why "[at-loader] Checking xxx" checks unrelated js files?

### ISSUE THREAD

**Issue by whitetrefoil** [s-panferov/awesome-typescript-loader#314]
When working with v2 everything worked perfectly.

After upgraded to **3.0.0-beta.14**, I saw this:

```
[at-loader] Checking started in a separate process...

[at-loader] Checking finished with xxx errors

ERROR in [at-loader] some-unrelated-1.js:1:4
    ';' expected.
ERROR in [at-loader] some-unrelated-2.js:10:24
    Unreachable code detected.
......
```

All my TS files locates in `src/...` directory, and none of them imported / required those unrelated (e.g. gulp files, compiled files, e2e tests, documents) JS files.

I'm using node v7.2.1 + webpack v1.14.0

webpack config:
```js
{
  test   : /\.ts$/,
  loader : 'awesome-typescript-loader?tsconfig=tsconfig.json',
},
```

tsconfig.json:
```json
{
  "compilerOptions"               : {
    "allowJs"                       : true,
    "target"                        : "es2017",
    "lib"                           : ["es2017", "dom.iterable"],
    "module"                        : "commonjs",
    "moduleResolution"              : "node",
    "inlineSources"                 : false,
    "inlineSourceMap"               : true,
    "sourceMap"                     : false,
    "emitDecoratorMetadata"         : true,
    "experimentalDecorators"        : true,
    "removeComments"                : false,
    "noImplicitAny"                 : true,
    "suppressImplicitAnyIndexErrors": true
  },
  "awesomeTypescriptLoaderOptions": {
    "useBabel": true,
    "useCache": true
  }
}
```

P.S.2
------

I case you've read the previous P.S., it's wrong, my mistake.  Now the issue description has been rewritten with minimized unrelated information.

**Comment by s-panferov** [comment]
@whitetrefoil `atl` should work consistently with `tsc`, so it uses the same rules. Please see my comment here: https://github.com/s-panferov/awesome-typescript-loader/issues/267#issuecomment-262901221

**Comment by whitetrefoil** [comment]
Make sense if it's by design.

Previously I thought at-loader was first a loader and should refer to how
ts-loader behave instead of tsc.  I must misunderstood something ☺️

2016年12月14日 16:40，"Stanislav Panferov" <notifications@github.com>写道：

**Comment by tony** [comment]
I'm new to typescript and came here from Google. 

This stuff is really hard. I can't tell where a lot of this stuff is coming from.

I added awesome-typescript-loader, and still have no clue why adding this plugin triggered files in completely unrelated projects from showing at-loader issues. Regardless of whether it was a dependency or not, I'm still confused
