### ISSUE TITLE
Loader doesn't seem to respect `skipLibCheck`

### ISSUE THREAD

**Issue by JKillian** [s-panferov/awesome-typescript-loader#324]
I have a `"skipLibCheck": true` line in my `tsconfig.json` file which prevents some `tsc` compiler errors that show up without the line there. However, with or without `skipLibCheck`, awesome-typescript-loader seems to produce those compiler errors.

I've verified that the right `tsconfig.json` and the right version of TS are being used.

Is this a known issue? Is there any reason that a compiler option would be being passed correctly? I know this issue is pretty vague, I can try to spin up a minimal repro if you can't duplicate this bug.

**Comment by yxnino** [comment]
Same problem.

**Comment by JKillian** [comment]
I wonder if this is a TS API issue, or an issue with how the API is used? As far as I can tell, `ts-loader` also has this same issue.

**Comment by ronami** [comment]
I'm having the same problem. Happens both with `awesome-ts-loader` and `ts-loader`.

**Comment by JKillian** [comment]
I wonder what the cause of this issue is? Considering it happens both here and with `ts-loader`. Maybe a TS issue?

**Comment by JKillian** [comment]
Verified the fix works for me. Thanks @s-panferov!
