### ISSUE TITLE
 Property 'includes' does not exist on type 'any[]'.

### ISSUE THREAD

**Issue by keyiis** [s-panferov/awesome-typescript-loader#329]
typescript version:2.1.4
webpack version:2.1.0-beta.25
os:win10 x64
nodejs:v6.9.2
The error looks like can't identify es6 method,below is tsconfig:
```
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": [ "es6", "dom" ],
    "removeComments": true,
    "noImplicitAny": true,
    "suppressImplicitAnyIndexErrors": true,
    "types": [
      "node"
    ]
  },
  "exclude": [
    "node_modules",
    "backup",
    "output"
  ]
}
```
compilerOptions.target must be 'es5'.
**error**
```
ERROR in [at-loader] src\angular\app\service\print.service.ts:510:32
    Property 'entries' does not exist on type 'ObjectConstructor'.
```
![qq 20161218141913](https://cloud.githubusercontent.com/assets/7766085/21292101/9b8c42dc-c533-11e6-827c-9845ad79295d.jpg)

**Comment by rvalimaki** [comment]
AFAIK, to get includes and other ES7 goodies to work, you need to set "lib" as [ "es7", "dom" ] instead of [ "es6", "dom" ].

I'm using "es7" lib and "es6" target, and at-loader no longer displays errors.

**Comment by s-panferov** [comment]
@keyiis yes, @rvalimaki is right.

**Comment by dijonkitchen** [comment]
FYI, it's `es2016` now instead of `es7`.
