### ISSUE TITLE
Changes to separate the checker into another process causes issues with Gulp and Webpack

### ISSUE THREAD

**Issue by KJoyner** [s-panferov/awesome-typescript-loader#33]
I am using Gulp with webpack. To signal that the webpack is done, it calls the callback method. It seems that the  changes related to calling the checker in a separate process is causing webpack to call the callback method multiple times. This in turn causes the error "Error: task completion callback called too many times." 

The task looks like:

gulp.task('webpack:production', function(callback) {
  webpack(config, function(err, stats) {
    logger(err, stats);
    callback()
  })
});

**Comment by s-panferov** [comment]
Do you use `forkChecker` option? If so, you don't need to use `forkChecker` for production builds. The only use case is when you work with your code in watch mode using small iterations and you don't want to wait the checker every time you modify your code.

If you don't use it, please show me your `webpack.config.js`.

**Comment by s-panferov** [comment]
@KJoyner ping

**Comment by s-panferov** [comment]
@KJoyner fixed in v0.9.0
