### ISSUE TITLE
Loader will add all files and subfiles as dependencies altough they are not referenced

### ISSUE THREAD

**Issue by Llorx** [s-panferov/awesome-typescript-loader#330]
Simply, I have a big project with this file on it:
```js
function c() {
    var compiler = webpack({
        context: __dirname,
        entry: "./main3.ts",
        output: {
            filename: 'bundle2.js',
            path: '/'
        },
        resolve: {
            extensions: [".ts", ".tsx", ".js"]
        },
        module: {
            loaders: [
                {
                    test: /\.tsx?$/,
                    loader: "awesome-typescript-loader"
                }
            ]
        }
    });
    compiler.plugin("compile", function () {
        console.log("cmp", i++);
    });
    return compiler.watch({
        aggregateTimeout: 333
    }, (err, stats) => {
        console.log(err, stats);
    });
}
var oldc = c();
```

Having `main3.ts` with a single `console.log("asd");` line and the `tsconfig.json` file being this:
```json
{
    "compilerOptions": {
        "jsx": "react",
        "module": "commonjs",
        "sourceMap": true,
        "target": "es5"
    }
}
```
When the compile ends, the `fileDependencies` array shows all the files of my project, and when I modify one of them, the watcher fires, so is actually looking for modifications on those files.

`ts-loader` is fine with this. How can I overcome this problem with `awesome-typescript-loader`?

EDIT: The furthest I've reached is [this line](https://github.com/s-panferov/awesome-typescript-loader/blob/0f6f1276939d958b23142af61e6e6e81ad22024e/src/checker/runtime.ts#L341) which creates the damned filelist that later [this line](https://github.com/s-panferov/awesome-typescript-loader/blob/master/src/instance.ts#L368) adds to the dependencies list, but now I'm pretty lost.

**Comment by s-panferov** [comment]
Closed in favour of #364
