### ISSUE TITLE
all files are considered changed when using webpack-dev-server and only a single file is changed

### ISSUE THREAD

**Issue by mindlink** [s-panferov/awesome-typescript-loader#334]
Howdy,

Here is our scenario:

1. webpack 2 is being used with awesome typescript loader on a large typescript code base,
2. when we use webpack-dev-server incremental builds seem to be rebuilding every file i.e. not very incremental.

We have tracked this as two separate issues, only one of which appears to be an at-loader bug:
1. paths are not normalized when adding dependencies for non-isolated modules (see here: https://github.com/s-panferov/awesome-typescript-loader/blob/master/src/index.ts#L87).
    - This means that when webpack checks the modified cache, which is indexed by normalized paths, no modified time is returned and webpack considers the dependency as changed and thus needs to be rebuilt.

2. if there is a mismatch between the on-disk file name and the imported file name all dependents will be marked as requiring a rebuild
    - So if the file is named "Somefile.ts" but imported with "./SomeFile.ts" or the file is named "SomeFile.ts" and imported with "./somefile.ts" then all files will be marked as requiring a rebuild.

Obviously point 2 is the fault of the developer, but point 1 causes incremental builds to require rebuilding all files. Which essentially negates the whole concept of an incremental build.

**Comment by apalchys** [comment]
Confirm. I see the same behavior in 3.0 as @mindlink described above.

@mindlink I would recommend you to use "forceConsistentCasingInFileNames" in tsconfig.json for the issue #2
