### ISSUE TITLE
Loader doesn't work on Windows.

### ISSUE THREAD

**Issue by kkovalevskiy** [s-panferov/awesome-typescript-loader#338]
Hello!

Looks like there is a pretty major issue for windows environment: awesome-typescript-loader skips output emitted by typescript. This occured due to incorrect behavior of `isFileEmit` function in `helpers.ts`. I see the following code there
```
function isFileEmit(fileName, outputFileName, sourceFileName) {
    return sourceFileName === fileName
        && (outputFileName.substr(-3) === '.js' || outputFileName.substr(-4) === '.jsx');
}
```
In my case `fileName` is `C:\MyFolder\MyFile` while `sourceFileName` is `c:\MyFolder\MyFile`. As consequence awesome loader thinks that there was no emit for this file. Probably here should be case insensetive comparison for windows environment.

I used v3.0.0-beta.17 version

**Comment by apalchys** [comment]
@kkovalevskiy what the version of nodejs do you use? there was an issue on Windows for node 6.3 and lower. (see https://github.com/nodejs/node/issues/6624 for details). If I am not mistaken it was fixed in 6.4

**Comment by kkovalevskiy** [comment]
I'm using node v.6.2.0. Ok, I'll try to install new one and check how loader will work.

**Comment by kkovalevskiy** [comment]
I checked the latest version of node and looks like all work fine on 6.9.4. Maybe this should be added to docs (that loader is working on specific versions of nodejs on Windows)? Or maybe it's better to make it work on versions before 6.9.4 (or 6.4)?
