### ISSUE TITLE
Possibility of custom plugins

### ISSUE THREAD

**Issue by tomitrescak** [s-panferov/awesome-typescript-loader#339]
Thanks for the awesome 3.0 version, will make the start of my year a bit nicer;) I was wondering If you would consider some kind of plugin system. Often I need to pre-process my TS code before compilation (e.g. jsx-controls) and having a plugin that transpired them to pure JSX would be great. Thanks!

**Comment by tomitrescak** [comment]
If not plugins, would you please point me to the place where I can modify the input source before the typescript compilation? Thanks!!

**Comment by aindlq** [comment]
One way to do this is to create your own webpack loader and put it in the chain before typescript one.

**Comment by tomitrescak** [comment]
That is an excellent idea! Thanks!
