### ISSUE TITLE
are resolve.alias options supported?

### ISSUE THREAD

**Issue by mrmuh** [s-panferov/awesome-typescript-loader#34]
hello! 
to avoid messy relative references with many "../" parts to other classes I tried to use the alias feature of webpack but it seems to be incompatible with the loader.

so my structure looks like this
```
src/
  common/
    lib/
      util/
        constants.ts     
  ui-admin/
    app.ts
```

and my webpack config contains the following config for resolve:
```
resolve.alias:{
  common: "/src/common/lib" 
}
```
in app.ts I try to load the class Constant from constants.ts as follows:
```
import {Constants} from "common/util/constants";
```

but when compiling the files I get 
```
  [14] ./src/common/lib/util/constants.ts 629 bytes {0} [built]

ERROR in _PATH_TO_PROJECT_/src/ui-admin/app.ts:22:24
Cannot find module 'common/util/constants'.
```

is the alias function not supported at all ? our could you please provide a small example how to use it correctly in combination with typescript?! :)

Version: v0.8.0-rc.0

**Comment by s-panferov** [comment]
@mrmuh 	hello! I've just added an example for you: https://github.com/s-panferov/awesome-typescript-loader/tree/master/examples/alias

Please note, that you need to use `rewriteImports` option right which forces loader to rewrite import paths for you. Maybe we can throw this option out when something like https://github.com/Microsoft/TypeScript/issues/2338 will land.

**Comment by s-panferov** [comment]
@mrmuh 	also please note, that such rewrites disable autocomplete features in IDEs right now, because it is a non-standard way of resolving modules.

IDEs will still work when you alias the root folder of your project, e.g.:

```
module.exports = {
    resolve: {
        extensions: ['', '.ts', '.js'],
        alias: {
            src: './src'
        }
    },
    devtool: 'source-map',
    module: {
        loaders: [
            {
                test: /\.ts$/,
                loader: '../../dist/index.js?module=common'
            }
        ]
    },
    entry: {
        index: ['./index.ts']
    },
    output: {
        path: './dist',
        filename: './[name].js'
    }
};
```

```
import { Constants } from 'src/common/lib/util/constants';

console.log(Constants.Test);
```

You import is still remains absolute, but IDE works and you don't need rewriteImports anymore.

**Comment by mrmuh** [comment]
@s-panferov thank you very much for providing the sample and for pointing out the point with the IDE support; I switched to your absolute "src" approach so I can still make use of the IDE features :+1:

**Comment by raybooysen** [comment]
Hi there

I've just hit this issue, and the example no longer exists.  How can I solve this?

**Comment by s-panferov** [comment]
@raybooysen could you please describe the problem and your setup in a new issue?

**Comment by raybooysen** [comment]
I'm using the latest awesome-typescript-loader and using aliases to shorten the import paths.  My tsconfig is:

```
{
    "compilerOptions": {
        "noImplicitAny": false,
        "removeComments": false,
        "preserveConstEnums": true,
        "sourceMap": true,
        "noEmitOnError": true,
        "jsx": "react",
        "target": "es6"
    },
    "exclude": [
        "node_modules",
        "dist",
        "dev-server",
        "testHelpers"
    ],
    "files": [
        "typings/typings.d.ts"
    ]
}
```

I'm seeing the following error:
```
ERROR in ./src/app/services/connectivity.ts
Module not found: Error: Cannot resolve 'file' or 'directory' C:\source\project/lib/messaging/messaging in C:\source\projectsrc\app\services
 @ ./src/app/services/connectivity.ts 7:29-63
```

where lib is an alias in webpack.

**Comment by raybooysen** [comment]
Woops, just saw you asked for a new issue. Will do.

**Comment by ahmednuaman** [comment]
Hi @s-panferov, I have this problem. The only way to resolve it is to fallback to `require`. I think this is because the typescript code is compiled before it's then sent into webpack, so the compiler throws an error stating modules can't be found. Here's some code (worked around): https://github.com/ahmednuaman/redux-counter/blob/master/src/js/angular2/buttons.component.ts#L2

I'll have a poke about the loader and hopefully send a PR soon. Thanks again.

**Comment by raybooysen** [comment]
@s-panferov just to be complete, I no longer use aliases so I don't see this issue.  Apologies for not responding.

**Comment by gohilumesh** [comment]
I have the same problem. I am using alias in webpack and typscript always complain that it "cannot find module 'shared-ng2/checkbox'. What are my other options then using require? 
Appreciate your reply.
