### ISSUE TITLE
  Cannot find name 'ts'. - 3.0.0-beta.18

### ISSUE THREAD

**Issue by windreamlion** [s-panferov/awesome-typescript-loader#353]
ERROR in [at-loader] node_modules/awesome-typescript-loader/dist/interfaces.d.ts:4:20 
    Cannot find name 'ts'.

ERROR in [at-loader] node_modules/awesome-typescript-loader/dist/interfaces.d.ts:13:23 
    Cannot find namespace 'ts'.

ERROR in [at-loader] node_modules/awesome-typescript-loader/dist/interfaces.d.ts:26:18 
    Cannot find namespace 'ts'.

ERROR in [at-loader] node_modules/awesome-typescript-loader/dist/interfaces.d.ts:28:32 
    Cannot find namespace 'ts'.

ERROR in [at-loader] node_modules/awesome-typescript-loader/dist/paths-plugin.d.ts:31:16 
    Cannot find name 'ts'.

ERROR in [at-loader] node_modules/awesome-typescript-loader/dist/paths-plugin.d.ts:33:14 
    Cannot find namespace 'ts'.

ERROR in [at-loader] node_modules/awesome-typescript-loader/dist/paths-plugin.d.ts:37:41 
    Cannot find namespace 'ts'.

**Comment by francisco-sanchez-molina** [comment]
Hi!

Try to add 

`  "files": [
    "node_modules/typescript/lib/typescriptServices.d.ts"
  ],
in your tsconfig.json

**Comment by windreamlion** [comment]
thx!!

**Comment by hheexx** [comment]
Same problem.
Did not work for me.

**Comment by hheexx** [comment]
allowJS in tsconfig couses this after beta 13.

To fix disable allowJs or downgrade to beta13.
