### ISSUE TITLE
Cold restart  / 3.0.0-beta.18

### ISSUE THREAD

**Issue by savvaoff** [s-panferov/awesome-typescript-loader#355]
Escaping and starting webpack again leads to that issue (it seems forked process becomes "zombi"), the same for all the bundles:

![screen shot 2017-01-23 at 12 40 26 am](https://cloud.githubusercontent.com/assets/3892914/22186301/9b9f01e6-e104-11e6-8fb4-aecfc9bf4169.png)

PS.
macos/webpack2/atl3-beta.18

**Comment by s-panferov** [comment]
Should be fixed with the latest version.
