### ISSUE TITLE
How to properly configure a new location for 'tsconfig.json'?

### ISSUE THREAD

**Issue by rfgamaral** [s-panferov/awesome-typescript-loader#357]
I currently have the following structure

- app (source files)
- config (json config files)
- tests (test source files)
- tsconfig.json
- webpack.config.js

I'm trying to move the `tsconfig.json` file into the `config/typescript.json` but it's not working.

My current setup is working just fine but when I move the file and configure `awesome-typescript-loader` to use the new location, my project does not compile. I get a lot of errors of not found modules. I tried to use the `TsConfigPathsPlugin` and `baseUrl` inside `typescript.json` but I can't get it to work.

Does anyone know all the changes I have to make to get this working?

**Comment by peacatshoe** [comment]
Had the same problem, got it to work by adding it in the query of the loader. LoaderOptions plugin and TsConfigPathsPlugin don't seem to work.
Using webpack 2.2.0 & beta 19
```
rules: [
                {
                    test: /\.ts$/,
                    loader: [
                        'awesome-typescript-loader?configFileName=tsconfig.test.json'
                    ],
                    exclude: [
                        /\.(e2e)\.ts$/
                    ]
                }
]
```

**Comment by rfgamaral** [comment]
@peacatshoe That's a different problem. You're just renaming the file, not changing it's location. Which makes a big difference because of how paths are resolved. That's the issue I'm having.

By the way, the correct syntax with Webpack 2 is this:

```json
{
    test: /\.ts$/,
    loader: 'awesome-typescript-loader',
    options: {
        configFileName: 'tsconfig.test.json'
    },
    exclude: [
        /\.(e2e)\.ts$/
    ]
}
```

**Comment by peacatshoe** [comment]
You're right, I missed that part. Tried it with the config file in a different folder and it does seem to resolve the path, but then throws a bunch of errors which are a result of the tsconfig settings in the root file (= the wrong file).

You're right about the syntax, I used the LoaderOptions plugin but that didn't seem to work, the only way I got it to pick up my other config is by using the query string directly on the loader.

**Comment by s-panferov** [comment]
> I'm trying to move the tsconfig.json file into the config/typescript.json but it's not working.

@rfgamaral please describe what exactly is not working.

**Comment by jonaskello** [comment]
I noted one thing that may be interesting in this discussion. I moved from 3.0.beta14 to 3.0.2 today and I had to reset my path for `loader.options.configFileName`. In beta14 this path was relative to the root of my project, but in 3.0.2 it is relative to webpack's main `context` path. However the setting for `TsConfigPathsPlugin` is still relative to the root of the project rather than `context`. So if you try setting both to the same path it will not work.

**Comment by rfgamaral** [comment]
> I noted one thing that may be interesting in this discussion. I moved from 3.0.beta14 to 3.0.2 today and I had to reset my path for loader.options.configFileName. In beta14 this path was relative to the root of my project, but in 3.0.2 it is relative to webpack's main context path. 

Actually I think that change - that happened between beta18 and beta19 - is exactly the problem I'm trying to describe.

This is my current file structure:

```
.
│   tsconfig.json
│
├───app (same folder structure as "tests" below)
├───config
└───tests (same folder structure as "app" above)
        webpack.js
```

My Webpack configuration have the `context` set to `path.join(__dirname, '..', 'app')` and my root `tsconfig.json` file is being picked up. This is working on beta18, which I happened to be using since I started this particular project. But upgrading to beta19 (or the latest stable version), messes it all up.

I have to set the `confgiFileName` property (like @jonaskello mentioned) to: `path.join(__dirname, '..', 'tsconfig.json')`. However, this is not working as before with beta18.

I'm getting a bunch of errors on my spec files:

```
ERROR in [at-loader] ..\tests\components\Application.spec.tsx:8:1
    Cannot find name 'describe'.

ERROR in [at-loader] ..\tests\components\Application.spec.tsx:10:5
    Cannot find name 'beforeAll'.

ERROR in [at-loader] ..\tests\components\Application.spec.tsx:24:5
    Cannot find name 'describe'.

ERROR in [at-loader] ..\tests\components\Application.spec.tsx:26:9
    Cannot find name 'test'.

ERROR in [at-loader] ..\tests\components\Application.spec.tsx:27:13
    Cannot find name 'expect'.

ERROR in [at-loader] ..\tests\components\Application.spec.tsx:30:9
    Cannot find name 'test'.

ERROR in [at-loader] ..\tests\components\Application.spec.tsx:38:13
    Cannot find name 'expect'.
```

I can't be 100% sure this is the same issue I originally posted but it feels very much related. After I fix this, maybe I can move `tsconfig.json` to `config/typescript.json`, fix paths the same way I should probably fix them right now and everything should keep working-

**Comment by kemalcany** [comment]
Hi everyone.

So I have the same problem of having the tsconfig.json at a location different than the project root. 

Right now, the tsconfig file is located as below. Notice that the file is under config directory.

```
      {
        test: /\.ts$/,
        loaders: [
          'awesome-typescript-loader?{configFileName: "config/tsconfig.json"}',
        ],
        exclude: ['/\.(spec|e2e|d)\.ts$/']
      },
```

With this settings I am getting a whole bunch of error, mentioned above by @rfgamaral as well.

I believe these errors happen because inside the tscondig.json file, the excluded folders are not being resolved correctly. ie:

```
  "exclude": [
    "cordova",
    "node_modules",
    "compiled",
    "e2e/**/*.ts",
    "src/**/*.spec.ts",
    "src/server.ts",
    "src/main.browser.aot.ts",
  ],
```

These folders are still getting included in the compilation. Adding a ../ in front of the paths doesnt change anything.

I I move the tsconfig.json back to the root (and set the {configFileName: "config/tsconfig.json"}' back to {configFileName: "tsconfig.json"}' again) these errors dissappear because the exclude statements work.

Short: Can tsconfig.json live under another directory (that is not root) and work with awesome-ts??

Thanks!

**Comment by ozmoroz** [comment]
As of awesome-typescript-loader@3.1.3 and webpack@2.5.1, the setup described by @kemalcany above works exactly as expected with tsconfig.json file located in a different directory.

**Comment by rfgamaral** [comment]
I couldn't make it work myself but VS Code also has issues with a `tsconfig.json` file in a different location so I'm closing this issue.

**Comment by mrtypescript** [comment]
The source is relative to the tsconfig.json location. I just went from "./src/**/*" to "../../src/**/*"
