### ISSUE TITLE
Unexpected token { during build when updating from v3.0.0-beta.18 to v3.0.0-beta.19

### ISSUE THREAD

**Issue by kharrak** [s-panferov/awesome-typescript-loader#363]
_It's the first time I'm opening an issue and I'm sorry if it's the wrong place or time  :)._

I updated from v3.0.0-beta.18 to v3.0.0-beta.19 and during build an error popped and the build clearly stopped. I've compared the dependencies of these two versions and you can see them below.
**I've downgraded to beta.18 and now build is passing.**

I'm using typescript loader along with webpack **2.2.0** and node **6.9.1**
I can provide further details of my configuration for whom it may concern.

I've deleted node_modules, cleared npm cache and I'm getting almost the same stacktrack trace as down below:
Could not find 'lib/plugins.js' .....

**Is it because of the nodejs version?** 

**The differences are**
`awesome-typescript-loader@3.0.0-beta.19
+-- colors@1.1.2 		                             
+-- enhanced-resolve@3.1.0 		             
+-- lodash@4.17.4 		                           
+-- object-assign@4.1.1 	                    
 -- source-map-support@0.4.11 	            
 		 				                         
 |  +-- awesome-typescript-loader@3.0.0-beta.18 
 |   +-- colors@1.1.2  
 |   +-- enhanced-resolve@2.3.0 
   |    -- memory-fs@0.3.0 
  |   +-- lodash@4.17.4 	
  | +-- object-assign@4.1.1
 -- source-map-support@0.4.11`
 	 
**Original stack trace.**
 `SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (D:\Dev\src\node_modules\awesome-typescript-loader\src\entry.ts:2:18)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (D:\Dev\src\config\webpack.common.js:17:23)
    at Module._compile (module.js:409:26)`

My tsconfig looks like this
`{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "allowSyntheticDefaultImports": true,
    "sourceMap": true,
    "noEmit": false,
    "noEmitHelpers": true,
    "strictNullChecks": false,
    "skipDefaultLibCheck": true,
    "lib": [
      "dom",
      "es6"
    ],
    "typeRoots": [
      "node_modules/@types"
    ],
    "types": [
      "hammerjs",
      "jasmine",
      "node",
      "source-map",
      "uglify-js",
      "webpack"
    ]
  },
  "exclude": [
    "node_modules",
    "wwwroot/dist"
  ],
  "awesomeTypescriptLoaderOptions": {
    "forkChecker": true,
    "useWebpackText": true
  },
  "compileOnSave": false,
  "buildOnSave": false,
  "atom": {
    "rewriteTsconfig": false
  }
}
`

**Comment by s-panferov** [comment]
> Could not find 'lib/plugins.js' .....

**Comment by kharrak** [comment]
Hello,  
The log with lib/plugin.js was showing on my local machine and unfortunately the npm log vanished.
I've changed it back to beta.19 and I have a clean build on my local machine (node_modules cleaned/npm cache cleaned).

I'm using a build machine for production builds and on that one the error is still reproducing for beta.19 (the last stacktrace from above).

I think this is a **node** problem because on my build machine node version is **v4.4.3**.
Unfortunately I don't have rights to change it to 6.9.3 as on my local machine, but I can ask for an upgrade and I will come back to you as soon as I get it upgraded.

**Comment by cvillamor** [comment]
Encountered this error as well. Was working on my local version of node but not on the version of node on our ci server.
