### ISSUE TITLE
webpack-dev-server live-reload and error overlay does not work with 3.0.2 but did in 3.0.0-beta.14

### ISSUE THREAD

**Issue by jonaskello** [s-panferov/awesome-typescript-loader#365]
I upgraded today from 3.0.0-beta.14 to 3.0.2 and noticed that the [overlay feature](https://github.com/webpack/webpack-dev-server/pull/764) in webpack-dev-server stopped working. Not sure why, I'm guessing it has something to do with webpack-dev-server not being able to determine that atl fails. I'm using webpack 2.2.1 and webpack-dev-server 2.3.0. Let me know if example code to repro the issue is needed.

**Comment by jonaskello** [comment]
Another related observation is that with live-reload enabled in webpack-dev-server it will now reload even when atl fails with errors. In beta14 it would not reload but just report the errors in the console. Probably the root cause is the same as for the error overlay not working.

**Comment by s-panferov** [comment]
@jonaskello the main reason of this behavior is that error reporting is async in the 3x version. "async" means that webpack don't wait for the error to mark build VALID and make HMR. 

You can work-around this behavior by disabling `CheckerPlugin` or make the loader `silent`

**Comment by jonaskello** [comment]
Aha, that makes sense now. Thanks!
