### ISSUE TITLE
Build time regression (~x2) from beta.18 to beta.19+

### ISSUE THREAD

**Issue by artaommahe** [s-panferov/awesome-typescript-loader#366]
ubuntu 16.04, angular app, webpack 2.2.0, watch mode, source maps, initial build (without aot), 2 passes for each version

**beta.18**
Time: 182792ms
Time: 194862ms

**beta.19**
Time: 335290ms
Time: 360012ms

**3.0.3**
Time: 360059ms
Time: 349131ms

tsconfig
```json
{
  "compilerOptions": {
    "target": "es5",
    "module": "es2015",
    "declaration": false,
    "noImplicitAny": true,
    "suppressImplicitAnyIndexErrors": true,
    "removeComments": false,
    "moduleResolution": "node",
    "noLib": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "sourceMap": true,
    "noEmit": true,
    "noEmitHelpers": true,
    "noUnusedParameters": true,
    "noUnusedLocals": true,
    "skipLibCheck": true,
    "baseUrl": "./app",
    "alwaysStrict": true,
    "importHelpers": true,
    "allowSyntheticDefaultImports": true,
    "lib": [ "dom", "es6" ]
  },
  "exclude": [
    "node_modules",
    "production-bundles"
  ],
  "compileOnSave": false,
  "buildOnSave": false,
  "angularCompilerOptions": {
    "genDir": "aot",
    "skipMetadataEmit": true
  },
  "awesomeTypescriptLoaderOptions": {
    "forkChecker": true
  }
}
```
webpack
```js
        {
          test: /\.ts$/,
          enforce: 'pre',
          loader: 'tslint-loader',
          options: {
            resourcePath: CONFIG.APP_PATH,
          }
        },

        {
          test: /\.ts$/,
          use: [
            'awesome-typescript-loader',
            'angular-router-loader',
            'angular2-template-loader',
          ]
        },
```

**Comment by s-panferov** [comment]
@artaommahe is your codebase open-source? Can I see it somehow?

**Comment by artaommahe** [comment]
@s-panferov nope :(

**Comment by Aleksanderis** [comment]
I can confirm the regression, but not sure if it's same issue, because regression for me is even bigger - from ~40s to ~400s. I also tried ts-loader recently, and there are very similar symptoms.
I saw some talks about joining ts-loader and awesome-typescript-loader forces, so maybe something was merge from ts-loader?

**Comment by s-panferov** [comment]
Please provide some information about your environment: node version, typescript, OS

**Comment by Aleksanderis** [comment]
I'm kind of new to webpack, so I don't pretend that I configured everything correctly, just wanted to confirm @artaommahe findings. :) 
I had enough challenges to setup everything but with awesome-typescript-loader 2.2.x it was working quite well at the end. If I explain everything in details, you would probably say it's not awesome-typescript-loader issue. ;)

If you are still interested, then:
- Everything  is more or less recent version: Windows 10, node - v6.9.4, Typescript - 2.0.10, webpack - 2.2.1, angular 2.4.0.
- Other loaders used: angular-router-loader (with lazy loading), angular2-template-loader, source-map-loader, file-loader, css-loader, url-loader.

One big "feature" of my solution I have to mention - is that it's based on several semi-separate modules (or "feature slices"):
- There  is one main module.
- Each module can be developed separately - i.e. there is tsconfig.json and node_modules for each module (although all dependencies are dev-dependencies in packages.json).
- There is also common/shared module used in all other modules. It's npm-linked  to "node_modules".
- webpack builds everything using main module and its' tsconfig.json, all modules are used as webpack "entries".

**Comment by artaommahe** [comment]
Tried 3.0.4-rc.0 - nothing changes, same low speed.
Node 7.4.0, Typescript 2.1.5, Ubuntu 16.04

**Comment by timbru31** [comment]
We experienced extreme time regressions, like x3 times longer than before.
The upgrade took place from 3.0.0-beta11 to 3.0.3

Running TypeScript 2.1.4, Node 6 (Docker image) in our GitLab pipeline (GitLab Enterprise Edition 8.16.4), sadly no OSS project either.
Using webpack 1.14.0

Thanks for your investigation, you are always very fix in releasing updates and bug fixes, keep up the good work 👍

**Comment by chrisnicola** [comment]
Not sure if this is the cause of the issue, but I noticed in my CI environment that the checker is type checking any `.ts` file it can find including files it has found in the `vendor` folder which contains bundler packages. They are throwing type errors because they are not actually typescript files.

Interestingly adding `"exclude": ['vendor']` to the `tsconfig.json` doesn't prevent it from doing this. This may be unrelated though. It is probably worth noting that this is happening in the Karma build where the webpack config has no `entry` file values as that is handled by Karma itself. Still I would expect the checker to respect the `tsconfig` which it does not appear to be.

**Comment by s-panferov** [comment]
@chrisnicola thanks, I'll check this

**Comment by s-panferov** [comment]
Could you all please describe your folder structure? Where is `tsconfig` relative to your source files and your ignore?

**Comment by Aleksanderis** [comment]
My folder structure is as follows:

```
+---Modules
|   +---CommonUIModule
|   |   package.json
|   |   tsconfig.json
|   |
|   |   +---node_modules
|   |   |   +---@angular 
|   |   \---src
|   \---Module1
|   |   package.json
|   |   tsconfig.json
|   |
|   |   +---node_modules
|   |   |   +---@angular  
|   |   |   +---@types
|   |   |   +---@foo
|   |   |   |   \---common-ui (npm link to CommonUIModule)
|   |   |   |       +---node_modules
|   |   |   |       \---src
|   |   \---src
|   \---Module2 (same structure as above)
|   \---Module3 (same structure as above)
|   \---Module4 (same structure as above)
\---Host
    |   package.json
    |   tsconfig.json
    |   webpack.config.js
    |   
    +---node_modules
    |   +---@angular
    |   +---@types
    |   +---@foo
    |   |   \---common-ui (npm link to CommonUIModule)
    |   |       +---node_modules
    |   |       \---src
    \---src
        +---app
        +---css
        +---img
```

Internal (inside Modules) tsconfig.json files are used mainly for development. Webpack uses tsconfig.json from Host, and its' contents are:

```
{
  "compileOnSave": false,
  "buildOnSave": false,
  "compilerOptions": {
    "rootDir": "../",
    "target": "es5",
    "module": "commonjs",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "noEmitOnError": false,
    "noImplicitAny": true,
    "removeComments": false,
    "declaration": false,
    "stripInternal": true,
    "skipLibCheck": true,
    "sourceMap": false,
    "noUnusedParameters": true,
    "noUnusedLocals": true,
    "strictNullChecks": true,
    "baseUrl": "",
    "paths": {
      "@foo/common-ui": [ "node_modules/@foo/common-ui" ],
      "@angular/*": [ "node_modules/@angular/*" ],
      "rxjs/*": [ "node_modules/rxjs/*" ]
    },
    "lib": [
      "dom",
      "es6"
    ],
    "typeRoots": [
      "node_modules/@types"
    ],
    "types": [
      "node"
    ]
  },
  "awesomeTypescriptLoaderOptions": {},
  "exclude": [
    "dist",
    "node_modules",
    "bin"
  ]
}
```

**Comment by s-panferov** [comment]
Could you please also try awesome-typescript-loader@3.0.4-rc.1?

**Comment by artaommahe** [comment]
```
tsconfig.json
app/ # contains all app code
libs/ # copies of some small libs with fixes
node_modules/ 
production_bundles/ # builded for production final bundles
```
tsconfig as in first post
```json
  "exclude": [
    "node_modules",
    "production-bundles"
  ],
```

**Comment by s-panferov** [comment]
@artaommahe I see a difference "production-bundles" vs "production_bundles".

**Comment by Aleksanderis** [comment]
For me unfortunately there is no any good changes in 3.0.4-rc.1

Output building with 3.0.4-rc.1 (there is also a strange error):
```
========== USING DEVELOPMENT ==========
[at-loader] Using typescript@2.0.10 from typescript and "tsconfig.json" from c:\Projects\Smth\Host/tsconfig.json.

**420205ms** building modules
82ms sealing
1ms optimizing
1ms basic module optimization
448ms module optimization
47ms advanced module optimization
44ms basic chunk optimization
1ms chunk optimization
4ms advanced chunk optimization
5149ms building modules
1ms module and chunk tree optimization
60ms module reviving
3ms module order optimization
20ms module id optimization
12ms chunk reviving
1ms chunk order optimization
72ms chunk id optimization
142ms hashing
3ms module assets processing
602ms chunk assets processing
441ms additional chunk assets processing
3ms recording
1ms additional asset processing
1ms chunk asset optimization
 94% asset optimization
[at-loader] Checking started in a separate process...

[at-loader] Ok, 0.675 sec.
999ms asset optimization
215ms emitting
Version: webpack 2.2.1
Time: 428719ms


ERROR in ../Modules/CommonUIModule/src/index.ts
Module build failed: Error: Final loader didn't return a Buffer or String
    at c:\Projects\Smth\Host\node_modules\webpack\lib\NormalModule.js:149:64
    at c:\Projects\Smth\Host\node_modules\loader-runner\lib\LoaderRunner.js:370:3
    at iterateNormalLoaders (c:\Projects\Smth\Host/\node_modules\loader-runner\lib\LoaderRunner.js:211:10)
    at iterateNormalLoaders (c:\Projects\Smth\Host\node_modules\loader-runner\lib\LoaderRunner.js:218:10)
    at c:\Projects\Smth\Host\node_modules\loader-runner\lib\LoaderRunner.js:233:3
    at context.callback (c:\Projects\Smth\Host\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at c:\Projects\Smth\Host\node_modules\awesome-typescript-loader\src\index.ts:98:13
```

Output with 2.2.4:
```
**33931ms** building modules
56ms sealing
1ms optimizing
1ms basic module optimization
462ms module optimization
44ms advanced module optimization
41ms basic chunk optimization
1ms chunk optimization
3ms advanced chunk optimization
4609ms building modules
1ms module and chunk tree optimization
54ms module reviving
4ms module order optimization
10ms module id optimization
9ms chunk reviving
1ms chunk order optimization
65ms chunk id optimization
145ms hashing
2ms module assets processing
632ms chunk assets processing
12ms additional chunk assets processing
3ms recording
1ms additional asset processing
0ms chunk asset optimization
3061ms asset optimization
198ms emitting
Version: webpack 2.2.1
Time: 43599ms
```

So.. 43599ms vs 428719ms :(

**Comment by artaommahe** [comment]
@s-panferov my typo, they are same

**Comment by s-panferov** [comment]
Let's try to debug a little bit more. Please download `3.0.4-rc.2` and add `debug: true` to `atl` loader settings. 

With this setting, it should print all initial and compiled files. Let's check that it compiles what you expect.

**Comment by artaommahe** [comment]
@s-panferov looks like `rc.1+` solves the problem

**3.0.0-beta.18**
Time: 136618ms

**3.0.4-rc.0**
Time: 244359ms

**3.0.4-rc.1**
Time: 137504ms

**Comment by Aleksanderis** [comment]
No significant improvement with rc.2.
With debug=true - it produced 13k lines of log, which is hard to read.. Is there anything specific I should search for?

**Comment by s-panferov** [comment]
@Aleksanderis it means that TS infers a lot of files to include. Only you know what should be included, but I can suppose that your `"rootDir": "../"` setting may affect `exclude` paths. Please try to adjust the settings.

**Comment by Aleksanderis** [comment]
I will try to flatten project structure just to be sure.

However I don't see too much files from "node_modules" in debug output (in "@DEBUG Typechecked files" section), just some expected ones. Which means that it's probably not the issue with `exclude`. I also tried to remove `node_modules` from current `exclude` option, and it clearly took much more files for processing.

Also it doesn't explain why it works much better with `atl@2.2.4`. What kind of changes were introduced in 3.x version? I didn't find it in change log, so just curious - maybe it could point into right direction somehow..;)

**Comment by timbru31** [comment]
rc.2 seems to be better, but not as good as beta11 (still about 7-8 mins instead of 4-5)

**Comment by Aleksanderis** [comment]
Hmm.. I was using `typescript@2.0.10`, because update to 2.1.x was blocked by some third-party dependencies. The most interesting part is that it turned out the last package which was blocking it for me - was `awesome-typescript-loader@2.2.4`. While upgrade to `awesome-typescript-loader@3.0.x` was blocked by the fact it wasn't performing for me. ;)

So I tried to escape this loop and update both libraries at the same time - and.. it magically helped! Maybe it's not as good as it was with `atl@2.2.4` and `ts@2.0.10` (I need to monitor it for longer), but now it's at least comparable (not 450000ms).

I would say you should try it with your projects, maybe it's not my big project fault after all, but rather a kind of incompatibility issue between different `atl` and `typescript` versions (in documentation it says it supports `typescript@2.x`, which includes 2.0.10).
