### ISSUE TITLE
webpack with pug-loader cannot find pug files

### ISSUE THREAD

**Issue by AckerApple** [s-panferov/awesome-typescript-loader#380]
I was using pug-loader with ts-loader and the packages co-existed great.

I have switched to awesome-typescript-loader because it is awesome and saves time.

However, I cannot get my pug files to load.

My Error:
```
[at-loader] Checking finished with 1 errors
Error in bail mode: [at-loader] app/app.module.ts:9:39 
    TS2307: Cannot find module './templates/rjon-app-stage.pug'.
```

My ts-loader would load pugs using ANY of these two methods:
```
import * as rjonAppStageTemplate from './templates/rjon-app-stage.pug'
```
or
```
const rjonAppStageTemplate = require('./templates/rjon-app-stage.pug')
```

My tsconfig
```
{
  "compilerOptions": {
    "baseUrl": ".",
    "moduleResolution": "node",
    "module": "commonjs",
    "experimentalDecorators": true
  },
  "files": [
    "./app/index.ts"
  ]
}
```

My webpack.config (essentially looks like this):
```
{
  bail:true,
  resolve: {
    extensions: ['.pug','.jade','.ts','.js']
  },
  module:{
    loaders:[{
      test: /\.pug$/, loader: 'pug-loader'
    },{
      test: /\.ts$/,
      loader: 'awesome-typescript-loader'
      ,exclude: [
       /\.pug$/
      ]
    }]
  },
  plugins: []
}
```

I have tried:

- Adding rootDir to tsconfig
- Tried switching to pug-static-loader instead of pug-loader

**Comment by s-panferov** [comment]
`atl` behaves similar to tsc here and uses its native module resolution. Please configure your TypeScript properly. Some info can be found here: https://github.com/Microsoft/TypeScript/wiki/What%27s-new-in-TypeScript#wildcard-character-in-module-names

**Comment by AckerApple** [comment]
Easier you saying it than actually doing so. I've researched a bit left and right this morning with little success. I'm uncertain where to apply this technique you are recommending. I also understand webpack and all these loaders have me knowledge packed up in a bubble where I don't care to understand all the ins and outs of how it actually all works ... I see the benefits of atl, still cant use.

But hey, you got another issue closed.

**Comment by enoshixi** [comment]
@AckerApple There are a couple good options I use for importing non-TypeScript assets:

- You can drop a corresponding .d.ts file along side your pug file, eg:
``` TypeScript
// ./templates/rjon-app-stage.pug.d.ts
declare const value: WhateverTheTypeIs;
export default value;
```
When importing make sure you import the .pug file, not the .d.ts file.

- Or if all `*.pug` files return the same thing (I'm not familiar with pug/pug-loader, sorry) you can drop an ambient .d.ts file somewhere in your project and use a wildcard module declaration like @s-panferov  mentioned, eg:
``` TypeScript
declare module '*.pug' {
    const value: WhateverTheTypeIs;
    export default value;
}
```
Then you can import any .pug file anywhere in your project.

**Comment by AckerApple** [comment]
I more than extra appreciate the free knowledge. I will make another attempt using your instructions.

I do start by asking myself the following though : Where do I "drop" an "ambient" .d.ts file to satisfy all pug/jade files. Perhaps I drop it adjacent to my tsconfig file? I think my problem starts with I don't know how .d.ts files work. I'm merely crashing through whatever Angular2 requires of me as I "drag" myself through getting it to do what I was doing with AngularJs.

I've been asked on GITHUB, questions that make me feel I am hand holding some stranger and the answer truly is for that person to do all the research... I am learning Typescript as I go, with some bitterness. I am crashing head first, reading second.

So I do again thank you for the tips and hints. I will do my part and report success

**Comment by enoshixi** [comment]
@AckerApple You can put the .d.ts file anywhere you like; alongside your tsconfig is fine.  I personally have a folder at the root of my projects named ```typings``` where I stick these things.  Looking at your tsconfig, I believe you would have to add the .d.t.s file path to your files array also (or use a [triple-slash reference comment ](https://www.typescriptlang.org/docs/handbook/triple-slash-directives.html)in files where you want to use it).

**Comment by AckerApple** [comment]
@enoshixi, I see I'm having the same issue with JSON files.

With webpack and ts-loader, I can load JSON files with : import * as pack from "../package.json"

With atl, I cannot. But perhaps this is where I should start learning this .d.ts techinque with JSON files first before pug/jade files

**Comment by s-panferov** [comment]
@AckerApple `ts-loader` adds it's own custom resolution logic. This is not how original TypeScript works and without special declarations these file should not be visible by compiler (your IDE should confirm this)

**Comment by AckerApple** [comment]
@s-panferov, I am coming to understand this a lot more. I had assumed that the ts-loader was taking extra steps to make my life "easier".

Anyone reading this, and having similar struggles, I have gained a lot of knowledge about .d.ts files from the following link : https://www.npmjs.com/package/typings

I have still not overcome switching to awesome-type-loader but it's certainly due to the vast amount of learning I'm taking on to achieve Angular2 TS coding.

A very soulful thank those lending free helpful knowledge.

**Comment by AckerApple** [comment]
This was a great helpful article: https://hackernoon.com/import-json-into-typescript-8d465beded79#.ics7lguqj

However, even after creating a typings.d.ts in the root with my tsconfig.json file, I have come to find that the "imported" JSON file is not even actually included but instead is only output as a require reference of require('./json-file-ref.json')

ts-loader, is bundling my JSON files into the single file output.

awesome-typescript-loader, is no longer erroring exactly like typescript cli, but only a require() declaration is seen.

MY QUESTION : how can I get atl to actually include a JSON file instead of just replace with a require() statement?

**Comment by s-panferov** [comment]
Loader don't include anything, webpack does it. When webpack sees `require` statement, it resolved the required file, processes it via loaders and includes a result to a bundle.

So you need something like `file-loader` to be installed property to handle `.json` files.

**Comment by mattiLeBlanc** [comment]
Dont forget to add `"baseUrl": "./src/app/typings"` to your tsconfig.json in your `compilerOptions` to make sure webpack can also find the typings folder where your `pug.ts` or `json.ts` is located with that declared module.
Otherwise you still get errors during build or compile. (I had).
