### ISSUE TITLE
Error messages don't use relative paths?

### ISSUE THREAD

**Issue by markwpearce** [s-panferov/awesome-typescript-loader#385]
I want to run my build scripts in the integrated terminal in VS Code, so that when I get compile errors, I can click on the filename, and VS Code will open the file. This works currently as long as the outputed file name is relative (eg. ./src/app/somefile.ts) … but Awesome-Typescript-Loader outputs filenames like:
```
ERROR in [at-loader] src/app/somefile.ts
```
(i.e. without the preceding '.’) 

Is there some configuration option I can use in order to make it a relative path (that is, report filenames like: ./src/app/somefile.ts) ?

**Comment by markwpearce** [comment]
I submitted Pull Request #387 to deal with this issue

**Comment by s-panferov** [comment]
Thanks, landed into awesome-typescript-loader@3.1.0
