### ISSUE TITLE
TSC compiles but loader gives "You may need an appropriate loader to handle this file type."

### ISSUE THREAD

**Issue by QuantumInformation** [s-panferov/awesome-typescript-loader#404]
First up, I have to say that the same issue occurs with ts-loader:

I have this code: https://github.com/QuantumInformation/Density-Wars/
when running webpack there I get this:
![image](https://cloud.githubusercontent.com/assets/216566/24353300/dae6e384-12e4-11e7-8e9c-edd83c580d06.png)

https://github.com/QuantumInformation/Density-Wars/blob/master/client/Game.ts#L19

However tsc works fine:

![image](https://cloud.githubusercontent.com/assets/216566/24353340/033c1fe8-12e5-11e7-8cbc-62db7d426299.png)

**Comment by QuantumInformation** [comment]
Also raised on ts-loader to get more eyes on it https://github.com/TypeStrong/ts-loader/issues/514

**Comment by miltonhultgren** [comment]
Hi,

I just ran into this issue as well. 

The thing that fixed it for me was changing the jsx option in my tsconfig.json from "preserve" to "react".

**Comment by QuantumInformation** [comment]
Thanks, I don't have that option in my config.

**Comment by miltonhultgren** [comment]
Maybe try adding it, not sure what the default value is.

**Comment by QuantumInformation** [comment]
no luck:
![image](https://cloud.githubusercontent.com/assets/216566/24506685/39d25734-1556-11e7-95d9-de5d9a76fccb.png)

**Comment by miltonhultgren** [comment]
Try lower case R (react)? My IDE complains if I write it with upper case R

**Comment by QuantumInformation** [comment]
Same error.

**Comment by asmuelle** [comment]
I can reproduce the problem with this sample: http://www.typescriptlang.org/docs/handbook/react-&-webpack.html

**Comment by QuantumInformation** [comment]
I solved this by switching to the new rules syntax.

**Comment by cr0cK** [comment]
@QuantumInformation 

I have the same issue in a projet that mixes ES6 modules and Typescript. I'm fighting to have both in parallel. And I'm stuck on this error.

Could you paste your webpack config?

Here, my very simple config (that works on an another project)

```
    module: {
      rules: [
        // {
        //   test: /\.scss$/,
        //   use: styles.getScssLoaders(options),
        // },

        {
          test: /\.tsx?$/,
          exclude: path.resolve(__dirname, 'node_modules'),
          include: path.resolve(__dirname, 'src'),
          use: 'awesome-typescript-loader',
        },

        {
          test: /\.js$/,
          exclude: path.resolve(__dirname, 'node_modules'),
          include: path.resolve(__dirname, 'src'),
          use: 'babel-loader',
        },
      ],
    },
```

Just a simple declaration of an interface is enough to break the build.

```
ERROR in ./server.ts
Module parse failed: /home/alexis/app/server.ts The keyword 'interface' is reserved (14:0)
You may need an appropriate loader to handle this file type.
| // });
| 
| interface ITest {
|   todos: string[];
| }
```

If I remove the interface, the build successes...

**Comment by alex-sherwin** [comment]
@cr0cK 

I had a similar setup to you, i changed my loader rule to not exclude `node_modules` and set the include to `__dirname` so that it would be able to load `ts` and `tsx` files from inside `node_modules`

```
{
  test: /\.ts|\.tsx$/,
  use: 'awesome-typescript-loader',
  include: __dirname
}
```

**Comment by abbazabacto** [comment]
@alex-sherwin you are my hero of the day

**Comment by lazurey** [comment]
@asmuelle I had the same issue with the tutorial and solved by changing `test: /\.ts?$/,` in `webpack.config.js` to `test: /\.ts|\.tsx$/,`.

p.s. I also installed a local webpack (`v3.0.0`).
```javascript
{
    test: /\.ts|\.tsx$/,
    loader: "awesome-typescript-loader"
},
```

**Comment by skmexyz** [comment]
@lazurey 's solution worked for me. However, is there a reason why `test: /\.tsx?$/` does not work?

`test: /\.jsx?$/` is the solution provided by [webpack documentation](https://webpack.js.org/configuration/) (So using that as reference, `/\.tsx?$/` instead of `/\.jsx?$/` should work but does not)

**Comment by grapehunter** [comment]
@alex-sherwin 
You are my hero

**Comment by Profeten** [comment]
I solved it this way:
```
     {
        test: /\.tsx$/,
        loader: ['babel-loader', 'awesome-typescript-loader'],
      },
```

**Comment by Profeten** [comment]
This is how I solved it:
```
      {
        test: /\.tsx$/,
        loader: ['babel-loader', 'awesome-typescript-loader'],
      },
```

**Comment by orjellingsen** [comment]
@Profeten this is the solution that worked for me as well. Thanks!

**Comment by vivekkumar93** [comment]
@alex-sherwin  and @johansaldes , Thanks a lot for your posts. I was banging to the wall for about 1 day to fix this issue.
You saved my day.
