### ISSUE TITLE
Annoying "EXIT RUNTIME" in terminal

### ISSUE THREAD

**Issue by vladimir-tikhonov** [s-panferov/awesome-typescript-loader#407]
Hi, guys!

It's a very minor, but annoying issue - when running tests via `karma`,  `at-loader` adds `EXIT RUNTIME` to the terminal. Sometimes it doesn't add new line so `EXIT RUNTIME` looks like a command you've entered into a terminal (see attached screenshots).
![screenshot-1](http://pix.toile-libre.org/upload/original/1490891058.png)
![screenshot-2](http://pix.toile-libre.org/upload/original/1490950751.png)

Is there any good reason why `at-loader` should print this? Maybe it could be enabled only in debug mode or something like this?

Cheers,
Vladimir.

**Comment by s-panferov** [comment]
Removed
