### ISSUE TITLE
transpileOnly's default value is not 'true'

### ISSUE THREAD

**Issue by ElvisKang** [s-panferov/awesome-typescript-loader#409]
I have the same issue as #364 mentioned.

ATL checked my unit-tests code which were not finished yet so I couldn't run my project.

I found that assigning true to `transpileOnly` could fix it , but after reading the source code,I found its default value **isn't** **`true`** but **`undefined`** , which conflicts with  README.md

**Comment by pl3xus** [comment]
I was about to report this too.

I was searching a way to disable the tslint logs and did not try this flag since the documentation said it defaults to true anyway.

After a few hours I finally tried it.

**Comment by s-panferov** [comment]
Fixed
