### ISSUE TITLE
Loader and compiler options

### ISSUE THREAD

**Issue by Dharmoslap** [s-panferov/awesome-typescript-loader#412]
I read documentation,  but it's still not obvious. What kind of settings go to 'awesomeTypescriptLoaderOptions' to tsconfig.json? And where exactly is it possible to set `configFileName`?  I need to have 2 files with such settings, eg. tsconfig.json and tsconfig-dev.json.

**Comment by Dharmoslap** [comment]
Got it now 
```
{
        test: /\.ts(x?)$/,
        exclude: /node_modules/,
        use: [{
          loader: "awesome-typescript-loader",
          options: {
            configFileName: 'tsconfig-dev.json'
        }
      }]
```

**Comment by noce2** [comment]
@Dharmoslap , where did you find this? I found it helpful and would like to see it added to the README.md to help other people who might be having the same issue.

**Comment by Dharmoslap** [comment]
@noce2 I figured that out myself, you can open PR and update documentation.
