### ISSUE TITLE
Webpack resolve.modules not working

### ISSUE THREAD

**Issue by rdsedmundo** [s-panferov/awesome-typescript-loader#413]
Why [this](https://webpack.js.org/configuration/resolve/#resolve-modules) feature doesn't work?

I'm trying to get a module from my root folder, and getting `TS2307: Cannot find module`.

I'm using this configuration for `resolve.modules` from Webpack:

*root/webpack.config.js*
```javascript
resolve: {
  modules: [
    'node_modules',
    path.resolve(__dirname, './src'),
  ]
}
```

*root/src/components/a/test.ts*
```javascript
export default {
  a: true,
};
```

*root/src/components/.../.../something.component.ts*
```javascript
import Test from 'components/a/test'; // doesn't work
```

This type of resolution work out-of-the-box using Babel with Javascript. I'm not sure if this is a problem with this loader, or with the TypeScript compiler itself.

**Comment by ospfranco** [comment]
Any word on this issue?

**Comment by O4epegb** [comment]
It also doesn't work with regular `ts-loader` for me.

**Comment by ospfranco** [comment]
I got this working by modifying the tsconfig.json file, try to add this lines:

`"baseUrl": "./wherever_your_source_files_are",`

**Comment by mrtrandinhvn** [comment]
https://webpack.js.org/configuration/resolve/#resolve-modules
> If you want to add a directory to search in that takes precedences over node_modules/:
> 
> modules: [path.resolve(__dirname, "src"), "node_modules"]

**Comment by ospfranco** [comment]
@mrtrandinhvn I don't think this is solvable through webpack, ts compilation has its own tool chain, I had the modules resolve configured but I solved my problem by changing the tsconfig

**Comment by mrtrandinhvn** [comment]
@ospfranco I don't know anything about ts but I'm sure the webpack.config.js of @rdsedmundo  is wrong. The "node_modules" must come last in the modules array.

**Comment by rdsedmundo** [comment]
@ospfranco Thanks. It does work here too.

**Comment by ospfranco** [comment]
@rdsedmundo can we close this ticket? :)

**Comment by Khangeldy** [comment]
```
resolve: {
    modules: [
      path.resolve('./src'),
      "node_modules"
    ],
    extensions: [".js", ".json"],
  },
```
This works for me
