### ISSUE TITLE
If you specify a different tsconfig.json file, ATL doesn't catch compile errors

### ISSUE THREAD

**Issue by jimbarrett33** [s-panferov/awesome-typescript-loader#415]
ATL is not finding compile errors when specifying an alternate tsconfig.json.  This occurs for both `transpileOnly: true` or `transpileOnly: false` in the `awesomeTypescriptLoaderOptions` section of tsconfig-dev.json.  (Although setting it to false finds other errors that are not real errors.)

Reproduced by just trying to set a property value on a TypeScript class when the property doesn't even exist.

// TestProp doesn't exist
this.TestProp = "text"; 

**does not work - ATL output shows no errors** 
`use: ['awesome-typescript-loader?configFileName=tsconfig-dev.json', 'angular2-template-loader']`

**works - ATL finds the eror**
`use: ['awesome-typescript-loader', 'angular2-template-loader']`

ERROR in [at-loader] ./_src/app.component.ts:55:12
    TS2339: Property 'TestProp' does not exist on type 'AppComponent'.

**Comment by s-panferov** [comment]
Our tests show that custom config file path should work as intended. Please provide more info.
