### ISSUE TITLE
Warning: .then() only accepts functions but was passed: [object Object]

### ISSUE THREAD

**Issue by markogresak** [s-panferov/awesome-typescript-loader#42]
Reported line is: [awesome-typescript-loader/dist/index.js:276:43 => index.ts:349](https://github.com/s-panferov/awesome-typescript-loader/blob/master/src/index.ts#L349-L352). 

AFAIK it should be `.then(() => ...`, which will return `Promise.all` promise to .then chain.

**Comment by s-panferov** [comment]
@markogresak nice catch, thanks! I'll fix this asap.

**Comment by s-panferov** [comment]
@markogresak thanks again, fixed in v0.11.3

**Comment by markogresak** [comment]
Thank you for the fix.
