### ISSUE TITLE
No way to provide custom babelrc

### ISSUE THREAD

**Issue by lekhnath** [s-panferov/awesome-typescript-loader#420]
I am using following `.babelrc` configuration to enable ES6 imports in webpack config files. At project root I have `webpack` directory with this `.babelrc` file and webpack config files.
```
{
  "presets": [
    [
      "env", {
        "targets": {
          "node": "current"
        }
      }
    ]
  ]
}
```
I also have `src` directory at project root with another `.babelrc` file along with my project source code. The babelrc configuration looks something like below.

```
{
  "presets": [
    "es2015",
    "stage-2"
  ]
}
```
But I see NO way to tell the loader to use `.babelrc` from `src` instead of `webpack` directory. No matter what I do to the config it only picks the configuration defined in `.babelrc` form `webpack` directory.

**Comment by s-panferov** [comment]
Not sure that it is possible due to https://github.com/babel/babel/issues/5689
