### ISSUE TITLE
Output glitches in Powershell

### ISSUE THREAD

**Issue by etatuev** [s-panferov/awesome-typescript-loader#421]
Powershell via cmd: [screenshot](https://i.imgur.com/OgfO2fw.png)
Visual Studio Code built-in terminal(powershell based) [screenshot](https://i.imgur.com/le360pg.png)

However, working OK if trying just in cmd.

Reproduced on:
```
Windows 10 Pro
Version 1607
Build 14393.1066
```

**Comment by s-panferov** [comment]
Don't think that I can do anything with it. You can try to use `silent` option if you want.
