### ISSUE TITLE
How to use/include npm packages that don't export a module?

### ISSUE THREAD

**Issue by sheam** [s-panferov/awesome-typescript-loader#427]
An example is the bootstrap-dialog npm package (I have the bootstrap-switch and @types/bootstrap-switch packages installed). The @types does not export a module, but simply declares a namespace, and adds to the JQuery interface.
:  https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/bootstrap-switch/index.d.ts

In my app.ts I use it as such:

```
import {OtherClass} from './otherclass'

$(document).ready(()=>{ 
  let thisPage= new PageEntry ();
  thisPage.init();
}

class PageEntry {
  public init(): void {
    $('.bss').bootstrapSwitch();
    let x = new OtherClass();
   x.doSomething();
  }
}
```

But the output from webpack does not include bootstrapSwitch code. I tried adding:
`import * as BootstrapSwitch from 'bootstrap-switch';` but I obviously get an error stating that 

> node_modules/@types/bootstrap-switch/index.d.ts' is not a module.

How do I ensure that bootstrap-switch gets pulled in?

I am using bootstrap-switch as an example, but I have about 5 packages with the same problem.

**Comment by s-panferov** [comment]
just use them using `<reference type="..." />` compiler directive
