### ISSUE TITLE
doesn't emit declaration on pure declartion files

### ISSUE THREAD

**Issue by DxCx** [s-panferov/awesome-typescript-loader#428]
Hey,

I'm just switch from `ts-loader` to `awesome-typescript-loader`
and i'm seeing that files like `interfaces.ts` which basiclly have just exported interfaces does not have a generated .d.ts file.

however, if i add `export const WORKAROUND = true;` to the end of the file, then the file will have .js that needs to be emitted and the .d.ts will be emitted as well.

i'm not sure if this is a feature or a bug, but if that's a feature how do i disable it? ^_^

**Comment by s-panferov** [comment]
#432 the same
