### ISSUE TITLE
interfaces.d.ts - ts namespace has no member "CustomTransformers"

### ISSUE THREAD

**Issue by wsloth** [s-panferov/awesome-typescript-loader#430]
TypeScript version: ~2.3.0
at-loader version: Latest 3.1.3

When building I get the following error:

```
Error in bail mode: [at-loader] ./node_modules/awesome-typescript-loader/dist/interfaces.d.ts:25:34
    TS2694: Namespace 'ts' has no exported member 'CustomTransformers'.
```

Indeed when looking at the interfaces.d.ts file in the dist directory in VSCode it has a red squiggly that CustomTransformers does not exist.

I was running TS2.2 before, and upgraded to the same version as this repository in hope it would be fixed. In the TypeScript source code I could find ample references to CustomTransformers, making it seem it's a WIP feature.

Could this be documented and/or fixed?

**Comment by fugalfunkster** [comment]
I had the same issue when at-loader moved to 3.1.3. Since bumping to typescript: 2.3.0, I'm not seeing the error from the compiler or in my editor (emacs, tide).

**Comment by wsloth** [comment]
It seems this problem is somehow fixed by updating TypeScript. My problem was that the local version of TypeScript was 2.3.x, but my global version was still outdated. Try updating both and `npm cache clean`-ing and eventually it should work.
