### ISSUE TITLE
newLine not honored?

### ISSUE THREAD

**Issue by diggyk** [s-panferov/awesome-typescript-loader#431]
I'm using awesome-typescript-loader 3.0.8 with the following tsconfig:

> {
  "compilerOptions": {
    "alwaysStrict": true,
    "declaration": true,
    "jsx": "react",
    "moduleResolution": "node",
    "newLine": "LF",
    "noImplicitAny": true,
    "noImplicitThis": true,
    "pretty": true,
    "sourceMap": true,
    "strictNullChecks": true,
    "target": "es6"
  },
  "exclude": ["node_modules"]
}

But when I go to git add the declaration files, I get the warning:

> warning: CRLF will be replaced by LF in routes.d.ts.

I thought the newLine should instruct to use LF instead of CRLF.  Is this happening at a different part of the stack?

**Comment by s-panferov** [comment]
Don't think that it's something specific to the loader.
