### ISSUE TITLE
Question: Ignore errors in development webpack

### ISSUE THREAD

**Issue by amilajack** [s-panferov/awesome-typescript-loader#434]
When running webpack in the development environment, I get a bunch of typescript errors and because of this, the webpack dev server never starts. Is there a way to show typescript errors but still have webpack/webpack dev server still run?

**Comment by s-panferov** [comment]
As far as I know, dev server should work with typescript errors. Please check your configuration, maybe you have something like https://github.com/webpack/docs/wiki/list-of-plugins#noerrorsplugin installed.
