### ISSUE TITLE
Webpack 2 hot loading

### ISSUE THREAD

**Issue by Dharmoslap** [s-panferov/awesome-typescript-loader#436]
Please create docs for usage with Webpack 2 hot loading. https://webpack.js.org/guides/hmr-react/#webpack-configuration

**Comment by rapilabs** [comment]
Link seems to be changed to https://webpack.js.org/guides/hot-module-replacement/

**Comment by jasperjn** [comment]
I'm searching for HMR implements with typescript. But most of all are talking about react framework.
Is there a document or examples using this loader with webpack2 HMR without react? Thanks.

**Comment by s-panferov** [comment]
You don't have to do anything special to the loader to make hot-loading work, as far as I know.
