### ISSUE TITLE
Can't import from node modules

### ISSUE THREAD

**Issue by QuantumInformation** [s-panferov/awesome-typescript-loader#444]
The code

![image](https://user-images.githubusercontent.com/216566/27182796-633eda60-51d4-11e7-82b5-bc542075b5ea.png)

The error

![image](https://user-images.githubusercontent.com/216566/27182776-5694c20c-51d4-11e7-9912-e096c49f012e.png)

Example:
https://github.com/quantumjs/solar-popup/blob/master/src/SolarPopup.ts#L2

I've been able to import with ts-loader

**Comment by giniedp** [comment]
to your tsconfig.json add
```
"moduleResolution": "node"
```

**Comment by QuantumInformation** [comment]
Great thx
