### ISSUE TITLE
getCustomTransformers are not being used when running with dev server

### ISSUE THREAD

**Issue by Igorbek** [s-panferov/awesome-typescript-loader#447]
I'm using `options.getCustomTransformers` to supply custom transformations to the TypeScript emitter.
It looks like they only work when webpack creates static bundles.
The method doesn't get called at all, when dev-server is running with HMR.
Is anything can be done in order to support customer transformers in that mode?

**Comment by s-panferov** [comment]
In "watch" mode our type-checking happens in another process and we need to find some way to pass transformers to that process.

**Comment by Igorbek** [comment]
Do you use emit api in that mode? Is that where the transpiling in the watch mode happening: https://github.com/s-panferov/awesome-typescript-loader/blob/master/src/checker/runtime.ts#L385 ?

**Comment by Igorbek** [comment]
If so, looks like `ts.transpileModule` is pretty simple (https://github.com/Microsoft/TypeScript/blob/master/src/services/transpile.ts#L26-L112) and creates a compiler host internally. So that it would be a good optimization to do this work manually.

Other option, which obviously is easier, is to pass `transformers?: CustomTransformers` as part of `transpileOptions`.

**Comment by guncha** [comment]
I really needed this to work so I made the necessary changes. Basically what you suggested, @Igorbek. @s-panferov if you're interested, I'm happy to write specs, document and open a proper PR.

https://github.com/s-panferov/awesome-typescript-loader/compare/master...guncha:fix-custom-transformers

**Comment by Igorbek** [comment]
That's great @guncha. That would be great if you open a PR. I have a suggestion though, that I raised here https://github.com/s-panferov/awesome-typescript-loader/pull/423#issuecomment-312401233, but it can be discussed later in your PR.
