### ISSUE TITLE
Set transpileOnly to true for specific directories (e.g. tests)

### ISSUE THREAD

**Issue by craigcartmell** [s-panferov/awesome-typescript-loader#451]
Hey,

I'd like to turn off type checking in my `src/__tests__` essentially, but still have at-loader transpile.

Is this possible?

Reason being I'm mocking in my tests which is causing ` TS2341: Property 'foo' is private and only accessible within class 'default'. ` all over the place.

This then stops my webpack build from compiling.

Thanks,

Craig

**Comment by s-panferov** [comment]
You can use `reportFiles` option to disable type-checking for some regions of your codebase.
