### ISSUE TITLE
at-loader should log to STDERR, not STDOUT

### ISSUE THREAD

**Issue by jrop** [s-panferov/awesome-typescript-loader#461]
First of all, thank you so much for an amazing WebPack loader!  I have come to rely on it in many of my projects.

From what I can tell, logs are made to STDOUT in these places:

* [runtime.ts#28](https://github.com/s-panferov/awesome-typescript-loader/blob/60ffa3c6329634c1a52f220058f64259d9b65943/src/checker/runtime.ts#L28)
* [runtime.ts#29](https://github.com/s-panferov/awesome-typescript-loader/blob/60ffa3c6329634c1a52f220058f64259d9b65943/src/checker/runtime.ts#L29)
* [runtime.ts#37](https://github.com/s-panferov/awesome-typescript-loader/blob/60ffa3c6329634c1a52f220058f64259d9b65943/src/checker/runtime.ts#L37)
* [instance.ts#117](https://github.com/s-panferov/awesome-typescript-loader/blob/589683f7fd9f47c76ddaeed1739ea6a8fc03c516/src/instance.ts#L117)
* [instance.ts#444](https://github.com/s-panferov/awesome-typescript-loader/blob/589683f7fd9f47c76ddaeed1739ea6a8fc03c516/src/instance.ts#L444)
* [instance.ts#470](https://github.com/s-panferov/awesome-typescript-loader/blob/589683f7fd9f47c76ddaeed1739ea6a8fc03c516/src/instance.ts#L470)

This is bad because in the case when I want JSON webpack output (`webpack --json > stats.json`), the outputted file will contain log-lines from at-loader:

For example: **stats.json**:
```json

[at-loader] Using typescript@2.4.1 from typescript and "tsconfig.json" from /Users/jrapodac/Code/gillette/web-team/node/famweb/src/public/js/tsconfig.json.


[at-loader] Checking started in a separate process...

[at-loader] Ok, 0.701 sec.
{
  "errors": [],
  "warnings": [],
  "version": "3.1.0",
  "hash": "a6062a75e3771e641063",
  "time": 7721,
  "publicPath": "/js/"
}
```

Ideally, these logs would get routed to STDERR, and this issue would not occur.

**Comment by jrop** [comment]
Afterthought, I suppose that I could use `{silent: true}`, but I would like to keep the error reporting, while being able to pipe webpack --json output to a valid file.

**Comment by gitowiec** [comment]
What exact part of webpack.config.js I can put `{silent:true}` to make at-loader mute? 
I am using Webpack 3.9.

**Comment by jrop** [comment]
@gitowiec See loader options: https://webpack.js.org/concepts/loaders/#configuration

**Comment by s-panferov** [comment]
Yesterday the new version with `webpack-log` was released, does it solve your problem?

**Comment by ypresto** [comment]
I'm using `awesome-typescript-loader@5.2.1` and this issue still exists. Please reopen :pray:.
`webpack-log` depends on [`loglevelnext`](https://github.com/webpack-contrib/webpack-log/blob/bce413869ac52c2d9d9b4f39d39a43486eeb4feb/src/index.js#L11) and it seems to call `console.log()` ... `console.error()` methods.

Note that in Node.js, only `console.warn()` and `console.error()` are written to STDERR.

```
$ node -e '"log,debug,info,warn,error".split(",").forEach(level => console[level](level))' > /dev/null
warn
error
```
