### ISSUE TITLE
Referenced file is undefined when using this loader

### ISSUE THREAD

**Issue by QuantumInformation** [s-panferov/awesome-typescript-loader#48]
I have a class doing this referencing a file:

https://github.com/QuantumInformation/Density-Wars/blob/master/lib/game.ts#L2

however the class Core it is undefined here: https://github.com/QuantumInformation/Density-Wars/blob/master/lib/game.ts#L96

any ideas?

**Comment by s-panferov** [comment]
@QuantumInformation sorry for the delay, I'll try to check.

**Comment by QuantumInformation** [comment]
Many thanks.

**Comment by QuantumInformation** [comment]
Any luck with the investigation @s-panferov I've not had much luck:

**Comment by s-panferov** [comment]
Should be fixed in recent versions.

**Comment by QuantumInformation** [comment]
thanks! great work on this repo!
