### ISSUE TITLE
After upgrading to version 3.2.x, TS2307: Cannot find module, declared in *.d.ts

### ISSUE THREAD

**Issue by kukjevov** [s-panferov/awesome-typescript-loader#481]
I am reopening issue https://github.com/s-panferov/awesome-typescript-loader/issues/468 because it still exists and latest version 3.2.2 does not solve it.

With "awesome-typescript-loader": "~3.1.3" everything is working nicely. After upgrading to version 3.2.x i got following error:

    ERROR in [at-loader] ./app/components/navigation/navigation.component.ts:11:25
    TS2307: Cannot find module 'config/global'.

in this repository https://github.com/kukjevov/ng-universal-demo/tree/mine you can see code.

You will not be able to install it, because of some proprietary packages, but you can see code.

Problem is not during normal build, but only during tests running using karma.

here is d.ts https://github.com/kukjevov/ng-universal-demo/blob/mine/config/global.d.ts
here is karma configuration https://github.com/kukjevov/ng-universal-demo/blob/mine/karma.conf.js
here is import (one of many) that fails after upgrade https://github.com/kukjevov/ng-universal-demo/blob/mine/app/components/navigation/navigation.component.ts

I can update repository so you will be able to install it if needed.

**Comment by paulbonner** [comment]
I can't guarantee that it's related, but I resolved an AOT compilation issue (Can't find ngFactory) in my project by (1) changing the version specification for enhanced-resolve in awesome-typescript-loader's package.json from "3.3.0" to "^3.4.1", (2) uninstalling enhanced-resolve v 3.30, and (3) running npm install on my project.

enhanced-resolve v 3.3.0 was supposed to fix the issue I was seeing, but apparently didn't, and it was still broken in 3.4.0.

**Comment by kukjevov** [comment]
Closing this because #468 was reopened
