### ISSUE TITLE
Exclude file from checker

### ISSUE THREAD

**Issue by alex88** [s-panferov/awesome-typescript-loader#482]
I have a project that runs AOT in production and JIT in development, as any other AOT project my `main.aot.ts` file reads the main module factory using
```
import { AppModuleNgFactory } from '../aot/src/app/app.module.ngfactory';
```
this however generates an error during development, even if my aot file is included only in production build (I don't see it in development's webpack module tree) the checker plugin still tries to compile it throwing the error as the factory doesn't exists because I'm in development mode.

Is there a way to tell the checker to exclude a file?

**Comment by s-panferov** [comment]
ATL behaves exactly like TypeScript would. So you can try just to use `exclude` in your `tsconfog.json`

**Comment by alex88** [comment]
Ok thank you @s-panferov, I'll do a separate config then, unfortunately trying to use a different tsconfig was throwing errors but that's not related with atl
