### ISSUE TITLE
How to build a project webpack with namespaces?

### ISSUE THREAD

**Issue by acopalipsis** [s-panferov/awesome-typescript-loader#488]
**Batman.ts**

```
namespace hero {
    export class Batman {}
}
```

**Superman.ts**

```
namespace hero {
    export class Superman {}
}
```

**hero.ts**

```
export const Batman = hero.Batman;
export const Superman = hero.Superman;
```

webpack compile 

```
... webpack helpers

/* 0 */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
Object.defineProperty(__webpack_exports__, "__esModule", { value: true });
const Batman = hero.Batman;
/* harmony export (immutable) */ __webpack_exports__["Batman"] = Batman;

const Superman = hero.Superman;
/* harmony export (immutable) */ __webpack_exports__["Superman"] = Superman;



/***/ })
/******/ ]);
});
```

If you remove the namespaces, then the project compiles as expected. But with namespaces is compiled only hero.ts. What's the matter?

I need the Declaration of the wrapped contents into namespaces. And important condition is to collect project webpack.

**Comment by s-panferov** [comment]
@acopalipsis this loader doesn't resolve namespace references (`ts-loader` doesn't do it also). The only this you can do is to have an `index.ts` file where you require all the other files you have. Maybe [this](https://webpack.github.io/docs/context.html) can help you.
