### ISSUE TITLE
at-errors 

### ISSUE THREAD

**Issue by trsh** [s-panferov/awesome-typescript-loader#514]
Even if I specify
`"reportFiles": [
      "./app/**/*.{ts,tsx}"
    ]`

I still get errors from node_modules/ packages that I'm importing. Is this expected behavior? Can we have some advanced setting, that ignores reporting some paths even from includes? It's a common problem, because I can do relay on my code, but not on 3rd party :/

**Comment by s-panferov** [comment]
where do you specify this?

**Comment by trsh** [comment]
@s-panferov by bad. I was using older version of atl that didn't support reportFiles.
