### ISSUE TITLE
Trouble getting useBabel to work correctly (Babel 7)...

### ISSUE THREAD

**Issue by tracker1** [s-panferov/awesome-typescript-loader#522]
I'm using ES2015/typescript module syntax throughout my application...

My configuration is as follows...

```js
const babelOptions = {
  presets: [
    [
      '@babel/preset-env',
      {
        loose: true,
        targets: {
          browsers: ['chrome >= 61'],
        },
        modules: false,
      },
    ],
  ],
  plugins: [
    'syntax-dynamic-import',
    'syntax-object-rest-spread',
    'syntax-pipeline-operator',
    'syntax-optional-chaining',
    'transform-class-properties',
    'transform-object-rest-spread',
    'transform-optional-chaining',
    'transform-pipeline-operator',
  ],
};
...          
            {
              loader: 'awesome-typescript-loader',
              options: {
                configFileName: 'tsconfig.json',
                useBabel: true,
                babelCore: '@babel/core',
                babelOptions,
              },
            }
```

My output seems to be in an incorrect order... the error is *"Uncaught TypeError: Cannot read property 'default' of undefined"*

The outputted code in question is...

```js
exports.__esModule = true;
exports.getStore = _store.default; // <<<< ERROR HERE <<<<<<
exports.State = _state.default;
exports.default = exports.Action = exports.save = exports.load = exports.check = void 0;

var _stateSerializer = _interopRequireDefault(__webpack_require__(56));

var _stateCheck = _interopRequireDefault(__webpack_require__(86));

var _store = _interopRequireDefault(__webpack_require__(202));

var _state = _interopRequireDefault(__webpack_require__(252));

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }
```

I believe the error is it's trying to use _store, which is undefined, before the _interopRequireDefault below.  I'm uncertain as to the underlying wiring between typescript and babel via this plugin... I will try to create a trivial application as an example later, so it can be used to demonstrate the behavior... I need babel 7, as one of the new syntax plugins I want to use seems to require it.

**Comment by phil-lgr** [comment]
hi, I'm stumbling on a similar issue, have u ever found a solution?

**Comment by tracker1** [comment]
@phil-lgr IIRC, the issue was a bug in the version of Babel I was using (beta/pre-release) ... a release a few days later corrected the issue.
