### ISSUE TITLE
Incompatible to Typescript 1.6+

### ISSUE THREAD

**Issue by EliotVU** [s-panferov/awesome-typescript-loader#53]
Any plans on supporting the latest Typescript 1.6 and up? Currently the loader cannot find the helpers due a path change, however fixing that myself only leads to further problems with the API such as ".text is undefined", or is this a problem on my end?

**Comment by s-panferov** [comment]
@EliotVU Could you please provide your package.json and webpack.config.js? My team uses this loader with latest nightly build of typescript and I'm sure that there is no problem with the loader.

**Comment by EliotVU** [comment]
Nothing out of the ordinary in my config, regardless, this is no longer a problem when I switched to defaude's fork of this plugin.

**Comment by s-panferov** [comment]
@EliotVU the problem must gone in v0.14.0
