### ISSUE TITLE
moduleResolution "node" error

### ISSUE THREAD

**Issue by Coderah** [s-panferov/awesome-typescript-loader#56]
setting 
```
{
    "compilerOptions": {
        "target": "ES6",
        "experimentalDecorators": true,
        "moduleResolution": "node"
    }
}
```
in tsconfig.json will result in the following error
```
Module build failed: TypeError: Cannot read property 'resolvedModule' of undefined
    at Host.resolveModuleNames (/node_modules/awesome-typescript-loader/dist/host.js:72:27)
```

I believe this is due to https://github.com/Microsoft/TypeScript/wiki/API-Breaking-Changes#compilerhost-interface-change-comparing-to-typescript-16-beta

**Comment by s-panferov** [comment]
@Coderah which version of loader and TypeScript are you using?

**Comment by Coderah** [comment]
running the latest loader 0.14.0 and latest stable typescript 1.6.2

**Comment by s-panferov** [comment]
@Coderah it's strange, because I've tested the loader with 1.6.2 version. I'll take a look again. Thanks for your report!

**Comment by Coderah** [comment]
Everything seems to work great with the defaults, to be clear I think its the moduleResolution = "node" that is tripping things up :) thanks, let me know if I can provide anymore info!

**Comment by Iorg** [comment]
@s-panferov, Hi!

I got the same error as @Coderah.

Probably I'm doing something wrong, but with previous version of TS (1.5) everything worked perfect. Could you share your tsconfig.json and webpack.config.js where loader@0.14.0 and typescript@1.6.2 works correctly?

Thanks!
