### ISSUE TITLE
Manually triggering compiler#run does not build TS files correctly

### ISSUE THREAD

**Issue by Merott** [s-panferov/awesome-typescript-loader#57]
I'm trying to create a Webpack workflow, where I don't use Webpack's built-in watch mechanism, and I would like to manually trigger the compilation process from a different watcher.

On the first trigger of the watch, I am creating an instance of the Webpack compiler, following the [node.js api](http://webpack.github.io/docs/node.js-api.html), then calling `run()`. Thereafter, and on subsequent triggers, I simply call the `run()` method again. Pretty much like this:

```js
var webpackCompiler;

gulp.task('webpack', function() {
  webpackCompiler = webpackCompiler || webpack({ /* webpack config */ });

  webpackCompiler.run(function(error, stats) {
    // handle results
  });
});
```

The `ts > js` output is done correctly on the first compilation, but subsequent compilations don't touch the outputted `.js`. Interestingly, Webpack's output indicate that the changed file has been rebuilt.

First time run:

    [webpack] Hash: 22d95a4baadbfa5ef83e
    Version: webpack 1.12.2
    Time: 2116ms
    Asset       Size  Chunks             Chunk Names
    geminga.js    1.09 MB       0  [emitted]  main
    geminga.js.map    1.27 MB       0  [emitted]  main
    index.html  193 bytes          [emitted]
    chunk    {0} geminga.js, geminga.js.map (main) 1.06 MB [rendered]
        [0] ./src/geminga.ts 176 bytes {0} [built]
        [1] ./~/angular/index.js 48 bytes {0} [built]
        [2] ./~/angular/angular.js 1.06 MB {0} [built]
        [3] ./src/components/dashboard/dashboard.ts 389 bytes {0} [built]
        [4] ./src/components/dashboard/dashboard.controller.ts 484 bytes {0} [built]
        [5] ./src/components/dashboard/dashboard.tpl.html 205 bytes {0} [built]

Subsequent runs, following watch trigger:

    Hash: 22d95a4baadbfa5ef83e
    Version: webpack 1.12.2
    Time: 9ms
             Asset       Size  Chunks             Chunk Names
        geminga.js    1.09 MB       0             main
    geminga.js.map    1.27 MB       0             main
        index.html  193 bytes          [emitted]  
    chunk    {0} geminga.js, geminga.js.map (main) 1.06 MB
        [0] ./src/geminga.ts 176 bytes {0}
        [1] ./~/angular/index.js 48 bytes {0}
        [2] ./~/angular/angular.js 1.06 MB {0}
        [3] ./src/components/dashboard/dashboard.ts 389 bytes {0} [built]
        [4] ./src/components/dashboard/dashboard.controller.ts 484 bytes {0}
        [5] ./src/components/dashboard/dashboard.tpl.html 205 bytes {0}

Notice the `[built]` tag after `dashboard.ts`, which is the file that was changed.

Initially I thought I was doing something wrong with the compiler (maybe I still am), but I've also tested changing a different type of file (e.g. `.html`) registered with a different loader, and that worked fine.

Is there some sort of cache that is causing this?

**Comment by merott-movahedi-cko** [comment]
No such issue with `ts-loader`, switching for now.

**Comment by Merott** [comment]
No such issue with ts-loader, switching for now.

**Comment by s-panferov** [comment]
Should be fixed in recent versions.
