### ISSUE TITLE
Where is my bundle.js ?

### ISSUE THREAD

**Issue by ismailbayram** [s-panferov/awesome-typescript-loader#575]
I installed ATL and configured like below : 
my webpack.config.js
```const HtmlWebPackPlugin = require('html-webpack-plugin');

module.exports = {
  entry: './src/index.tsx',
  output: {
    filename: 'bundle.js',
    path: __dirname + '/dist'
  },
  devtool: 'source-map',
  resolve: {
    extensions: ['.ts', '.tsx', '.js', '.json']
  },
  module: {
    rules: [
      {
        test: /\.tsx?$/,
        loader: 'awesome-typescript-loader'
      },
      {
        enforce: 'pre',
        test: /\.js$/,
        loader: 'source-map-loader'
      }
    ]
  },
  plugins: [
    new HtmlWebPackPlugin({
      template: './public/index.html',
      filename: './index.html'
    })
  ]
};
```

when i executed 'yarn start', dist/ directory is empty. But when build command started, bundle.js occured in dist directory

**Comment by raybooysen** [comment]
Does yarn start start the dev server? If so, this is correct behaviour as everything is served out of memory.

**Comment by ismailbayram** [comment]
@raybooysen Yes it does. Out of the memory ? So where is the dist files

**Comment by raybooysen** [comment]
In memory.

**Comment by loyd-cpi** [comment]
Just a question, I only `buildServer` and not the server. How am I gonna include the bundle file on my HTML? Thanks.

**Comment by ismailbayram** [comment]
@loyd-cpi use html-webpack-plugin.
