### ISSUE TITLE
5.1 Error - Cannot find module 'webpack-log' at run time

### ISSUE THREAD

**Issue by djh-od** [s-panferov/awesome-typescript-loader#592]
With the 5.1.0 release, the following error is occurring when trying to run the loader: 

```
Module build failed: Error: Cannot find module 'webpack-log'
    at Function.Module._resolveFilename (module.js:555:15)
```

It looks like `webpack-log` should have been added as a dependency instead of a dev-dependency.

**Comment by astorije** [comment]
Woops, [sorry everyone](https://github.com/s-panferov/awesome-typescript-loader/pull/568/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R73) 😕

<img src="https://media.giphy.com/media/Ob7p7lDT99cd2/giphy.gif" alt="shame">
