### ISSUE TITLE
typescript 3 support

### ISSUE THREAD

**Issue by zerkms** [s-panferov/awesome-typescript-loader#602]
TS v3.0 was released tonight https://blogs.msdn.microsoft.com/typescript/2018/07/30/announcing-typescript-3-0/

This issue is to track the `awesome-typescript-loader` compatibility with it.

**Comment by qtiki** [comment]
We're using TypeScript 3.0.1 with the `awesome-typescript-loader`. So far the only issue I've noticed is that the `peerDependency` in the package is listed as `^2.7` which gives the following warning with `yarn`:

**Comment by nomcopter** [comment]
What about build mode?

**Comment by sarink** [comment]
Despite the warning, I've been using this with TS 3 for a couple of weeks and everything seems fine. Is there anything that needs to be done other than changing the `peerDependency` version in `package.json`?
