### ISSUE TITLE
Suppress some diagnostics

### ISSUE THREAD

**Issue by just-boris** [s-panferov/awesome-typescript-loader#61]
I get the following output at the end of webpack build
```
ERROR in [default]
File 'src/layouts/application/AppLayout.hbs' has unsupported extension. The only supported extensions are '.ts', '.tsx', '.d.ts'.

ERROR in [default] src/app.ts:2:22
Cannot find module './layouts/application/AppLayout.ts'.

ERROR in [default] src/index.ts:3:16
Cannot find module './app.ts'.

ERROR in [default] src/layouts/application/AppLayout.ts:4:26
Cannot find module './AppLayout.hbs'.

```
All files actually have been successfully imported by webpack, but during typescript compilation it doesn't know about it and report errors.

Now it always written in console output and distracts from real errors. It would be nice to have ability to disable errors by its code.

These errors has following codes
[TS2307 - Cannot find module](https://github.com/Microsoft/TypeScript/blob/99d448a1672490a1924adbb377cae2363b28fe33/src/compiler/diagnosticMessages.json#L831)
[TS6054 -File has unsupported extension.](https://github.com/Microsoft/TypeScript/blob/99d448a1672490a1924adbb377cae2363b28fe33/src/compiler/diagnosticMessages.json#L2228)

**Comment by just-boris** [comment]
Also, found that breaks ExtractTextPlugin.
It refuses to extract content if it has erorrs. See [this commit](https://github.com/webpack/extract-text-webpack-plugin/commit/336faab8050e00bc7b4a857774e4f7bb30de72c8).

Because errors from comment above is not actually an error, it should not be reported to webpack and break other plugins

**Comment by s-panferov** [comment]
I believe that now it can be achieved by `allowNonTsExtensions` tsconfig option.
