### ISSUE TITLE
Slowdown with typescript@3.4.2

### ISSUE THREAD

**Issue by mattkrick** [s-panferov/awesome-typescript-loader#633]
Using typescript@3.4.1 works great. Initial build of ~20 seconds.

Using it with anything above (tested up through 3.5.0-dev.20190507) results in a much slower build of ~4 minutes.

Diff is here: https://github.com/microsoft/TypeScript/compare/v3.4.1...v3.4.2
The diff looks harmless, but I must be missing something :confused: 
The slowdown does not occur when running `tsc`
The slowdown _does_ occur when using it via atl.

atl config:
```
useCache: true,
forceIsolatedModules: true,
errorsAsWarnings: true
        
```

**Comment by MikeMitterer** [comment]
Same problem here with TS 3.4.5
My sample takes ~3000ms to build

With: 
ts-loader: ~750ms
babel-loader: ~400ms
babel-loader + ts-loader: ~1000ms

So - really a huge difference

**Comment by mattkrick** [comment]
Looks like ts folks admitted to a regression in 3.4.5, they'll be fixing it in 3.5.
Root cause of mine was a mismatch between a package's github tarball & the tarball in the package.json `resolutions` (why that caused a slowdown i have no idea...)

Closing as ts@3.5rc should fix it
