### ISSUE TITLE
Hot Module Reload

### ISSUE THREAD

**Issue by hydrotik** [s-panferov/awesome-typescript-loader#70]
Does this support HMR with internal modules? (Assuming what I am describing is considered an internal module)

For example (I can include more specifics if this is unclear)
```./app.tsx``` is importing a module from ```./components/App/App.tsx```
When I edit App.tsx or _App.scss which is being imported into App.tsx, should I be seeing a reload for that module or styles in that sass file?

According to the README internal modules aren't supported and wanted to understand what that means.

Thanks! been trying to get this working with ts-loader and thought I'd see what else is out there:)

**Comment by s-panferov** [comment]
Hello @hydrotik. "Internal modules" has specific meaning inside TypeScript, see [here](http://www.typescriptlang.org/Handbook#modules-splitting-across-files). 

Your case is supported, of course. Feel free to reopen, if you have any other questions.

**Comment by hydrotik** [comment]
Wasn't able to reopen so I created another issue here with the info:

https://github.com/s-panferov/awesome-typescript-loader/issues/71
