### ISSUE TITLE
tsx is not supported

### ISSUE THREAD

**Issue by kraf** [s-panferov/awesome-typescript-loader#75]
Is there a way to get the built in jsx support of the typescript compiler to work? The only solution I found is to pipe the output to the babel-loader. It looks as if it worked at some point (around `0.6`).

**Comment by s-panferov** [comment]
@kraf please make sure you have `"jsx": "react"` property inside your tsconfig file. See more detailed info [here](https://github.com/Microsoft/TypeScript/wiki/JSX).

**Comment by kraf** [comment]
It's in there, I can compile with `tsc`. I also tried passing it in additionally with `awesome-typescript?jsx=react` but no luck. It seems to be treating it like `preserve`.

##### webpack.config.js
```javascript
module.exports = {
    entry: './entry',
    output: {
        path: __dirname,
        filename: 'bundle.js'
    },
    resolve: {
        extensions: ['', '.ts', '.tsx']
    },
    module: {
        loaders: [
            {
                test: /\.tsx?$/,
                loaders: 'awesome-typescript'
            }
        ]
    }
};
```

##### entry.tsx
```typescript
/// <reference path="typings/tsd.d.ts" />

import * as React from 'react';

interface Props {}

class MyComponent extends React.Component<Props, {}> {
    render() {
        return <div />;
    }
}
```

##### tsconfig.json
```json
{
    "compilerOptions": {
        "module": "commonjs",
        "jsx": "react"
    }
}
```

**Comment by s-panferov** [comment]
@kraf do you have `tsconfig` file? Maybe you have the option there?

**Comment by s-panferov** [comment]
@kraf please try with v0.15.3

**Comment by kraf** [comment]
it works, thanks!
