### ISSUE TITLE
Cannot use node.d.ts reference file.

### ISSUE THREAD

**Issue by cloppy** [s-panferov/awesome-typescript-loader#8]
I tried to get your loader working, but I constantly get errors.

I am using awesome typescript loader at Version 0.3.0-rc.1 and webpack 1.8.9

This is my webpack.config.js:

```javascript
module.exports = {
    entry: './ui/index.ts',
    output: {
        path: __dirname + '/build-ui',
        filename: 'app.js',
        publicPath: 'http://localhost:8090/assets'
    },
    module: {
        loaders: [
            {
                test: /\.jsx$/,
                loader: 'jsx-loader?insertPragma=React.DOM&harmony'
            },
            {
                test: /\.css$/,
                loader: "style-loader!css-loader"
            },
            {
                test: /\.scss$/,
                loader: "style-loader!css-loader!sass-loader"
            },
            {
                test: /\.(png|jpg)$/,
                loader: 'url-loader?limit=8192'
            },
            {
                test: /\.ts$/,
                loader: 'awesome-typescript-loader'
            }
        ]
    },
    resolve: {
        extensions: ['', '.js', '.jsx', '.ts']
    }
};
```

When I run the webpack dev server and my index.ts looks like this:

```javascript
alert('hello');
```

It states the following error:

```
ERROR in ./ui/index.ts
/Users/..../typings/node/node.d.ts:29:12 
Subsequent variable declarations must have the same type.  Variable 'require' must be of type 'WebpackRequire', but here has type '{ (id: string): any; resolve(id: string): string; cache: any; extensions: any; main: any; }'.
```

Same when I put in the reference path.

When I try to import the React.js via `import React = require('react');` it states:

```
ERROR in ./ui/index.ts
Module build failed: Cannot resolve module 'child_process' in /..../typings/node
    Required in /..../typings/node/node.d.ts
```

I copied the node.d.ts file from your repo, still no luck. Any suggestions?

**Comment by cloppy** [comment]
Same with rc2

**Comment by s-panferov** [comment]
@cloppy I think that node's `require` function type conflicts with one that this loader provides. I'll think about how to fix this. Thanks for your report!

**Comment by s-panferov** [comment]
@cloppy try 0.3.0-rc.3 with `?emitRequireType=false&library=es6` loader options.

**Comment by s-panferov** [comment]
@cloppy 	see https://github.com/s-panferov/awesome-typescript-loader#emitrequiretype-boolean-defaulttrue section for the details.

**Comment by s-panferov** [comment]
@cloppy I think that error has been fixed. Please feel free to reopen the issue if something is wrong.
