### ISSUE TITLE
Cannot find module when use module with typings in package.json

### ISSUE THREAD

**Issue by squarepants** [s-panferov/awesome-typescript-loader#81]
webpack result was fine, but I got an error when packing , I'm new to typescript , please help if something I wrote was wrong.
```
ERROR in [default] /Users/***/Projects/tstest/index.ts:2:22 
Cannot find module 'beth'.
```

beth is a test npm module
typing file is in the npm module and config in module package.json with typings
beth.d.ts in npm module beth

```
declare module Beth {
	interface Person {
		name: string,
		age: number,
		color?: string
	}

	function printTest(person: Person): void;
	
}

export = Beth;
```
index.ts in my project
```
import * as Beth from "beth";

Beth.printTest({
	name: "yl",
	age: 23
});
```

webpack.config.js in my project
```
module.exports = {
    entry: "./index.ts",
    output: {
        path: __dirname + "/dist",
        filename: "bundle.js"
    },
	// Currently we need to add '.ts' to resolve.extensions array.
	resolve: {
		extensions: ['', '.ts', '.webpack.js', '.web.js', '.js']
	},
	module: {
		loaders: [
			{
				test: /\.ts$/,
				loader: 'awesome-typescript-loader'
			}
		]
	}
}
```

**Comment by s-panferov** [comment]
@squarepants as I can see, your `beth.d.ts` doesn't seem correct. You can't use external modules and `export =` syntax if you want your module to be visible via `import * as Beth from "beth";`.

The right way to do this:

**beth.d.ts**:

```    
export interface Person {
        name: string,
        age: number,
        color?: string
    }

export function printTest(person: Person): void;
```

Please feel free to reopen if you have any other questions.

**Comment by squarepants** [comment]
Thank you @s-panferov, Great help!!!
