### ISSUE TITLE
Webpack source map examples?

### ISSUE THREAD

**Issue by hydrotik** [s-panferov/awesome-typescript-loader#85]
I'm currently using inline-source-map in my webpack config and don't seem to be getting to the source file. The error is being captured at my entry file. Is there an example of this or some information on how to set this up? My error is located in a component and I would think I would be able to see the error within that file when everything is set up correctly?

**Comment by s-panferov** [comment]
Everything should work out of the box. If you're still interested, please provide your `webpack.config.js`.

**Comment by Ciantic** [comment]
I'm having issue also, the source maps are not generated with Babel options:

```
    devtool: 'source-map',
    module: {
        preLoaders: [
            { test: /\.tsx?$/, loader: "tslint", include: appDir },
        ],
        noParse: [],
        loaders: [
            { test: /\.tsx?$/, loaders: ['awesome-typescript-loader?{tsconfig:"tsconfig.webpack.json", useBabel:true, babelOptions: { presets: ["es2015-native-modules"], sourceMaps : true } }'], include: appDir },
...
```
