### ISSUE TITLE
Console.log in npm distribution

### ISSUE THREAD

**Issue by tlancina** [s-panferov/awesome-typescript-loader#86]
I believe there's a `console.log` in `dist.babel/instance.js` on line 287 in the latest npm release.

**Comment by mcrawshaw** [comment]
+1

**Comment by s-panferov** [comment]
@tlancina @mcrawshaw sorry, I've forgot to rebuild my code with babel after removing this debug logging line. Fixed in v0.15.7

**Comment by mcrawshaw** [comment]
@s-panferov thanks for the quick fix!

**Comment by tlancina** [comment]
No worries, thanks again for the speedy response :thumbsup:
