### ISSUE TITLE
Ability to use outside of webpack?

### ISSUE THREAD

**Issue by hydrotik** [s-panferov/awesome-typescript-loader#93]
Any thoughts on the possibility of using this outside web pack, say to transpile views on the server side for something like express/hapi?

**Comment by hydrotik** [comment]
I'm in the process of working on hapi-typescript-views and there is a lot of similar functionality in both. Going to take a closer look at this myself and report any findings.

**Comment by s-panferov** [comment]
@hydrotik sorry for the delay in answering. I don't think that it's in scope of this library. I believe that most of the work you need can be with TypeScript compiler API.

Feel free to ask any questions.
