### ISSUE TITLE
difference between ts-loader?

### ISSUE THREAD

**Issue by gdi2290** [s-panferov/awesome-typescript-loader#94]
What's the difference between the two loaders?

**Comment by s-panferov** [comment]
This loader was created mostly to speed-up compilation in my own projects. Some of them are quite big and I wanted to have full control on how my files are compiled. There are three big points:

1) awesome-typescript-loader (atl) uses dependency resolution to build modules dependency graph. This speeds up build process in *some* corner cases, but adds a lot of additional complexity. Also it can re-emit all *related* files which is also useful in some *corner* cases.

2) atl has first-class integration with Babel and enables caching possibilities (for speed!)

3) atl is able fork checker to a separate process, which also speeds-up come development scenarios

**Comment by lightning18** [comment]
That should be in the README :smiley:

**Comment by TheLarkInn** [comment]
Would you be willing to expand more on 'first-class integration with Babel'

**Comment by s-panferov** [comment]
@TheLarkInn when `useBabel` and `useCache` flags enabled, typescript emit will be transplied with Babel and cached. So next time if source file (+environment) has the same checksum we can totally skip typescript's and babel's transpiling. This significantly reduces build time.

**Comment by admmasters** [comment]
I'm wondering whether this should be closed as imho its not really an issue. :-p

**Comment by s-panferov** [comment]
Moved to README. Thanks for all!

**Comment by caleb15** [comment]
People referencing this issue should also take a look at https://github.com/s-panferov/awesome-typescript-loader/issues/497

According to @bengrunfeld ts-loader is about 10-17 seconds faster than awesome-typescript-loader.
