### ISSUE TITLE
HMR Doesn't work if there is compiled file nearby ts file

### ISSUE THREAD

**Issue by aspirisen** [s-panferov/awesome-typescript-loader#98]
It seems that HMR always reload whole page if there are compiled files nearby `*.ts` files. In the browser console you can see the warning:

```
[HMR] Cannot apply update. Need to do a full reload!
[HMR] Error: Aborted because 244 is not accepted
    at hotApply (http://localhost:8080/app.js:370:31)
    at hotUpdateDownloaded (http://localhost:8080/app.js:283:13)
    at hotAddUpdateChunk (http://localhost:8080/app.js:263:13)
    at webpackHotUpdateCallback (http://localhost:8080/app.js:5:12)
    at http://localhost:8080/0.2df8e109f0c4212ee1a5.hot-update.js:1:1
```

If you delete these `.js` files everything will work ok. On the one hand it is not critical issue, but on the other hand there are several IDE's that can't work with TypeScript without emitting compiled files (Atom, VS Code, Visual Studio).

There is a small [example archive](https://github.com/s-panferov/awesome-typescript-loader/files/120351/example.zip) that demonstrates the issue.

**Comment by s-panferov** [comment]
@aspirisen thanks for your report. Can I see your webpack config?

**Comment by aspirisen** [comment]
@s-panferov Sure:

```
var webpack = require('webpack');

module.exports = {

  context: __dirname,

  entry: ["./app.tsx"],

  output: {
    path: __dirname + "/dist",
    filename: "app.js"
  },

  resolve: {
    root: __dirname,
    extensions: ['', '.js', '.ts', '.tsx']
  },

  module: {
    loaders: [{
      test: /\.tsx?$/,
      loaders: ['react-hot', 'awesome-typescript-loader']
    }]
  },

  plugins: [
    new webpack.HotModuleReplacementPlugin()
  ],

  devServer: {
    inline: true,
    hot: true
  }
};

```

You can find the whole exanple on the link in the topic above

**Comment by s-panferov** [comment]
@aspirisen sorry for the delay in answering. Please try to reorder extensions in your config file to ensure that `.ts` files have priority:

```
extensions: ['', '.ts', '.tsx', '.js']
```

**Comment by s-panferov** [comment]
Please tell if issue will appear after the change.

**Comment by aspirisen** [comment]
I can't check it because i have another configuration now but your answer seems to be true
