### ISSUE TITLE
Webpack dev server not reloading on changes

### ISSUE THREAD

**Issue by ocombe** [s-panferov/awesome-typescript-loader#99]
I added your loader instead of ts-loader (which works fine for me), and now my page doesn't reload on changes.
It recompiles but I get the messages:
```
[WDS] App updated. Recompiling...
[WDS] Nothing changed.
```
It says that nothing changed and it doesn't reload the page :(

In my shell I have the messages:
```sh
chunk    {0} js/common.js (common) 0 bytes
chunk    {1} js/vendor.js (vendor) 5.48 MB {0}
     + 561 hidden modules
chunk    {2} js/app.js (app) 18.4 kB {0}
  [328] ./src/app/components/home/home.ts 1.42 kB {2} [built]
     + 15 hidden modules
Child html-webpack-plugin for "index.html":
    chunk    {0} index.html 299 bytes
         + 1 hidden modules
webpack: bundle is now VALID.
[default] Ok, 1.202 sec.
[default] Checking started in a separate process...
[default] Ok, 0.006 sec.
```

You can find my repository here: https://github.com/ocombe/ng2-webpack/tree/awesome-typescript
On the branch awesome-typescript it uses your lib.

I'm wondering if the problem might be webpack 2 ? Or is it a config problem ?

**Comment by s-panferov** [comment]
@ocombe sorry for the delay in answering.

I've tried to build your branch and everything works fine for me, page reloads! Could you please try the latest loader version?

**Comment by ocombe** [comment]
I'm on windows, maybe that's the problem ?

**Comment by s-panferov** [comment]
Maybe, I'll try to run it at my windows virtual machine

**Comment by Ciantic** [comment]
Webpack 2 problem I think, there is even error message:

Error: Signature changed: context parameter added
    Required in C:\...\App\Components\Counter.tsx

If one googles the "Signature changed: context parameter added" it's something other webpack loaders need to fix also for webpack 2.

Should this loader even work with webpack 2 yet?

**Comment by Ciantic** [comment]
Ah there is some deprecation notice in here:
https://github.com/webpack/enhanced-resolve/blob/master/lib/Resolver.js#L28

The awesome-typescript-loader is using old format, but it's bizarre because I thought the package.json versions would work...

**Comment by Ciantic** [comment]
Okay sorry for spamming, but the problem is now clear: 

When one installs webpack 2, it installs enhanced-resolver 2

but awesome-typescript-loader is pegged with ^ modifier:

https://github.com/s-panferov/awesome-typescript-loader/blob/master/package.json#L34

To work with any major version, which is not true of course.

Solution is to peg it to 0.9.x or update awesome-typescript-loader to work with enhanced resolver 2.

**Comment by Ciantic** [comment]
HOT FIX:

If you use babel, open **awesome-typescript-loader/dist.babel/instance.js**, if you use without babel open **awesome-typescript-loader/dist/instance.js**

Find line:
```resolver = deps_1.createResolver(compiler.options.externals, state.options.exclude || [], watching.compiler.resolvers.normal.resolve);```

Replace with
```resolver = deps_1.createResolver(compiler.options.externals, state.options.exclude || [], function (a,b,c) { return watching.compiler.resolvers.normal.resolve({}, a,b,c); });
```

**Comment by s-panferov** [comment]
@Ciantic 	thanks a lot for your investigation! I'll fix everything tomorrow morning (GMT+3).

**Comment by s-panferov** [comment]
Please try v0.17.0-rc.4

**Comment by Ciantic** [comment]
Now I'm getting a different error:

```
Error: this.doResolve is not a function
```

This happens when changing a file and live reload triggers, not on the first run.

**Comment by Ciantic** [comment]
It's working! I just had to uninstall my version it was conflicting somehow.
 Thanks for fixing!

**Comment by Ciantic** [comment]
@s-panferov I made a simple repo: https://github.com/Ciantic/webpack2-awesome-typescript-bug-repro if you want to try the new error `Error: this.doResolve is not a function` in rc4.

**Comment by s-panferov** [comment]
@Ciantic thanks again. Your repo helped a lot. Please try v0.17.0-rc.5

**Comment by Ciantic** [comment]
It works now, thank you!
